$ Spice netlist generated by v2lvs
$ v2020.1_25.14    Mon Feb 3 16:40:08 PST 2020
*.BUSDELIMITER [ 

.SUBCKT datapath p_0[23] p_0[22] p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] 
+ p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] 
+ p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] Accumulator[23] 
+ Accumulator[22] Accumulator[21] Accumulator[20] Accumulator[19] 
+ Accumulator[18] Accumulator[17] Accumulator[16] Accumulator[15] 
+ Accumulator[14] Accumulator[13] Accumulator[12] Accumulator[11] 
+ Accumulator[10] Accumulator[9] Accumulator[8] Accumulator[7] Accumulator[6] 
+ Accumulator[5] Accumulator[4] Accumulator[3] Accumulator[2] Accumulator[1] 
+ Accumulator[0] Accumulator1[23] Accumulator1[22] Accumulator1[21] 
+ Accumulator1[20] Accumulator1[19] Accumulator1[18] Accumulator1[17] 
+ Accumulator1[16] Accumulator1[15] Accumulator1[14] Accumulator1[13] 
+ Accumulator1[12] Accumulator1[11] Accumulator1[10] Accumulator1[9] 
+ Accumulator1[8] Accumulator1[7] Accumulator1[6] Accumulator1[5] 
+ Accumulator1[4] Accumulator1[3] Accumulator1[2] Accumulator1[1] 
+ Accumulator1[0] 
Xi_139 INV_X1 $PINS ZN=n_115 A=p_0[20] 
Xi_138 INV_X1 $PINS ZN=n_114 A=Accumulator[20] 
Xi_137 NOR2_X1 $PINS ZN=n_113 A1=p_0[22] A2=Accumulator[22] 
Xi_136 NOR2_X1 $PINS ZN=n_112 A1=p_0[20] A2=Accumulator[20] 
Xi_135 INV_X1 $PINS ZN=n_111 A=n_112 
Xi_134 OAI21_X1 $PINS ZN=n_110 A=n_111 B1=p_0[21] B2=Accumulator[21] 
Xi_133 NOR2_X1 $PINS ZN=n_109 A1=p_0[19] A2=Accumulator[19] 
Xi_132 NOR2_X1 $PINS ZN=n_108 A1=p_0[17] A2=Accumulator[17] 
Xi_131 OAI22_X1 $PINS ZN=n_107 A1=p_0[17] A2=Accumulator[17] B1=p_0[18] 
+ B2=Accumulator[18] 
Xi_130 OR2_X1 $PINS ZN=n_106 A1=n_109 A2=n_107 
Xi_129 NAND2_X1 $PINS ZN=n_105 A1=p_0[16] A2=Accumulator[16] 
Xi_128 AOI22_X1 $PINS ZN=n_104 A1=p_0[16] A2=Accumulator[16] B1=p_0[17] 
+ B2=Accumulator[17] 
Xi_127 NAND2_X1 $PINS ZN=n_103 A1=p_0[18] A2=Accumulator[18] 
Xi_126 OAI22_X1 $PINS ZN=n_102 A1=n_106 A2=n_104 B1=n_109 B2=n_103 
Xi_125 AND2_X1 $PINS ZN=n_101 A1=p_0[3] A2=Accumulator[3] 
Xi_124 NAND2_X1 $PINS ZN=n_100 A1=p_0[2] A2=Accumulator[2] 
Xi_123 NOR2_X1 $PINS ZN=n_99 A1=p_0[1] A2=Accumulator[1] 
Xi_122 NAND2_X1 $PINS ZN=n_98 A1=p_0[0] A2=Accumulator[0] 
Xi_121 NAND2_X1 $PINS ZN=n_97 A1=p_0[1] A2=Accumulator[1] 
Xi_120 AOI21_X1 $PINS ZN=n_96 A=n_99 B1=n_98 B2=n_97 
Xi_119 OAI21_X1 $PINS ZN=n_95 A=n_96 B1=p_0[2] B2=Accumulator[2] 
Xi_118 NAND2_X1 $PINS ZN=n_94 A1=n_100 A2=n_95 
Xi_117 OAI22_X1 $PINS ZN=n_93 A1=p_0[3] A2=Accumulator[3] B1=n_101 B2=n_94 
Xi_116 NOR2_X1 $PINS ZN=n_92 A1=p_0[7] A2=Accumulator[7] 
Xi_115 NOR2_X1 $PINS ZN=n_91 A1=p_0[5] A2=Accumulator[5] 
Xi_114 NOR2_X1 $PINS ZN=n_90 A1=p_0[6] A2=Accumulator[6] 
Xi_113 OR3_X1 $PINS ZN=n_89 A1=n_92 A2=n_90 A3=n_91 
Xi_112 NOR2_X1 $PINS ZN=n_88 A1=p_0[4] A2=Accumulator[4] 
Xi_111 NOR3_X1 $PINS ZN=n_87 A1=n_89 A2=n_88 A3=n_93 
Xi_110 NAND2_X1 $PINS ZN=n_86 A1=p_0[4] A2=Accumulator[4] 
Xi_109 NAND2_X1 $PINS ZN=n_85 A1=p_0[5] A2=Accumulator[5] 
Xi_108 AOI21_X1 $PINS ZN=n_84 A=n_89 B1=n_86 B2=n_85 
Xi_107 AND2_X1 $PINS ZN=n_83 A1=p_0[7] A2=Accumulator[7] 
Xi_106 NAND2_X1 $PINS ZN=n_82 A1=p_0[6] A2=Accumulator[6] 
Xi_105 INV_X1 $PINS ZN=n_81 A=n_82 
Xi_104 NOR2_X1 $PINS ZN=n_80 A1=n_92 A2=n_82 
Xi_103 NOR4_X1 $PINS ZN=n_79 A1=n_83 A2=n_80 A3=n_84 A4=n_87 
Xi_102 NOR2_X1 $PINS ZN=n_78 A1=p_0[11] A2=Accumulator[11] 
Xi_101 NOR2_X1 $PINS ZN=n_77 A1=p_0[9] A2=Accumulator[9] 
Xi_100 NOR2_X1 $PINS ZN=n_76 A1=p_0[10] A2=Accumulator[10] 
Xi_99 OR3_X1 $PINS ZN=n_75 A1=n_78 A2=n_76 A3=n_77 
Xi_98 NOR2_X1 $PINS ZN=n_74 A1=p_0[8] A2=Accumulator[8] 
Xi_97 NOR3_X1 $PINS ZN=n_73 A1=n_75 A2=n_74 A3=n_79 
Xi_96 NAND2_X1 $PINS ZN=n_72 A1=p_0[8] A2=Accumulator[8] 
Xi_95 NAND2_X1 $PINS ZN=n_71 A1=p_0[9] A2=Accumulator[9] 
Xi_94 AOI21_X1 $PINS ZN=n_70 A=n_75 B1=n_72 B2=n_71 
Xi_93 AND2_X1 $PINS ZN=n_69 A1=p_0[11] A2=Accumulator[11] 
Xi_92 NAND2_X1 $PINS ZN=n_68 A1=p_0[10] A2=Accumulator[10] 
Xi_91 INV_X1 $PINS ZN=n_67 A=n_68 
Xi_90 NOR2_X1 $PINS ZN=n_66 A1=n_78 A2=n_68 
Xi_89 NOR4_X1 $PINS ZN=n_65 A1=n_69 A2=n_66 A3=n_70 A4=n_73 
Xi_88 NOR2_X1 $PINS ZN=n_64 A1=p_0[15] A2=Accumulator[15] 
Xi_87 NOR2_X1 $PINS ZN=n_63 A1=p_0[13] A2=Accumulator[13] 
Xi_86 NOR2_X1 $PINS ZN=n_62 A1=p_0[14] A2=Accumulator[14] 
Xi_85 OR3_X1 $PINS ZN=n_61 A1=n_64 A2=n_62 A3=n_63 
Xi_84 NOR2_X1 $PINS ZN=n_60 A1=p_0[12] A2=Accumulator[12] 
Xi_83 NOR3_X1 $PINS ZN=n_59 A1=n_61 A2=n_60 A3=n_65 
Xi_82 NAND2_X1 $PINS ZN=n_58 A1=p_0[12] A2=Accumulator[12] 
Xi_81 NAND2_X1 $PINS ZN=n_57 A1=p_0[13] A2=Accumulator[13] 
Xi_80 AOI21_X1 $PINS ZN=n_56 A=n_61 B1=n_58 B2=n_57 
Xi_79 AND2_X1 $PINS ZN=n_55 A1=p_0[15] A2=Accumulator[15] 
Xi_78 NAND2_X1 $PINS ZN=n_54 A1=p_0[14] A2=Accumulator[14] 
Xi_77 INV_X1 $PINS ZN=n_53 A=n_54 
Xi_76 NOR2_X1 $PINS ZN=n_52 A1=n_64 A2=n_54 
Xi_75 NOR4_X1 $PINS ZN=n_51 A1=n_55 A2=n_52 A3=n_56 A4=n_59 
Xi_74 INV_X1 $PINS ZN=n_50 A=n_51 
Xi_73 NOR2_X1 $PINS ZN=n_49 A1=p_0[16] A2=Accumulator[16] 
Xi_72 NOR2_X1 $PINS ZN=n_48 A1=n_106 A2=n_49 
Xi_71 AOI221_X1 $PINS ZN=n_47 A=n_102 B1=p_0[19] B2=Accumulator[19] C1=n_50 
+ C2=n_48 
Xi_70 OAI21_X1 $PINS ZN=n_46 A=n_47 B1=n_115 B2=n_114 
Xi_69 INV_X1 $PINS ZN=n_45 A=n_46 
Xi_68 NOR3_X1 $PINS ZN=n_44 A1=n_113 A2=n_110 A3=n_45 
Xi_67 NAND2_X1 $PINS ZN=n_43 A1=p_0[21] A2=Accumulator[21] 
Xi_66 NOR2_X1 $PINS ZN=n_42 A1=n_113 A2=n_43 
Xi_65 AOI211_X1 $PINS ZN=n_41 A=n_42 B=n_44 C1=p_0[22] C2=Accumulator[22] 
Xi_64 XNOR2_X1 $PINS ZN=Accumulator1[23] A=p_0[23] B=n_41 
Xi_63 AOI21_X1 $PINS ZN=n_40 A=n_113 B1=p_0[22] B2=Accumulator[22] 
Xi_62 OAI21_X1 $PINS ZN=n_39 A=n_111 B1=n_115 B2=n_114 
Xi_61 OAI21_X1 $PINS ZN=n_38 A=n_43 B1=n_110 B2=n_45 
Xi_60 XOR2_X1 $PINS Z=Accumulator1[22] A=n_40 B=n_38 
Xi_59 OAI21_X1 $PINS ZN=n_37 A=n_43 B1=p_0[21] B2=Accumulator[21] 
Xi_58 NOR2_X1 $PINS ZN=n_36 A1=n_112 A2=n_45 
Xi_57 XNOR2_X1 $PINS ZN=Accumulator1[21] A=n_37 B=n_36 
Xi_56 XOR2_X1 $PINS Z=Accumulator1[20] A=n_47 B=n_39 
Xi_55 AOI21_X1 $PINS ZN=n_35 A=n_109 B1=p_0[19] B2=Accumulator[19] 
Xi_54 OAI21_X1 $PINS ZN=n_34 A=n_105 B1=p_0[16] B2=Accumulator[16] 
Xi_53 AOI21_X1 $PINS ZN=n_33 A=n_49 B1=n_105 B2=n_51 
Xi_52 AOI21_X1 $PINS ZN=n_32 A=n_33 B1=p_0[17] B2=Accumulator[17] 
Xi_51 AOI21_X1 $PINS ZN=n_31 A=n_108 B1=p_0[17] B2=Accumulator[17] 
Xi_50 OAI21_X1 $PINS ZN=n_30 A=n_103 B1=n_107 B2=n_32 
Xi_49 XOR2_X1 $PINS Z=Accumulator1[19] A=n_35 B=n_30 
Xi_48 OAI21_X1 $PINS ZN=n_29 A=n_103 B1=p_0[18] B2=Accumulator[18] 
Xi_47 NOR2_X1 $PINS ZN=n_28 A1=n_108 A2=n_32 
Xi_46 XNOR2_X1 $PINS ZN=Accumulator1[18] A=n_29 B=n_28 
Xi_45 XOR2_X1 $PINS Z=Accumulator1[17] A=n_33 B=n_31 
Xi_44 XOR2_X1 $PINS Z=Accumulator1[16] A=n_51 B=n_34 
Xi_43 NOR2_X1 $PINS ZN=n_27 A1=n_64 A2=n_55 
Xi_42 OAI21_X1 $PINS ZN=n_26 A=n_58 B1=p_0[12] B2=Accumulator[12] 
Xi_41 AOI21_X1 $PINS ZN=n_25 A=n_60 B1=n_65 B2=n_58 
Xi_40 INV_X1 $PINS ZN=n_24 A=n_25 
Xi_39 AOI21_X1 $PINS ZN=n_23 A=n_63 B1=n_57 B2=n_24 
Xi_38 AOI21_X1 $PINS ZN=n_22 A=n_63 B1=p_0[13] B2=Accumulator[13] 
Xi_37 OAI22_X1 $PINS ZN=n_21 A1=p_0[14] A2=Accumulator[14] B1=n_53 B2=n_23 
Xi_36 XNOR2_X1 $PINS ZN=Accumulator1[15] A=n_27 B=n_21 
Xi_35 NOR2_X1 $PINS ZN=n_20 A1=n_62 A2=n_53 
Xi_34 XOR2_X1 $PINS Z=Accumulator1[14] A=n_23 B=n_20 
Xi_33 XOR2_X1 $PINS Z=Accumulator1[13] A=n_25 B=n_22 
Xi_32 XOR2_X1 $PINS Z=Accumulator1[12] A=n_65 B=n_26 
Xi_31 NOR2_X1 $PINS ZN=n_19 A1=n_78 A2=n_69 
Xi_30 AOI21_X1 $PINS ZN=n_18 A=n_74 B1=p_0[8] B2=Accumulator[8] 
Xi_29 AOI21_X1 $PINS ZN=n_17 A=n_74 B1=n_79 B2=n_72 
Xi_28 INV_X1 $PINS ZN=n_16 A=n_17 
Xi_27 AOI21_X1 $PINS ZN=n_15 A=n_77 B1=n_71 B2=n_16 
Xi_26 AOI21_X1 $PINS ZN=n_14 A=n_77 B1=p_0[9] B2=Accumulator[9] 
Xi_25 OAI22_X1 $PINS ZN=n_13 A1=p_0[10] A2=Accumulator[10] B1=n_67 B2=n_15 
Xi_24 XNOR2_X1 $PINS ZN=Accumulator1[11] A=n_19 B=n_13 
Xi_23 NOR2_X1 $PINS ZN=n_12 A1=n_76 A2=n_67 
Xi_22 XOR2_X1 $PINS Z=Accumulator1[10] A=n_15 B=n_12 
Xi_21 XOR2_X1 $PINS Z=Accumulator1[9] A=n_17 B=n_14 
Xi_20 XNOR2_X1 $PINS ZN=Accumulator1[8] A=n_79 B=n_18 
Xi_19 NOR2_X1 $PINS ZN=n_11 A1=n_92 A2=n_83 
Xi_18 OAI21_X1 $PINS ZN=n_10 A=n_86 B1=p_0[4] B2=Accumulator[4] 
Xi_17 AOI21_X1 $PINS ZN=n_9 A=n_88 B1=n_93 B2=n_86 
Xi_16 INV_X1 $PINS ZN=n_8 A=n_9 
Xi_15 AOI21_X1 $PINS ZN=n_7 A=n_91 B1=n_85 B2=n_8 
Xi_14 AOI21_X1 $PINS ZN=n_6 A=n_91 B1=p_0[5] B2=Accumulator[5] 
Xi_13 OAI22_X1 $PINS ZN=n_5 A1=p_0[6] A2=Accumulator[6] B1=n_81 B2=n_7 
Xi_12 XNOR2_X1 $PINS ZN=Accumulator1[7] A=n_11 B=n_5 
Xi_11 NOR2_X1 $PINS ZN=n_4 A1=n_90 A2=n_81 
Xi_10 XOR2_X1 $PINS Z=Accumulator1[6] A=n_7 B=n_4 
Xi_9 XOR2_X1 $PINS Z=Accumulator1[5] A=n_9 B=n_6 
Xi_8 XOR2_X1 $PINS Z=Accumulator1[4] A=n_93 B=n_10 
Xi_7 XOR2_X1 $PINS Z=n_3 A=p_0[3] B=Accumulator[3] 
Xi_6 XOR2_X1 $PINS Z=Accumulator1[3] A=n_94 B=n_3 
Xi_5 OAI21_X1 $PINS ZN=n_2 A=n_100 B1=p_0[2] B2=Accumulator[2] 
Xi_4 XNOR2_X1 $PINS ZN=Accumulator1[2] A=n_96 B=n_2 
Xi_3 OAI21_X1 $PINS ZN=n_1 A=n_97 B1=p_0[1] B2=Accumulator[1] 
Xi_2 XOR2_X1 $PINS Z=Accumulator1[1] A=n_98 B=n_1 
Xi_1 OAI21_X1 $PINS ZN=n_0 A=n_98 B1=p_0[0] B2=Accumulator[0] 
Xi_0 INV_X1 $PINS ZN=Accumulator1[0] A=n_0 
.ENDS

.SUBCKT unsigned_seq_multiplier clk_CTS_1_PP_2 CTSclk_CTS_1_PP_2PP_0 
+ CTSclk_CTS_1_PP_2PP_1 clk rst start_s a[23] a[22] a[21] a[20] a[19] a[18] 
+ a[17] a[16] a[15] a[14] a[13] a[12] a[11] a[10] a[9] a[8] a[7] a[6] a[5] a[4] 
+ a[3] a[2] a[1] a[0] b[23] b[22] b[21] b[20] b[19] b[18] b[17] b[16] b[15] 
+ b[14] b[13] b[12] b[11] b[10] b[9] b[8] b[7] b[6] b[5] b[4] b[3] b[2] b[1] 
+ b[0] c[47] c[46] c[45] c[44] c[43] c[42] c[41] c[40] c[39] c[38] c[37] c[36] 
+ c[35] c[34] c[33] c[32] c[31] c[30] c[29] c[28] c[27] c[26] c[25] c[24] c[23] 
+ c[22] c[21] c[20] c[19] c[18] c[17] c[16] c[15] c[14] c[13] c[12] c[11] c[10] 
+ c[9] c[8] c[7] c[6] c[5] c[4] c[3] c[2] c[1] c[0] 
Xi_1_119 INV_X1 $PINS ZN=n_1_26 A=hfn_ipo_n3 
Xi_1_118 MUX2_X1 $PINS Z=n_142 A=A_r[22] B=a[22] S=hfn_ipo_n3 
Xi_1_117 MUX2_X1 $PINS Z=n_141 A=A_r[21] B=a[21] S=hfn_ipo_n3 
Xi_1_116 MUX2_X1 $PINS Z=n_140 A=A_r[20] B=a[20] S=hfn_ipo_n3 
Xi_1_115 MUX2_X1 $PINS Z=n_139 A=A_r[19] B=a[19] S=hfn_ipo_n3 
Xi_1_114 MUX2_X1 $PINS Z=n_138 A=A_r[18] B=a[18] S=hfn_ipo_n3 
Xi_1_113 MUX2_X1 $PINS Z=n_137 A=A_r[17] B=a[17] S=hfn_ipo_n3 
Xi_1_112 MUX2_X1 $PINS Z=n_136 A=A_r[16] B=a[16] S=hfn_ipo_n3 
Xi_1_111 MUX2_X1 $PINS Z=n_135 A=A_r[15] B=a[15] S=hfn_ipo_n3 
Xi_1_110 MUX2_X1 $PINS Z=n_134 A=A_r[14] B=a[14] S=hfn_ipo_n3 
Xi_1_109 MUX2_X1 $PINS Z=n_133 A=A_r[13] B=a[13] S=hfn_ipo_n3 
Xi_1_108 MUX2_X1 $PINS Z=n_132 A=A_r[12] B=a[12] S=hfn_ipo_n3 
Xi_1_107 MUX2_X1 $PINS Z=n_131 A=A_r[11] B=a[11] S=hfn_ipo_n3 
Xi_1_106 MUX2_X1 $PINS Z=n_130 A=A_r[10] B=a[10] S=hfn_ipo_n3 
Xi_1_105 MUX2_X1 $PINS Z=n_129 A=A_r[9] B=a[9] S=hfn_ipo_n3 
Xi_1_104 MUX2_X1 $PINS Z=n_128 A=A_r[8] B=a[8] S=hfn_ipo_n3 
Xi_1_103 MUX2_X1 $PINS Z=n_127 A=A_r[7] B=a[7] S=hfn_ipo_n3 
Xi_1_102 MUX2_X1 $PINS Z=n_126 A=A_r[6] B=a[6] S=hfn_ipo_n3 
Xi_1_101 MUX2_X1 $PINS Z=n_125 A=A_r[5] B=a[5] S=hfn_ipo_n3 
Xi_1_100 MUX2_X1 $PINS Z=n_124 A=A_r[4] B=a[4] S=hfn_ipo_n3 
Xi_1_99 MUX2_X1 $PINS Z=n_123 A=A_r[3] B=a[3] S=hfn_ipo_n3 
Xi_1_98 MUX2_X1 $PINS Z=n_122 A=A_r[2] B=a[2] S=hfn_ipo_n3 
Xi_1_97 MUX2_X1 $PINS Z=n_121 A=A_r[1] B=a[1] S=hfn_ipo_n3 
Xi_1_96 MUX2_X1 $PINS Z=n_119 A=A_r[0] B=a[0] S=hfn_ipo_n3 
Xi_1_95 AND2_X1 $PINS ZN=n_118 A1=n_1_26 A2=n_0 
Xi_1_94 AND2_X1 $PINS ZN=n_117 A1=n_1_26 A2=c[45] 
Xi_1_93 AND2_X1 $PINS ZN=n_116 A1=n_1_26 A2=c[44] 
Xi_1_92 AND2_X1 $PINS ZN=n_115 A1=n_1_26 A2=c[43] 
Xi_1_91 AND2_X1 $PINS ZN=n_114 A1=n_1_26 A2=c[42] 
Xi_1_90 AND2_X1 $PINS ZN=n_113 A1=n_1_26 A2=c[41] 
Xi_1_89 AND2_X1 $PINS ZN=n_112 A1=n_1_26 A2=c[40] 
Xi_1_88 AND2_X1 $PINS ZN=n_111 A1=n_1_26 A2=c[39] 
Xi_1_87 AND2_X1 $PINS ZN=n_110 A1=n_1_26 A2=c[38] 
Xi_1_86 AND2_X1 $PINS ZN=n_109 A1=n_1_26 A2=c[37] 
Xi_1_85 AND2_X1 $PINS ZN=n_108 A1=n_1_26 A2=c[36] 
Xi_1_84 AND2_X1 $PINS ZN=n_107 A1=n_1_26 A2=c[35] 
Xi_1_83 AND2_X1 $PINS ZN=n_106 A1=n_1_26 A2=c[34] 
Xi_1_82 AND2_X1 $PINS ZN=n_105 A1=n_1_26 A2=c[33] 
Xi_1_81 AND2_X1 $PINS ZN=n_104 A1=n_1_26 A2=c[32] 
Xi_1_80 AND2_X1 $PINS ZN=n_103 A1=n_1_26 A2=c[31] 
Xi_1_79 AND2_X1 $PINS ZN=n_102 A1=n_1_26 A2=c[30] 
Xi_1_78 AND2_X1 $PINS ZN=n_101 A1=n_1_26 A2=c[29] 
Xi_1_77 AND2_X1 $PINS ZN=n_100 A1=n_1_26 A2=c[28] 
Xi_1_76 AND2_X1 $PINS ZN=n_99 A1=n_1_26 A2=c[27] 
Xi_1_75 AND2_X1 $PINS ZN=n_98 A1=n_1_26 A2=c[26] 
Xi_1_74 AND2_X1 $PINS ZN=n_97 A1=n_1_26 A2=c[25] 
Xi_1_73 AND2_X1 $PINS ZN=n_96 A1=n_1_26 A2=c[24] 
Xi_1_72 NOR2_X1 $PINS ZN=n_1_25 A1=n_1_0 A2=n_1_1 
Xi_1_71 INV_X1 $PINS ZN=n_71 A=n_1_25 
Xi_1_70 INV_X1 $PINS ZN=n_70 A=n_1_24 
Xi_1_69 AOI22_X1 $PINS ZN=n_1_24 A1=a[22] A2=n_1_0 B1=A_r[22] B2=n_1_1 
Xi_1_68 INV_X1 $PINS ZN=n_69 A=n_1_23 
Xi_1_67 AOI22_X1 $PINS ZN=n_1_23 A1=a[21] A2=n_1_0 B1=A_r[21] B2=n_1_1 
Xi_1_66 INV_X1 $PINS ZN=n_68 A=n_1_22 
Xi_1_65 AOI22_X1 $PINS ZN=n_1_22 A1=a[20] A2=n_1_0 B1=A_r[20] B2=n_1_1 
Xi_1_64 INV_X1 $PINS ZN=n_67 A=n_1_21 
Xi_1_63 AOI22_X1 $PINS ZN=n_1_21 A1=a[19] A2=n_1_0 B1=A_r[19] B2=n_1_1 
Xi_1_62 INV_X1 $PINS ZN=n_66 A=n_1_20 
Xi_1_61 AOI22_X1 $PINS ZN=n_1_20 A1=a[18] A2=n_1_0 B1=A_r[18] B2=n_1_1 
Xi_1_60 INV_X1 $PINS ZN=n_65 A=n_1_19 
Xi_1_59 AOI22_X1 $PINS ZN=n_1_19 A1=a[17] A2=n_1_0 B1=A_r[17] B2=n_1_1 
Xi_1_58 INV_X1 $PINS ZN=n_64 A=n_1_18 
Xi_1_57 AOI22_X1 $PINS ZN=n_1_18 A1=a[16] A2=n_1_0 B1=A_r[16] B2=n_1_1 
Xi_1_56 INV_X1 $PINS ZN=n_63 A=n_1_17 
Xi_1_55 AOI22_X1 $PINS ZN=n_1_17 A1=a[15] A2=n_1_0 B1=A_r[15] B2=n_1_1 
Xi_1_54 INV_X1 $PINS ZN=n_62 A=n_1_16 
Xi_1_53 AOI22_X1 $PINS ZN=n_1_16 A1=a[14] A2=n_1_0 B1=A_r[14] B2=n_1_1 
Xi_1_52 INV_X1 $PINS ZN=n_61 A=n_1_15 
Xi_1_51 AOI22_X1 $PINS ZN=n_1_15 A1=a[13] A2=n_1_0 B1=A_r[13] B2=n_1_1 
Xi_1_50 INV_X1 $PINS ZN=n_60 A=n_1_14 
Xi_1_49 AOI22_X1 $PINS ZN=n_1_14 A1=a[12] A2=n_1_0 B1=A_r[12] B2=n_1_1 
Xi_1_48 INV_X1 $PINS ZN=n_59 A=n_1_13 
Xi_1_47 AOI22_X1 $PINS ZN=n_1_13 A1=a[11] A2=n_1_0 B1=A_r[11] B2=n_1_1 
Xi_1_46 INV_X1 $PINS ZN=n_58 A=n_1_12 
Xi_1_45 AOI22_X1 $PINS ZN=n_1_12 A1=a[10] A2=n_1_0 B1=A_r[10] B2=n_1_1 
Xi_1_44 INV_X1 $PINS ZN=n_57 A=n_1_11 
Xi_1_43 AOI22_X1 $PINS ZN=n_1_11 A1=a[9] A2=n_1_0 B1=A_r[9] B2=n_1_1 
Xi_1_42 INV_X1 $PINS ZN=n_56 A=n_1_10 
Xi_1_41 AOI22_X1 $PINS ZN=n_1_10 A1=a[8] A2=n_1_0 B1=A_r[8] B2=n_1_1 
Xi_1_40 INV_X1 $PINS ZN=n_55 A=n_1_9 
Xi_1_39 AOI22_X1 $PINS ZN=n_1_9 A1=a[7] A2=n_1_0 B1=A_r[7] B2=n_1_1 
Xi_1_38 INV_X1 $PINS ZN=n_54 A=n_1_8 
Xi_1_37 AOI22_X1 $PINS ZN=n_1_8 A1=a[6] A2=n_1_0 B1=A_r[6] B2=n_1_1 
Xi_1_36 INV_X1 $PINS ZN=n_53 A=n_1_7 
Xi_1_35 AOI22_X1 $PINS ZN=n_1_7 A1=a[5] A2=n_1_0 B1=A_r[5] B2=n_1_1 
Xi_1_34 INV_X1 $PINS ZN=n_52 A=n_1_6 
Xi_1_33 AOI22_X1 $PINS ZN=n_1_6 A1=a[4] A2=n_1_0 B1=A_r[4] B2=n_1_1 
Xi_1_32 INV_X1 $PINS ZN=n_51 A=n_1_5 
Xi_1_31 AOI22_X1 $PINS ZN=n_1_5 A1=a[3] A2=n_1_0 B1=A_r[3] B2=n_1_1 
Xi_1_30 INV_X1 $PINS ZN=n_50 A=n_1_4 
Xi_1_29 AOI22_X1 $PINS ZN=n_1_4 A1=a[2] A2=n_1_0 B1=A_r[2] B2=n_1_1 
Xi_1_28 INV_X1 $PINS ZN=n_49 A=n_1_3 
Xi_1_27 AOI22_X1 $PINS ZN=n_1_3 A1=a[1] A2=n_1_0 B1=A_r[1] B2=n_1_1 
Xi_1_26 INV_X1 $PINS ZN=n_48 A=n_1_2 
Xi_1_25 AOI22_X1 $PINS ZN=n_1_2 A1=a[0] A2=n_1_0 B1=A_r[0] B2=n_1_1 
Xi_1_24 AND2_X1 $PINS ZN=n_1_1 A1=n_1_26 A2=n_23 
Xi_1_23 AND2_X1 $PINS ZN=n_1_0 A1=hfn_ipo_n3 A2=b[0] 
Xi_1_22 OR2_X1 $PINS ZN=n_47 A1=hfn_ipo_n3 A2=c[23] 
Xi_1_21 MUX2_X1 $PINS Z=n_46 A=n_1 B=b[22] S=hfn_ipo_n3 
Xi_1_20 MUX2_X1 $PINS Z=n_45 A=n_2 B=b[21] S=hfn_ipo_n3 
Xi_1_19 MUX2_X1 $PINS Z=n_44 A=n_3 B=b[20] S=hfn_ipo_n3 
Xi_1_18 MUX2_X1 $PINS Z=n_43 A=n_4 B=b[19] S=hfn_ipo_n3 
Xi_1_17 MUX2_X1 $PINS Z=n_42 A=n_5 B=b[18] S=hfn_ipo_n3 
Xi_1_16 MUX2_X1 $PINS Z=n_41 A=n_6 B=b[17] S=hfn_ipo_n3 
Xi_1_15 MUX2_X1 $PINS Z=n_40 A=n_7 B=b[16] S=hfn_ipo_n3 
Xi_1_14 MUX2_X1 $PINS Z=n_39 A=n_8 B=b[15] S=hfn_ipo_n3 
Xi_1_13 MUX2_X1 $PINS Z=n_38 A=n_9 B=b[14] S=hfn_ipo_n3 
Xi_1_12 MUX2_X1 $PINS Z=n_37 A=n_10 B=b[13] S=hfn_ipo_n3 
Xi_1_11 MUX2_X1 $PINS Z=n_36 A=n_11 B=b[12] S=hfn_ipo_n3 
Xi_1_10 MUX2_X1 $PINS Z=n_35 A=n_12 B=b[11] S=hfn_ipo_n3 
Xi_1_9 MUX2_X1 $PINS Z=n_34 A=n_13 B=b[10] S=hfn_ipo_n3 
Xi_1_8 MUX2_X1 $PINS Z=n_33 A=n_14 B=b[9] S=hfn_ipo_n3 
Xi_1_7 MUX2_X1 $PINS Z=n_32 A=n_15 B=b[8] S=hfn_ipo_n3 
Xi_1_6 MUX2_X1 $PINS Z=n_31 A=n_16 B=b[7] S=hfn_ipo_n3 
Xi_1_5 MUX2_X1 $PINS Z=n_30 A=n_17 B=b[6] S=hfn_ipo_n3 
Xi_1_4 MUX2_X1 $PINS Z=n_29 A=n_18 B=b[5] S=hfn_ipo_n3 
Xi_1_3 MUX2_X1 $PINS Z=n_28 A=n_19 B=b[4] S=hfn_ipo_n3 
Xi_1_2 MUX2_X1 $PINS Z=n_27 A=n_20 B=b[3] S=hfn_ipo_n3 
Xi_1_1 MUX2_X1 $PINS Z=n_26 A=n_21 B=b[2] S=hfn_ipo_n3 
Xi_1_0 MUX2_X1 $PINS Z=n_25 A=n_22 B=b[1] S=hfn_ipo_n3 
Xclk_gate_B_r_reg CLKGATETST_X4 $PINS GCK=CTS_n_tid0_6 CK=CTSclk_CTS_1_PP_2PP_0 
+ E=n_24 SE=VSS 
Xi_0_0 INV_X1 $PINS ZN=n_24 A=rst 
XA_r_reg[0] DFF_X1 $PINS Q=A_r[0] CK=CTS_n_tid0_5 D=n_119 
XA_r_reg[1] DFF_X1 $PINS Q=A_r[1] CK=CTS_n_tid0_5 D=n_121 
XA_r_reg[2] DFF_X1 $PINS Q=A_r[2] CK=CTS_n_tid0_5 D=n_122 
XA_r_reg[3] DFF_X1 $PINS Q=A_r[3] CK=CTS_n_tid0_5 D=n_123 
XA_r_reg[4] DFF_X1 $PINS Q=A_r[4] CK=CTS_n_tid0_5 D=n_124 
XA_r_reg[5] DFF_X1 $PINS Q=A_r[5] CK=CTS_n_tid0_5 D=n_125 
XA_r_reg[6] DFF_X1 $PINS Q=A_r[6] CK=CTS_n_tid0_5 D=n_126 
XA_r_reg[7] DFF_X1 $PINS Q=A_r[7] CK=CTS_n_tid0_5 D=n_127 
XA_r_reg[8] DFF_X1 $PINS Q=A_r[8] CK=CTS_n_tid0_5 D=n_128 
XA_r_reg[9] DFF_X1 $PINS Q=A_r[9] CK=CTS_n_tid0_5 D=n_129 
XA_r_reg[10] DFF_X1 $PINS Q=A_r[10] CK=CTS_n_tid0_5 D=n_130 
XA_r_reg[11] DFF_X1 $PINS Q=A_r[11] CK=CTS_n_tid0_5 D=n_131 
XA_r_reg[12] DFF_X1 $PINS Q=A_r[12] CK=CTS_n_tid0_5 D=n_132 
XA_r_reg[13] DFF_X1 $PINS Q=A_r[13] CK=CTS_n_tid0_5 D=n_133 
XA_r_reg[14] DFF_X1 $PINS Q=A_r[14] CK=CTS_n_tid0_5 D=n_134 
XA_r_reg[15] DFF_X1 $PINS Q=A_r[15] CK=CTS_n_tid0_5 D=n_135 
XA_r_reg[16] DFF_X1 $PINS Q=A_r[16] CK=CTS_n_tid0_5 D=n_136 
XA_r_reg[17] DFF_X1 $PINS Q=A_r[17] CK=CTS_n_tid0_5 D=n_137 
XA_r_reg[18] DFF_X1 $PINS Q=A_r[18] CK=CTS_n_tid0_5 D=n_138 
XA_r_reg[19] DFF_X1 $PINS Q=A_r[19] CK=CTS_n_tid0_5 D=n_139 
XA_r_reg[20] DFF_X1 $PINS Q=A_r[20] CK=CTS_n_tid0_5 D=n_140 
XA_r_reg[21] DFF_X1 $PINS Q=A_r[21] CK=CTS_n_tid0_5 D=n_141 
XA_r_reg[22] DFF_X1 $PINS Q=A_r[22] CK=CTS_n_tid0_5 D=n_142 
XB_r_reg[0] DFF_X1 $PINS Q=n_23 CK=CTS_n_tid0_5 D=n_25 
XB_r_reg[1] DFF_X1 $PINS Q=n_22 CK=CTS_n_tid0_5 D=n_26 
XB_r_reg[2] DFF_X1 $PINS Q=n_21 CK=CTS_n_tid0_5 D=n_27 
XB_r_reg[3] DFF_X1 $PINS Q=n_20 CK=CTS_n_tid0_5 D=n_28 
XB_r_reg[4] DFF_X1 $PINS Q=n_19 CK=CTS_n_tid0_5 D=n_29 
XB_r_reg[5] DFF_X1 $PINS Q=n_18 CK=CTS_n_tid0_5 D=n_30 
XB_r_reg[6] DFF_X1 $PINS Q=n_17 CK=CTS_n_tid0_5 D=n_31 
XB_r_reg[7] DFF_X1 $PINS Q=n_16 CK=CTS_n_tid0_5 D=n_32 
XB_r_reg[8] DFF_X1 $PINS Q=n_15 CK=CTS_n_tid0_5 D=n_33 
XB_r_reg[9] DFF_X1 $PINS Q=n_14 CK=CTS_n_tid0_5 D=n_34 
XB_r_reg[10] DFF_X1 $PINS Q=n_13 CK=CTS_n_tid0_5 D=n_35 
XB_r_reg[11] DFF_X1 $PINS Q=n_12 CK=CTS_n_tid0_5 D=n_36 
XB_r_reg[12] DFF_X1 $PINS Q=n_11 CK=CTS_n_tid0_5 D=n_37 
XB_r_reg[13] DFF_X1 $PINS Q=n_10 CK=CTS_n_tid0_5 D=n_38 
XB_r_reg[14] DFF_X1 $PINS Q=n_9 CK=CTS_n_tid0_5 D=n_39 
XB_r_reg[15] DFF_X1 $PINS Q=n_8 CK=CTS_n_tid0_5 D=n_40 
XB_r_reg[16] DFF_X1 $PINS Q=n_7 CK=CTS_n_tid0_5 D=n_41 
XB_r_reg[17] DFF_X1 $PINS Q=n_6 CK=CTS_n_tid0_5 D=n_42 
XB_r_reg[18] DFF_X1 $PINS Q=n_5 CK=CTS_n_tid0_5 D=n_43 
XB_r_reg[19] DFF_X1 $PINS Q=n_4 CK=CTS_n_tid0_5 D=n_44 
XB_r_reg[20] DFF_X1 $PINS Q=n_3 CK=CTS_n_tid0_5 D=n_45 
XB_r_reg[21] DFF_X1 $PINS Q=n_2 CK=CTS_n_tid0_5 D=n_46 
XB_r_reg[22] DFF_X1 $PINS Q=n_1 CK=CTS_n_tid0_5 D=n_47 
XB_r_reg[23] DFF_X1 $PINS Q=c[23] CK=CTS_n_tid0_5 D=n_72 
Xi_4 datapath $PINS Accumulator1[23]=n_95 Accumulator1[22]=n_94 
+ Accumulator1[21]=n_93 Accumulator1[20]=n_92 Accumulator1[19]=n_91 
+ Accumulator1[18]=n_90 Accumulator1[17]=n_89 Accumulator1[16]=n_88 
+ Accumulator1[15]=n_87 Accumulator1[14]=n_86 Accumulator1[13]=n_85 
+ Accumulator1[12]=n_84 Accumulator1[11]=n_83 Accumulator1[10]=n_82 
+ Accumulator1[9]=n_81 Accumulator1[8]=n_80 Accumulator1[7]=n_79 
+ Accumulator1[6]=n_78 Accumulator1[5]=n_77 Accumulator1[4]=n_76 
+ Accumulator1[3]=n_75 Accumulator1[2]=n_74 Accumulator1[1]=n_73 
+ Accumulator1[0]=n_72 Accumulator[23]=uc_0 Accumulator[22]=n_118 
+ Accumulator[21]=n_117 Accumulator[20]=n_116 Accumulator[19]=n_115 
+ Accumulator[18]=n_114 Accumulator[17]=n_113 Accumulator[16]=n_112 
+ Accumulator[15]=n_111 Accumulator[14]=n_110 Accumulator[13]=n_109 
+ Accumulator[12]=n_108 Accumulator[11]=n_107 Accumulator[10]=n_106 
+ Accumulator[9]=n_105 Accumulator[8]=n_104 Accumulator[7]=n_103 
+ Accumulator[6]=n_102 Accumulator[5]=n_101 Accumulator[4]=n_100 
+ Accumulator[3]=n_99 Accumulator[2]=n_98 Accumulator[1]=n_97 Accumulator[0]=n_96 
+ p_0[23]=n_71 p_0[22]=n_70 p_0[21]=n_69 p_0[20]=n_68 p_0[19]=n_67 p_0[18]=n_66 
+ p_0[17]=n_65 p_0[16]=n_64 p_0[15]=n_63 p_0[14]=n_62 p_0[13]=n_61 p_0[12]=n_60 
+ p_0[11]=n_59 p_0[10]=n_58 p_0[9]=n_57 p_0[8]=n_56 p_0[7]=n_55 p_0[6]=n_54 
+ p_0[5]=n_53 p_0[4]=n_52 p_0[3]=n_51 p_0[2]=n_50 p_0[1]=n_49 p_0[0]=n_48 
XAccumulator_reg[0] DFFR_X1 $PINS Q=c[24] CK=clk_CTS_1_PP_2 D=n_73 RN=n_24 
XAccumulator_reg[1] DFFR_X1 $PINS Q=c[25] CK=n_tid1_116 D=n_74 RN=n_24 
XAccumulator_reg[2] DFFR_X1 $PINS Q=c[26] CK=n_tid1_116 D=n_75 RN=n_24 
XAccumulator_reg[3] DFFR_X1 $PINS Q=c[27] CK=n_tid1_116 D=n_76 RN=n_24 
XAccumulator_reg[4] DFFR_X1 $PINS Q=c[28] CK=n_tid1_116 D=n_77 RN=n_24 
XAccumulator_reg[5] DFFR_X1 $PINS Q=c[29] CK=CTSclk_CTS_1_PP_2PP_0 D=n_78 
+ RN=n_24 
XAccumulator_reg[6] DFFR_X1 $PINS Q=c[30] CK=CTSclk_CTS_1_PP_2PP_0 D=n_79 
+ RN=n_24 
XAccumulator_reg[7] DFFR_X1 $PINS Q=c[31] CK=n_tid1_116 D=n_80 RN=n_24 
XAccumulator_reg[8] DFFR_X1 $PINS Q=c[32] CK=n_tid1_116 D=n_81 RN=n_24 
XAccumulator_reg[9] DFFR_X1 $PINS Q=c[33] CK=CTSclk_CTS_1_PP_2PP_0 D=n_82 
+ RN=n_24 
XAccumulator_reg[10] DFFR_X1 $PINS Q=c[34] CK=CTSclk_CTS_1_PP_2PP_0 D=n_83 
+ RN=n_24 
XAccumulator_reg[11] DFFR_X1 $PINS Q=c[35] CK=n_tid1_116 D=n_84 RN=n_24 
XAccumulator_reg[12] DFFR_X1 $PINS Q=c[36] CK=clk_CTS_1_PP_2 D=n_85 RN=n_24 
XAccumulator_reg[13] DFFR_X1 $PINS Q=c[37] CK=clk_CTS_1_PP_2 D=n_86 RN=n_24 
XAccumulator_reg[14] DFFR_X1 $PINS Q=c[38] CK=clk_CTS_1_PP_2 D=n_87 RN=n_24 
XAccumulator_reg[15] DFFR_X1 $PINS Q=c[39] CK=CTSclk_CTS_1_PP_2PP_0 D=n_88 
+ RN=n_24 
XAccumulator_reg[16] DFFR_X1 $PINS Q=c[40] CK=CTSclk_CTS_1_PP_2PP_0 D=n_89 
+ RN=n_24 
XAccumulator_reg[17] DFFR_X1 $PINS Q=c[41] CK=CTSclk_CTS_1_PP_2PP_0 D=n_90 
+ RN=n_24 
XAccumulator_reg[18] DFFR_X1 $PINS Q=c[42] CK=CTSclk_CTS_1_PP_2PP_0 D=n_91 
+ RN=n_24 
XAccumulator_reg[19] DFFR_X1 $PINS Q=c[43] CK=CTSclk_CTS_1_PP_2PP_0 D=n_92 
+ RN=n_24 
XAccumulator_reg[20] DFFR_X1 $PINS Q=c[44] CK=CTSclk_CTS_1_PP_2PP_0 D=n_93 
+ RN=n_24 
XAccumulator_reg[21] DFFR_X1 $PINS Q=c[45] CK=CTSclk_CTS_1_PP_2PP_0 D=n_94 
+ RN=n_24 
XAccumulator_reg[22] DFFR_X1 $PINS Q=n_0 CK=CTSclk_CTS_1_PP_2PP_0 D=n_95 
+ RN=n_24 
Xhfn_ipo_c3 CLKBUF_X3 $PINS Z=hfn_ipo_n3 A=start_s 
XCTS_L3_c_tid0_6 CLKBUF_X3 $PINS Z=CTS_n_tid0_5 A=CTS_n_tid0_6 
XCTS_L2_tid1__c2_tid1__c52 CLKBUF_X1 $PINS Z=n_tid1_116 A=CTSclk_CTS_1_PP_2PP_1 
.ENDS

.SUBCKT fp_mul clk rst a_s[31] a_s[30] a_s[29] a_s[28] a_s[27] a_s[26] a_s[25] 
+ a_s[24] a_s[23] a_s[22] a_s[21] a_s[20] a_s[19] a_s[18] a_s[17] a_s[16] 
+ a_s[15] a_s[14] a_s[13] a_s[12] a_s[11] a_s[10] a_s[9] a_s[8] a_s[7] a_s[6] 
+ a_s[5] a_s[4] a_s[3] a_s[2] a_s[1] a_s[0] b_s[31] b_s[30] b_s[29] b_s[28] 
+ b_s[27] b_s[26] b_s[25] b_s[24] b_s[23] b_s[22] b_s[21] b_s[20] b_s[19] 
+ b_s[18] b_s[17] b_s[16] b_s[15] b_s[14] b_s[13] b_s[12] b_s[11] b_s[10] 
+ b_s[9] b_s[8] b_s[7] b_s[6] b_s[5] b_s[4] b_s[3] b_s[2] b_s[1] b_s[0] 
+ c_out[31] c_out[30] c_out[29] c_out[28] c_out[27] c_out[26] c_out[25] 
+ c_out[24] c_out[23] c_out[22] c_out[21] c_out[20] c_out[19] c_out[18] 
+ c_out[17] c_out[16] c_out[15] c_out[14] c_out[13] c_out[12] c_out[11] 
+ c_out[10] c_out[9] c_out[8] c_out[7] c_out[6] c_out[5] c_out[4] c_out[3] 
+ c_out[2] c_out[1] c_out[0] overflow 
XCTS_L3_c_tid1_5 CLKBUF_X3 $PINS Z=CTS_n_tid1_3 A=CTS_n_tid1_4 
Xi_0_0_69 OR2_X1 $PINS ZN=n_0_0_37 A1=counter[2] A2=counter[1] 
Xi_0_0_68 NAND3_X1 $PINS ZN=n_0_0_36 A1=counter[4] A2=counter[3] A3=counter[0] 
Xi_0_0_67 OAI21_X1 $PINS ZN=n_0_99 A=n_0_97 B1=n_0_0_37 B2=n_0_0_36 
Xi_0_0_66 INV_X1 $PINS ZN=n_0_0_35 A=n_0_99 
Xi_0_0_65 NOR2_X1 $PINS ZN=n_0_0_33 A1=counter[4] A2=n_0_0_9 
Xi_0_0_64 AOI211_X1 $PINS ZN=n_0_96 A=n_0_0_33 B=n_0_99 C1=counter[4] 
+ C2=n_0_0_9 
Xi_0_0_63 INV_X1 $PINS ZN=n_0_0_11 A=n_0_42 
Xi_0_0_62 INV_X1 $PINS ZN=n_0_97 A=rst 
Xi_0_0_61 NOR4_X1 $PINS ZN=start A1=n_0_0_37 A2=counter[0] A3=counter[3] 
+ A4=counter[4] 
Xi_0_0_60 OAI21_X1 $PINS ZN=n_0_0_34 A=n_0_97 B1=n_0_0_11 B2=n_0_0_8 
Xi_0_0_59 AOI21_X1 $PINS ZN=n_0_98 A=n_0_0_34 B1=n_0_0_8 B2=n_0_0_11 
Xi_0_0_58 AND2_X1 $PINS ZN=n_0_95 A1=n_0_0_21 A2=n_0_0_35 
Xi_0_0_57 AND2_X1 $PINS ZN=n_0_94 A1=n_0_0_20 A2=n_0_0_35 
Xi_0_0_56 AND2_X1 $PINS ZN=n_0_93 A1=n_0_0_19 A2=n_0_0_35 
Xi_0_0_55 NOR2_X1 $PINS ZN=n_0_92 A1=rst A2=counter[0] 
Xi_0_0_54 AND2_X1 $PINS ZN=n_0_91 A1=start A2=n_0_97 
Xi_0_0_53 NOR4_X1 $PINS ZN=n_0_0_32 A1=n_0_55 A2=n_0_56 A3=n_0_57 A4=n_0_58 
Xi_0_0_52 NOR4_X1 $PINS ZN=n_0_0_31 A1=n_0_51 A2=n_0_52 A3=n_0_53 A4=n_0_54 
Xi_0_0_51 NAND2_X1 $PINS ZN=n_0_0_30 A1=n_0_0_32 A2=n_0_0_31 
Xi_0_0_50 NOR4_X1 $PINS ZN=n_0_0_29 A1=n_0_46 A2=n_0_47 A3=n_0_48 A4=n_0_49 
Xi_0_0_49 NOR4_X1 $PINS ZN=n_0_0_28 A1=n_0_42 A2=n_0_43 A3=n_0_44 A4=n_0_45 
Xi_0_0_48 NAND2_X1 $PINS ZN=n_0_0_27 A1=n_0_0_29 A2=n_0_0_28 
Xi_0_0_47 NAND2_X1 $PINS ZN=n_0_0_26 A1=n_0_0_30 A2=n_0_0_27 
Xi_0_0_46 NAND3_X1 $PINS ZN=n_0_0_25 A1=n_0_0_30 A2=n_0_0_27 A3=b 
Xi_0_0_45 XNOR2_X1 $PINS ZN=n_0_0_24 A=a B=n_0_0_25 
Xi_0_0_44 AND2_X1 $PINS ZN=n_0_90 A1=n_0_0_24 A2=n_0_97 
Xi_0_0_43 NOR2_X2 $PINS ZN=n_0_0_23 A1=n_0_0_26 A2=rst 
Xi_0_0_42 AND2_X1 $PINS ZN=n_0_89 A1=n_0_0_18 A2=n_0_0_23 
Xi_0_0_41 AND2_X1 $PINS ZN=n_0_88 A1=n_0_0_17 A2=n_0_0_23 
Xi_0_0_40 AND2_X1 $PINS ZN=n_0_87 A1=n_0_0_16 A2=n_0_0_23 
Xi_0_0_39 AND2_X1 $PINS ZN=n_0_86 A1=n_0_0_15 A2=n_0_0_23 
Xi_0_0_38 AND2_X1 $PINS ZN=n_0_85 A1=n_0_0_14 A2=n_0_0_23 
Xi_0_0_37 AND2_X1 $PINS ZN=n_0_84 A1=n_0_0_13 A2=n_0_0_23 
Xi_0_0_36 AND2_X1 $PINS ZN=n_0_83 A1=n_0_0_12 A2=n_0_0_23 
Xi_0_0_35 OR2_X1 $PINS ZN=n_0_0_10 A1=n_0_49 A2=n_0_58 
Xi_0_0_34 NAND2_X1 $PINS ZN=n_0_0_22 A1=n_0_49 A2=n_0_58 
Xi_0_0_33 AOI211_X1 $PINS ZN=n_0_82 A=rst B=n_0_0_26 C1=n_0_0_10 C2=n_0_0_22 
Xi_0_0_32 AND2_X1 $PINS ZN=CLOCK_slh__n166 A1=res_mant[23] A2=n_0_0_23 
Xi_0_0_31 AND2_X1 $PINS ZN=CLOCK_slh__n178 A1=res_mant[22] A2=n_0_0_23 
Xi_0_0_30 AND2_X1 $PINS ZN=CLOCK_slh__n158 A1=res_mant[21] A2=n_0_0_23 
Xi_0_0_29 AND2_X1 $PINS ZN=CLOCK_slh__n162 A1=res_mant[20] A2=n_0_0_23 
Xi_0_0_28 AND2_X1 $PINS ZN=CLOCK_slh__n174 A1=res_mant[19] A2=n_0_0_23 
Xi_0_0_27 AND2_X1 $PINS ZN=CLOCK_slh__n182 A1=res_mant[18] A2=n_0_0_23 
Xi_0_0_26 AND2_X1 $PINS ZN=CLOCK_slh__n198 A1=res_mant[17] A2=n_0_0_23 
Xi_0_0_25 AND2_X1 $PINS ZN=n_0_74 A1=res_mant[16] A2=n_0_0_23 
Xi_0_0_24 AND2_X1 $PINS ZN=n_0_73 A1=res_mant[15] A2=n_0_0_23 
Xi_0_0_23 AND2_X1 $PINS ZN=n_0_72 A1=res_mant[14] A2=n_0_0_23 
Xi_0_0_22 AND2_X1 $PINS ZN=n_0_71 A1=res_mant[13] A2=n_0_0_23 
Xi_0_0_21 AND2_X1 $PINS ZN=CLOCK_slh__n186 A1=res_mant[12] A2=n_0_0_23 
Xi_0_0_20 AND2_X1 $PINS ZN=CLOCK_slh__n190 A1=res_mant[11] A2=n_0_0_23 
Xi_0_0_19 AND2_X1 $PINS ZN=n_0_68 A1=res_mant[10] A2=n_0_0_23 
Xi_0_0_18 AND2_X1 $PINS ZN=n_0_67 A1=res_mant[9] A2=n_0_0_23 
Xi_0_0_17 AND2_X1 $PINS ZN=CLOCK_slh__n170 A1=res_mant[8] A2=n_0_0_23 
Xi_0_0_16 AND2_X1 $PINS ZN=CLOCK_slh__n194 A1=res_mant[7] A2=n_0_0_23 
Xi_0_0_15 AND2_X1 $PINS ZN=n_0_64 A1=res_mant[6] A2=n_0_0_23 
Xi_0_0_14 AND2_X1 $PINS ZN=n_0_63 A1=res_mant[5] A2=n_0_0_23 
Xi_0_0_13 AND2_X1 $PINS ZN=n_0_62 A1=res_mant[4] A2=n_0_0_23 
Xi_0_0_12 AND2_X1 $PINS ZN=n_0_61 A1=res_mant[3] A2=n_0_0_23 
Xi_0_0_11 AND2_X1 $PINS ZN=n_0_60 A1=res_mant[2] A2=n_0_0_23 
Xi_0_0_10 AND2_X1 $PINS ZN=n_0_59 A1=res_mant[1] A2=n_0_0_23 
Xi_0_0_9 HA_X1 $PINS CO=n_0_0_9 S=n_0_0_21 A=counter[3] B=n_0_0_1 
Xi_0_0_8 HA_X1 $PINS CO=n_0_0_1 S=n_0_0_20 A=counter[2] B=n_0_0_0 
Xi_0_0_7 HA_X1 $PINS CO=n_0_0_0 S=n_0_0_19 A=counter[1] B=counter[0] 
Xi_0_0_6 FA_X1 $PINS CO=n_0_0_8 S=n_0_0_18 A=n_0_51 B=n_0_0_11 CI=n_0_0_7 
Xi_0_0_5 FA_X1 $PINS CO=n_0_0_7 S=n_0_0_17 A=n_0_43 B=n_0_52 CI=n_0_0_6 
Xi_0_0_4 FA_X1 $PINS CO=n_0_0_6 S=n_0_0_16 A=n_0_44 B=n_0_53 CI=n_0_0_5 
Xi_0_0_3 FA_X1 $PINS CO=n_0_0_5 S=n_0_0_15 A=n_0_45 B=n_0_54 CI=n_0_0_4 
Xi_0_0_2 FA_X1 $PINS CO=n_0_0_4 S=n_0_0_14 A=n_0_46 B=n_0_55 CI=n_0_0_3 
Xi_0_0_1 FA_X1 $PINS CO=n_0_0_3 S=n_0_0_13 A=n_0_47 B=n_0_56 CI=n_0_0_2 
Xi_0_0_0 FA_X1 $PINS CO=n_0_0_2 S=n_0_0_12 A=n_0_48 B=n_0_57 CI=n_0_0_10 
Xclk_gate_b_reg__1 CLKGATETST_X8 $PINS GCK=CTS_n_tid1_4 CK=CTS_n_tid1_131 
+ E=n_0_91 SE=VSS 
Xclk_gate_overflow_reg CLKGATETST_X8 $PINS GCK=CTS_n_tid0_116 CK=n_tid1_157 
+ E=n_0_99 SE=VSS 
Xcounter_reg[0] DFF_X1 $PINS Q=counter[0] CK=n_tid1_157 D=n_0_92 
Xcounter_reg[1] DFF_X1 $PINS Q=counter[1] CK=n_tid1_157 D=n_0_93 
Xcounter_reg[2] DFF_X1 $PINS Q=counter[2] CK=n_tid1_157 D=n_0_94 
Xcounter_reg[3] DFF_X1 $PINS Q=counter[3] CK=n_tid1_157 D=n_0_95 
Xcounter_reg[4] DFF_X1 $PINS Q=counter[4] CK=CTS_n_tid1_131 D=n_0_96 
Xa_reg[23] DFF_X1 $PINS Q=n_0_58 CK=CTS_n_tid1_3 D=a_s[23] 
Xa_reg[24] DFF_X1 $PINS Q=n_0_57 CK=CTS_n_tid1_3 D=a_s[24] 
Xa_reg[25] DFF_X1 $PINS Q=n_0_56 CK=CTS_n_tid1_3 D=a_s[25] 
Xa_reg[26] DFF_X1 $PINS Q=n_0_55 CK=CTS_n_tid1_3 D=a_s[26] 
Xa_reg[27] DFF_X1 $PINS Q=n_0_54 CK=CTS_n_tid1_3 D=a_s[27] 
Xa_reg[28] DFF_X1 $PINS Q=n_0_53 CK=CTS_n_tid1_3 D=a_s[28] 
Xa_reg[29] DFF_X1 $PINS Q=n_0_52 CK=CTS_n_tid1_3 D=a_s[29] 
Xa_reg[30] DFF_X1 $PINS Q=n_0_51 CK=CTS_n_tid1_3 D=a_s[30] 
Xb_reg[23] DFF_X1 $PINS Q=n_0_49 CK=CTS_n_tid1_3 D=b_s[23] 
Xb_reg[24] DFF_X1 $PINS Q=n_0_48 CK=CTS_n_tid1_3 D=b_s[24] 
Xb_reg[25] DFF_X1 $PINS Q=n_0_47 CK=CTS_n_tid1_3 D=b_s[25] 
Xb_reg[26] DFF_X1 $PINS Q=n_0_46 CK=CTS_n_tid1_3 D=b_s[26] 
Xb_reg[27] DFF_X1 $PINS Q=n_0_45 CK=CTS_n_tid1_3 D=b_s[27] 
Xb_reg[28] DFF_X1 $PINS Q=n_0_44 CK=CTS_n_tid1_3 D=b_s[28] 
Xb_reg[29] DFF_X1 $PINS Q=n_0_43 CK=CTS_n_tid1_3 D=b_s[29] 
Xb_reg[30] DFF_X1 $PINS Q=n_0_42 CK=CTS_n_tid1_3 D=b_s[30] 
Xa_reg[31] DFF_X1 $PINS Q=a CK=CTS_n_tid1_3 D=a_s[31] 
Xb_reg[31] DFF_X1 $PINS Q=b CK=CTS_n_tid1_3 D=b_s[31] 
Xmul_start_reg_enable_mux_0 MUX2_X1 $PINS Z=n_0_41 A=mul_start B=start S=n_0_97 
Xmul_start_reg DFF_X1 $PINS Q=mul_start CK=n_tid1_157 D=n_0_41 
Xa_reg[0] DFF_X1 $PINS Q=n_0_39 CK=CTS_n_tid1_3 D=a_s[0] 
Xa_reg[1] DFF_X1 $PINS Q=n_0_38 CK=CTS_n_tid1_3 D=a_s[1] 
Xa_reg[2] DFF_X1 $PINS Q=n_0_37 CK=CTS_n_tid1_3 D=a_s[2] 
Xa_reg[3] DFF_X1 $PINS Q=n_0_36 CK=CTS_n_tid1_3 D=a_s[3] 
Xa_reg[4] DFF_X1 $PINS Q=n_0_35 CK=CTS_n_tid1_3 D=a_s[4] 
Xa_reg[5] DFF_X1 $PINS Q=n_0_34 CK=CTS_n_tid1_3 D=a_s[5] 
Xa_reg[6] DFF_X1 $PINS Q=n_0_33 CK=CTS_n_tid1_3 D=a_s[6] 
Xa_reg[7] DFF_X1 $PINS Q=n_0_32 CK=CTS_n_tid1_3 D=a_s[7] 
Xa_reg[8] DFF_X1 $PINS Q=n_0_31 CK=CTS_n_tid1_3 D=a_s[8] 
Xa_reg[9] DFF_X1 $PINS Q=n_0_30 CK=CTS_n_tid1_3 D=a_s[9] 
Xa_reg[10] DFF_X1 $PINS Q=n_0_29 CK=CTS_n_tid1_3 D=a_s[10] 
Xa_reg[11] DFF_X1 $PINS Q=n_0_28 CK=CTS_n_tid1_3 D=a_s[11] 
Xa_reg[12] DFF_X1 $PINS Q=n_0_27 CK=CTS_n_tid1_3 D=a_s[12] 
Xa_reg[13] DFF_X1 $PINS Q=n_0_26 CK=CTS_n_tid1_3 D=a_s[13] 
Xa_reg[14] DFF_X1 $PINS Q=n_0_25 CK=CTS_n_tid1_3 D=a_s[14] 
Xa_reg[15] DFF_X1 $PINS Q=n_0_24 CK=CTS_n_tid1_3 D=a_s[15] 
Xa_reg[16] DFF_X1 $PINS Q=n_0_23 CK=CTS_n_tid1_3 D=a_s[16] 
Xa_reg[17] DFF_X1 $PINS Q=n_0_22 CK=CTS_n_tid1_3 D=a_s[17] 
Xa_reg[18] DFF_X1 $PINS Q=n_0_21 CK=CTS_n_tid1_3 D=a_s[18] 
Xa_reg[19] DFF_X1 $PINS Q=n_0_20 CK=CTS_n_tid1_3 D=a_s[19] 
Xa_reg[20] DFF_X1 $PINS Q=n_0_19 CK=CTS_n_tid1_3 D=a_s[20] 
Xa_reg[21] DFF_X1 $PINS Q=n_0_18 CK=CTS_n_tid1_3 D=a_s[21] 
Xa_reg[22] DFF_X1 $PINS Q=n_0_17 CK=CTS_n_tid1_3 D=a_s[22] 
Xb_reg[0] DFF_X1 $PINS Q=n_0_16 CK=CTS_n_tid1_3 D=b_s[0] 
Xb_reg[1] DFF_X1 $PINS Q=n_0_15 CK=CTS_n_tid1_3 D=b_s[1] 
Xb_reg[2] DFF_X1 $PINS Q=n_0_14 CK=CTS_n_tid1_3 D=b_s[2] 
Xb_reg[3] DFF_X1 $PINS Q=n_0_13 CK=CTS_n_tid1_3 D=b_s[3] 
Xb_reg[4] DFF_X1 $PINS Q=n_0_12 CK=CTS_n_tid1_3 D=b_s[4] 
Xb_reg[5] DFF_X1 $PINS Q=n_0_11 CK=CTS_n_tid1_3 D=b_s[5] 
Xb_reg[6] DFF_X1 $PINS Q=n_0_10 CK=CTS_n_tid1_3 D=b_s[6] 
Xb_reg[7] DFF_X1 $PINS Q=n_0_9 CK=CTS_n_tid1_3 D=b_s[7] 
Xb_reg[8] DFF_X1 $PINS Q=n_0_8 CK=CTS_n_tid1_3 D=b_s[8] 
Xb_reg[9] DFF_X1 $PINS Q=n_0_7 CK=CTS_n_tid1_3 D=b_s[9] 
Xb_reg[10] DFF_X1 $PINS Q=n_0_6 CK=CTS_n_tid1_3 D=b_s[10] 
Xb_reg[11] DFF_X1 $PINS Q=n_0_5 CK=CTS_n_tid1_3 D=b_s[11] 
Xb_reg[12] DFF_X1 $PINS Q=n_0_4 CK=CTS_n_tid1_3 D=b_s[12] 
Xb_reg[13] DFF_X1 $PINS Q=n_0_3 CK=CTS_n_tid1_3 D=b_s[13] 
Xb_reg[14] DFF_X1 $PINS Q=n_0_2 CK=CTS_n_tid1_3 D=b_s[14] 
Xb_reg[15] DFF_X1 $PINS Q=n_0_1 CK=CTS_n_tid1_3 D=b_s[15] 
Xb_reg[16] DFF_X1 $PINS Q=n_0_0 CK=CTS_n_tid1_3 D=b_s[16] 
Xb_reg[17] DFF_X1 $PINS Q=n_0_105 CK=CTS_n_tid1_3 D=b_s[17] 
Xb_reg[18] DFF_X1 $PINS Q=n_0_104 CK=CTS_n_tid1_3 D=b_s[18] 
Xb_reg[19] DFF_X1 $PINS Q=n_0_103 CK=CTS_n_tid1_3 D=b_s[19] 
Xb_reg[20] DFF_X1 $PINS Q=n_0_102 CK=CTS_n_tid1_3 D=b_s[20] 
Xb_reg[21] DFF_X1 $PINS Q=n_0_101 CK=CTS_n_tid1_3 D=b_s[21] 
Xb_reg[22] DFF_X1 $PINS Q=n_0_100 CK=CTS_n_tid1_3 D=b_s[22] 
Xc_out_reg[0] DFF_X1 $PINS Q=c_out[0] CK=CTS_n_tid0_116 D=n_0_59 
Xc_out_reg[1] DFF_X1 $PINS Q=c_out[1] CK=CTS_n_tid0_116 D=n_0_60 
Xc_out_reg[2] DFF_X1 $PINS Q=c_out[2] CK=CTS_n_tid0_116 D=n_0_61 
Xc_out_reg[3] DFF_X1 $PINS Q=c_out[3] CK=CTS_n_tid0_116 D=n_0_62 
Xc_out_reg[4] DFF_X1 $PINS Q=c_out[4] CK=CTS_n_tid0_116 D=n_0_63 
Xc_out_reg[5] DFF_X1 $PINS Q=c_out[5] CK=CTS_n_tid0_116 D=n_0_64 
Xc_out_reg[6] DFF_X1 $PINS Q=c_out[6] CK=CTS_n_tid0_116 D=n_0_65 
Xc_out_reg[7] DFF_X1 $PINS Q=c_out[7] CK=CTS_n_tid0_116 D=n_0_66 
Xc_out_reg[8] DFF_X1 $PINS Q=c_out[8] CK=CTS_n_tid0_116 D=n_0_67 
Xc_out_reg[9] DFF_X1 $PINS Q=c_out[9] CK=CTS_n_tid0_116 D=n_0_68 
Xc_out_reg[10] DFF_X1 $PINS Q=c_out[10] CK=CTS_n_tid0_116 D=n_0_69 
Xc_out_reg[11] DFF_X1 $PINS Q=c_out[11] CK=CTS_n_tid0_116 D=n_0_70 
Xc_out_reg[12] DFF_X1 $PINS Q=c_out[12] CK=CTS_n_tid0_116 D=n_0_71 
Xc_out_reg[13] DFF_X1 $PINS Q=c_out[13] CK=CTS_n_tid0_116 D=n_0_72 
Xc_out_reg[14] DFF_X1 $PINS Q=c_out[14] CK=CTS_n_tid0_116 D=n_0_73 
Xc_out_reg[15] DFF_X1 $PINS Q=c_out[15] CK=CTS_n_tid0_116 D=n_0_74 
Xc_out_reg[16] DFF_X1 $PINS Q=c_out[16] CK=CTS_n_tid0_116 D=n_0_75 
Xc_out_reg[17] DFF_X1 $PINS Q=c_out[17] CK=CTS_n_tid0_116 D=n_0_76 
Xc_out_reg[18] DFF_X1 $PINS Q=c_out[18] CK=CTS_n_tid0_116 D=n_0_77 
Xc_out_reg[19] DFF_X1 $PINS Q=c_out[19] CK=CTS_n_tid0_116 D=n_0_78 
Xc_out_reg[20] DFF_X1 $PINS Q=c_out[20] CK=CTS_n_tid0_116 D=n_0_79 
Xc_out_reg[21] DFF_X1 $PINS Q=c_out[21] CK=CTS_n_tid0_116 D=n_0_80 
Xc_out_reg[22] DFF_X1 $PINS Q=c_out[22] CK=CTS_n_tid0_116 D=n_0_81 
Xc_out_reg[23] DFF_X1 $PINS Q=c_out[23] CK=CTS_n_tid0_116 D=n_0_82 
Xc_out_reg[24] DFF_X1 $PINS Q=c_out[24] CK=CTS_n_tid0_116 D=n_0_83 
Xc_out_reg[25] DFF_X1 $PINS Q=c_out[25] CK=CTS_n_tid0_116 D=n_0_84 
Xc_out_reg[26] DFF_X1 $PINS Q=c_out[26] CK=CTS_n_tid0_116 D=n_0_85 
Xc_out_reg[27] DFF_X1 $PINS Q=c_out[27] CK=CTS_n_tid0_116 D=n_0_86 
Xc_out_reg[28] DFF_X1 $PINS Q=c_out[28] CK=CTS_n_tid0_116 D=n_0_87 
Xc_out_reg[29] DFF_X1 $PINS Q=c_out[29] CK=CTS_n_tid0_116 D=n_0_88 
Xc_out_reg[30] DFF_X1 $PINS Q=c_out[30] CK=CTS_n_tid0_116 D=n_0_89 
Xc_out_reg[31] DFF_X1 $PINS Q=c_out[31] CK=CTS_n_tid0_116 D=n_0_90 
Xoverflow_reg DFF_X1 $PINS Q=overflow CK=CTS_n_tid0_116 D=n_0_98 
Xunsigned_seq_multiplier_dut unsigned_seq_multiplier $PINS c[47]=uc_2 
+ c[46]=uc_3 c[45]=res_mant[23] c[44]=res_mant[22] c[43]=res_mant[21] 
+ c[42]=res_mant[20] c[41]=res_mant[19] c[40]=res_mant[18] c[39]=res_mant[17] 
+ c[38]=res_mant[16] c[37]=res_mant[15] c[36]=res_mant[14] c[35]=res_mant[13] 
+ c[34]=res_mant[12] c[33]=res_mant[11] c[32]=res_mant[10] c[31]=res_mant[9] 
+ c[30]=res_mant[8] c[29]=res_mant[7] c[28]=res_mant[6] c[27]=res_mant[5] 
+ c[26]=res_mant[4] c[25]=res_mant[3] c[24]=res_mant[2] c[23]=res_mant[1] 
+ c[22]=uc_4 c[21]=uc_5 c[20]=uc_6 c[19]=uc_7 c[18]=uc_8 c[17]=uc_9 c[16]=uc_10 
+ c[15]=uc_11 c[14]=uc_12 c[13]=uc_13 c[12]=uc_14 c[11]=uc_15 c[10]=uc_16 
+ c[9]=uc_17 c[8]=uc_18 c[7]=uc_19 c[6]=uc_20 c[5]=uc_21 c[4]=uc_22 c[3]=uc_23 
+ c[2]=uc_24 c[1]=uc_25 c[0]=uc_26 a[23]=uc_0 a[22]=n_0_17 a[21]=n_0_18 
+ a[20]=n_0_19 a[19]=n_0_20 a[18]=n_0_21 a[17]=n_0_22 a[16]=n_0_23 a[15]=n_0_24 
+ a[14]=n_0_25 a[13]=n_0_26 a[12]=n_0_27 a[11]=n_0_28 a[10]=n_0_29 a[9]=n_0_30 
+ a[8]=n_0_31 a[7]=n_0_32 a[6]=n_0_33 a[5]=n_0_34 a[4]=n_0_35 a[3]=n_0_36 
+ a[2]=n_0_37 a[1]=n_0_38 a[0]=n_0_39 b[23]=uc_1 b[22]=n_0_100 b[21]=n_0_101 
+ b[20]=n_0_102 b[19]=n_0_103 b[18]=n_0_104 b[17]=n_0_105 b[16]=n_0_0 b[15]=n_0_1 
+ b[14]=n_0_2 b[13]=n_0_3 b[12]=n_0_4 b[11]=n_0_5 b[10]=n_0_6 b[9]=n_0_7 
+ b[8]=n_0_8 b[7]=n_0_9 b[6]=n_0_10 b[5]=n_0_11 b[4]=n_0_12 b[3]=n_0_13 
+ b[2]=n_0_14 b[1]=n_0_15 b[0]=n_0_16 rst=rst start_s=mul_start 
+ clk_CTS_1_PP_2=n_tid1_157 CTSclk_CTS_1_PP_2PP_0=CTS_n_tid1_131 
+ CTSclk_CTS_1_PP_2PP_1=CTS_n_tid1_131 
XCTS_L2_tid1__c3_tid1__c88 CLKBUF_X1 $PINS Z=n_tid1_157 A=CTS_n_tid1_131 
XCTS_L1_tid1__c1_tid1__c89 CLKBUF_X3 $PINS Z=CTS_n_tid1_131 A=clk 
XCLOCK_slh__c96 CLKBUF_X1 $PINS Z=CLOCK_slh__n159 A=CLOCK_slh__n158 
XCLOCK_slh__c97 CLKBUF_X1 $PINS Z=n_0_79 A=CLOCK_slh__n159 
XCLOCK_slh__c100 CLKBUF_X1 $PINS Z=CLOCK_slh__n163 A=CLOCK_slh__n162 
XCLOCK_slh__c101 CLKBUF_X1 $PINS Z=n_0_78 A=CLOCK_slh__n163 
XCLOCK_slh__c104 CLKBUF_X1 $PINS Z=CLOCK_slh__n167 A=CLOCK_slh__n166 
XCLOCK_slh__c105 CLKBUF_X1 $PINS Z=n_0_81 A=CLOCK_slh__n167 
XCLOCK_slh__c108 CLKBUF_X1 $PINS Z=CLOCK_slh__n171 A=CLOCK_slh__n170 
XCLOCK_slh__c109 CLKBUF_X1 $PINS Z=n_0_66 A=CLOCK_slh__n171 
XCLOCK_slh__c112 CLKBUF_X1 $PINS Z=CLOCK_slh__n175 A=CLOCK_slh__n174 
XCLOCK_slh__c113 CLKBUF_X1 $PINS Z=n_0_77 A=CLOCK_slh__n175 
XCLOCK_slh__c116 CLKBUF_X1 $PINS Z=CLOCK_slh__n179 A=CLOCK_slh__n178 
XCLOCK_slh__c117 CLKBUF_X1 $PINS Z=n_0_80 A=CLOCK_slh__n179 
XCLOCK_slh__c120 CLKBUF_X1 $PINS Z=CLOCK_slh__n183 A=CLOCK_slh__n182 
XCLOCK_slh__c121 CLKBUF_X1 $PINS Z=n_0_76 A=CLOCK_slh__n183 
XCLOCK_slh__c124 CLKBUF_X1 $PINS Z=CLOCK_slh__n187 A=CLOCK_slh__n186 
XCLOCK_slh__c125 CLKBUF_X1 $PINS Z=n_0_70 A=CLOCK_slh__n187 
XCLOCK_slh__c128 CLKBUF_X1 $PINS Z=CLOCK_slh__n191 A=CLOCK_slh__n190 
XCLOCK_slh__c129 CLKBUF_X1 $PINS Z=n_0_69 A=CLOCK_slh__n191 
XCLOCK_slh__c132 CLKBUF_X1 $PINS Z=CLOCK_slh__n195 A=CLOCK_slh__n194 
XCLOCK_slh__c133 CLKBUF_X1 $PINS Z=n_0_65 A=CLOCK_slh__n195 
XCLOCK_slh__c136 CLKBUF_X1 $PINS Z=CLOCK_slh__n199 A=CLOCK_slh__n198 
XCLOCK_slh__c137 CLKBUF_X1 $PINS Z=n_0_75 A=CLOCK_slh__n199 
.ENDS
.GLOBAL VSS 
