$ Spice netlist generated by v2lvs
$ v2020.1_25.14    Mon Feb 3 16:40:08 PST 2020
*.BUSDELIMITER [ 

.SUBCKT buffer__parameterized0 clk_CTS_1_PP_0 clk rst en D[0] Q[0] 
Xi_0_2 INV_X1 $PINS ZN=n_0_1 A=D[0] 
Xi_0_1 NOR2_X1 $PINS ZN=n_0_0 A1=Q[0] A2=en 
Xi_0_0 AOI211_X1 $PINS ZN=n_0 A=rst B=n_0_0 C1=n_0_1 C2=en 
XQ_reg[0] DFF_X1 $PINS Q=Q[0] CK=clk_CTS_1_PP_0 D=n_0 
.ENDS

.SUBCKT buffer__parameterized0__0_52 clk_CTS_1_PP_0 clk_CTS_1_PP_8 clk rst en 
+ D[0] Q[0] 
Xi_0_2 INV_X1 $PINS ZN=n_0_1 A=D[0] 
Xi_0_1 NOR2_X1 $PINS ZN=n_0_0 A1=Q[0] A2=en 
Xi_0_0 AOI211_X1 $PINS ZN=n_0 A=rst B=n_0_0 C1=n_0_1 C2=en 
XQ_reg[0] DFF_X1 $PINS Q=Q[0] CK=clk_CTS_1_PP_0 D=n_0 
XCTS_L1_c_tid1_2 CLKBUF_X3 $PINS Z=clk_CTS_1_PP_0 A=clk_CTS_1_PP_8 
.ENDS

.SUBCKT buffer clk_CTS_1_PP_3 clk rst en D[31] D[30] D[29] D[28] D[27] D[26] 
+ D[25] D[24] D[23] D[22] D[21] D[20] D[19] D[18] D[17] D[16] D[15] D[14] D[13] 
+ D[12] D[11] D[10] D[9] D[8] D[7] D[6] D[5] D[4] D[3] D[2] D[1] D[0] Q[31] 
+ Q[30] Q[29] Q[28] Q[27] Q[26] Q[25] Q[24] Q[23] Q[22] Q[21] Q[20] Q[19] Q[18] 
+ Q[17] Q[16] Q[15] Q[14] Q[13] Q[12] Q[11] Q[10] Q[9] Q[8] Q[7] Q[6] Q[5] Q[4] 
+ Q[3] Q[2] Q[1] Q[0] 
Xi_0_33 AND2_X1 $PINS ZN=n_33 A1=n_0_0 A2=D[31] 
Xi_0_32 AND2_X1 $PINS ZN=n_32 A1=n_0_0 A2=D[30] 
Xi_0_31 AND2_X1 $PINS ZN=n_31 A1=n_0_0 A2=D[29] 
Xi_0_30 AND2_X1 $PINS ZN=n_30 A1=n_0_0 A2=D[28] 
Xi_0_29 AND2_X1 $PINS ZN=n_29 A1=n_0_0 A2=D[27] 
Xi_0_28 AND2_X1 $PINS ZN=n_28 A1=n_0_0 A2=D[26] 
Xi_0_27 AND2_X1 $PINS ZN=n_27 A1=n_0_0 A2=D[25] 
Xi_0_26 AND2_X1 $PINS ZN=n_26 A1=n_0_0 A2=D[24] 
Xi_0_25 AND2_X1 $PINS ZN=n_25 A1=n_0_0 A2=D[23] 
Xi_0_24 AND2_X1 $PINS ZN=n_24 A1=n_0_0 A2=D[22] 
Xi_0_23 AND2_X1 $PINS ZN=n_23 A1=n_0_0 A2=D[21] 
Xi_0_22 AND2_X1 $PINS ZN=n_22 A1=n_0_0 A2=D[20] 
Xi_0_21 AND2_X1 $PINS ZN=n_21 A1=n_0_0 A2=D[19] 
Xi_0_20 AND2_X1 $PINS ZN=n_20 A1=n_0_0 A2=D[18] 
Xi_0_19 AND2_X1 $PINS ZN=n_19 A1=n_0_0 A2=D[17] 
Xi_0_18 AND2_X1 $PINS ZN=n_18 A1=n_0_0 A2=D[16] 
Xi_0_17 AND2_X1 $PINS ZN=n_17 A1=n_0_0 A2=D[15] 
Xi_0_16 AND2_X1 $PINS ZN=n_16 A1=n_0_0 A2=D[14] 
Xi_0_15 AND2_X1 $PINS ZN=n_15 A1=n_0_0 A2=D[13] 
Xi_0_14 AND2_X1 $PINS ZN=n_14 A1=n_0_0 A2=D[12] 
Xi_0_13 AND2_X1 $PINS ZN=n_13 A1=n_0_0 A2=D[11] 
Xi_0_12 AND2_X1 $PINS ZN=n_12 A1=n_0_0 A2=D[10] 
Xi_0_11 AND2_X1 $PINS ZN=n_11 A1=n_0_0 A2=D[9] 
Xi_0_10 AND2_X1 $PINS ZN=n_10 A1=n_0_0 A2=D[8] 
Xi_0_9 AND2_X1 $PINS ZN=n_9 A1=n_0_0 A2=D[7] 
Xi_0_8 AND2_X1 $PINS ZN=n_8 A1=n_0_0 A2=D[6] 
Xi_0_7 AND2_X1 $PINS ZN=n_7 A1=n_0_0 A2=D[5] 
Xi_0_6 AND2_X1 $PINS ZN=n_6 A1=n_0_0 A2=D[4] 
Xi_0_5 AND2_X1 $PINS ZN=n_5 A1=n_0_0 A2=D[3] 
Xi_0_4 AND2_X1 $PINS ZN=n_4 A1=n_0_0 A2=D[2] 
Xi_0_3 AND2_X1 $PINS ZN=n_3 A1=n_0_0 A2=D[1] 
Xi_0_2 AND2_X1 $PINS ZN=n_2 A1=n_0_0 A2=D[0] 
Xi_0_1 INV_X1 $PINS ZN=n_0_0 A=rst 
Xi_0_0 OR2_X1 $PINS ZN=n_1 A1=en A2=rst 
XQ_reg[0] DFF_X1 $PINS Q=Q[0] CK=n_0 D=n_2 
XQ_reg[1] DFF_X1 $PINS Q=Q[1] CK=n_0 D=n_3 
XQ_reg[2] DFF_X1 $PINS Q=Q[2] CK=n_0 D=n_4 
XQ_reg[3] DFF_X1 $PINS Q=Q[3] CK=n_0 D=n_5 
XQ_reg[4] DFF_X1 $PINS Q=Q[4] CK=n_0 D=n_6 
XQ_reg[5] DFF_X1 $PINS Q=Q[5] CK=n_0 D=n_7 
XQ_reg[6] DFF_X1 $PINS Q=Q[6] CK=n_0 D=n_8 
XQ_reg[7] DFF_X1 $PINS Q=Q[7] CK=n_0 D=n_9 
XQ_reg[8] DFF_X1 $PINS Q=Q[8] CK=n_0 D=n_10 
XQ_reg[9] DFF_X1 $PINS Q=Q[9] CK=n_0 D=n_11 
XQ_reg[10] DFF_X1 $PINS Q=Q[10] CK=n_0 D=n_12 
XQ_reg[11] DFF_X1 $PINS Q=Q[11] CK=n_0 D=n_13 
XQ_reg[12] DFF_X1 $PINS Q=Q[12] CK=n_0 D=n_14 
XQ_reg[13] DFF_X1 $PINS Q=Q[13] CK=n_0 D=n_15 
XQ_reg[14] DFF_X1 $PINS Q=Q[14] CK=n_0 D=n_16 
XQ_reg[15] DFF_X1 $PINS Q=Q[15] CK=n_0 D=n_17 
XQ_reg[16] DFF_X1 $PINS Q=Q[16] CK=n_0 D=n_18 
XQ_reg[17] DFF_X1 $PINS Q=Q[17] CK=n_0 D=n_19 
XQ_reg[18] DFF_X1 $PINS Q=Q[18] CK=n_0 D=n_20 
XQ_reg[19] DFF_X1 $PINS Q=Q[19] CK=n_0 D=n_21 
XQ_reg[20] DFF_X1 $PINS Q=Q[20] CK=n_0 D=n_22 
XQ_reg[21] DFF_X1 $PINS Q=Q[21] CK=n_0 D=n_23 
XQ_reg[22] DFF_X1 $PINS Q=Q[22] CK=n_0 D=n_24 
XQ_reg[23] DFF_X1 $PINS Q=Q[23] CK=n_0 D=n_25 
XQ_reg[24] DFF_X1 $PINS Q=Q[24] CK=n_0 D=n_26 
XQ_reg[25] DFF_X1 $PINS Q=Q[25] CK=n_0 D=n_27 
XQ_reg[26] DFF_X1 $PINS Q=Q[26] CK=n_0 D=n_28 
XQ_reg[27] DFF_X1 $PINS Q=Q[27] CK=n_0 D=n_29 
XQ_reg[28] DFF_X1 $PINS Q=Q[28] CK=n_0 D=n_30 
XQ_reg[29] DFF_X1 $PINS Q=Q[29] CK=n_0 D=n_31 
XQ_reg[30] DFF_X1 $PINS Q=Q[30] CK=n_0 D=n_32 
XQ_reg[31] DFF_X1 $PINS Q=Q[31] CK=n_0 D=n_33 
Xclk_gate_Q_reg CLKGATETST_X1 $PINS GCK=n_0 CK=n_tid1_46 E=n_1 SE=VSS 
XCTS_L1_tid1__c1_tid1__c7 CLKBUF_X1 $PINS Z=n_tid1_46 A=clk_CTS_1_PP_3 
.ENDS

.SUBCKT datapath__0_43 mant_A[23] mant_A[22] mant_A[21] mant_A[20] mant_A[19] 
+ mant_A[18] mant_A[17] mant_A[16] mant_A[15] mant_A[14] mant_A[13] mant_A[12] 
+ mant_A[11] mant_A[10] mant_A[9] mant_A[8] mant_A[7] mant_A[6] mant_A[5] 
+ mant_A[4] mant_A[3] mant_A[2] mant_A[1] mant_A[0] p_0[31] p_0[30] p_0[29] 
+ p_0[28] p_0[27] p_0[26] p_0[25] p_0[24] p_0[23] p_0[22] p_0[21] p_0[20] 
+ p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] p_0[14] p_0[13] p_0[12] p_0[11] 
+ p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] 
Xi_47 INV_X1 $PINS ZN=n_23 A=mant_A[15] 
Xi_46 INV_X1 $PINS ZN=n_22 A=mant_A[11] 
Xi_45 OR3_X1 $PINS ZN=n_21 A1=mant_A[2] A2=mant_A[1] A3=mant_A[0] 
Xi_44 OR2_X1 $PINS ZN=n_20 A1=n_21 A2=mant_A[3] 
Xi_43 OR2_X1 $PINS ZN=n_19 A1=n_20 A2=mant_A[4] 
Xi_42 OR3_X1 $PINS ZN=n_18 A1=n_19 A2=mant_A[5] A3=mant_A[6] 
Xi_41 OR2_X1 $PINS ZN=n_17 A1=n_18 A2=mant_A[7] 
Xi_40 OR3_X1 $PINS ZN=n_16 A1=n_17 A2=mant_A[8] A3=mant_A[9] 
Xi_39 NOR2_X1 $PINS ZN=n_15 A1=n_16 A2=mant_A[10] 
Xi_38 NAND2_X1 $PINS ZN=n_14 A1=n_15 A2=n_22 
Xi_37 OR2_X1 $PINS ZN=n_13 A1=n_14 A2=mant_A[12] 
Xi_36 NOR2_X1 $PINS ZN=n_12 A1=n_13 A2=mant_A[13] 
Xi_35 NOR3_X1 $PINS ZN=n_11 A1=n_13 A2=mant_A[13] A3=mant_A[14] 
Xi_34 NAND2_X1 $PINS ZN=n_10 A1=n_11 A2=n_23 
Xi_33 OR2_X1 $PINS ZN=n_9 A1=n_10 A2=mant_A[16] 
Xi_32 OR2_X1 $PINS ZN=n_8 A1=n_9 A2=mant_A[17] 
Xi_31 OR3_X1 $PINS ZN=n_7 A1=n_8 A2=mant_A[18] A3=mant_A[19] 
Xi_30 OR3_X1 $PINS ZN=n_6 A1=n_7 A2=mant_A[20] A3=mant_A[21] 
Xi_29 OR3_X1 $PINS ZN=p_0[31] A1=n_6 A2=mant_A[22] A3=mant_A[23] 
Xi_28 OAI21_X1 $PINS ZN=n_5 A=mant_A[23] B1=n_6 B2=mant_A[22] 
Xi_27 AND2_X1 $PINS ZN=p_0[23] A1=p_0[31] A2=n_5 
Xi_26 XOR2_X1 $PINS Z=p_0[22] A=mant_A[22] B=n_6 
Xi_25 OAI21_X1 $PINS ZN=n_4 A=mant_A[21] B1=n_7 B2=mant_A[20] 
Xi_24 AND2_X1 $PINS ZN=p_0[21] A1=n_6 A2=n_4 
Xi_23 XOR2_X1 $PINS Z=p_0[20] A=mant_A[20] B=n_7 
Xi_22 OAI21_X1 $PINS ZN=n_3 A=mant_A[19] B1=n_8 B2=mant_A[18] 
Xi_21 AND2_X1 $PINS ZN=p_0[19] A1=n_7 A2=n_3 
Xi_20 XOR2_X1 $PINS Z=p_0[18] A=mant_A[18] B=n_8 
Xi_19 XOR2_X1 $PINS Z=p_0[17] A=mant_A[17] B=n_9 
Xi_18 XOR2_X1 $PINS Z=p_0[16] A=mant_A[16] B=n_10 
Xi_17 XNOR2_X1 $PINS ZN=p_0[15] A=mant_A[15] B=n_11 
Xi_16 XNOR2_X1 $PINS ZN=p_0[14] A=mant_A[14] B=n_12 
Xi_15 XOR2_X1 $PINS Z=p_0[13] A=mant_A[13] B=n_13 
Xi_14 XOR2_X1 $PINS Z=p_0[12] A=mant_A[12] B=n_14 
Xi_13 XNOR2_X1 $PINS ZN=p_0[11] A=mant_A[11] B=n_15 
Xi_12 XOR2_X1 $PINS Z=p_0[10] A=mant_A[10] B=n_16 
Xi_11 OAI21_X1 $PINS ZN=n_2 A=mant_A[9] B1=n_17 B2=mant_A[8] 
Xi_10 AND2_X1 $PINS ZN=p_0[9] A1=n_16 A2=n_2 
Xi_9 XOR2_X1 $PINS Z=p_0[8] A=mant_A[8] B=n_17 
Xi_8 XOR2_X1 $PINS Z=p_0[7] A=mant_A[7] B=n_18 
Xi_7 OAI21_X1 $PINS ZN=n_1 A=mant_A[6] B1=n_19 B2=mant_A[5] 
Xi_6 AND2_X1 $PINS ZN=p_0[6] A1=n_18 A2=n_1 
Xi_5 XOR2_X1 $PINS Z=p_0[5] A=mant_A[5] B=n_19 
Xi_4 XOR2_X1 $PINS Z=p_0[4] A=mant_A[4] B=n_20 
Xi_3 XOR2_X1 $PINS Z=p_0[3] A=mant_A[3] B=n_21 
Xi_2 OAI21_X1 $PINS ZN=n_0 A=mant_A[2] B1=mant_A[1] B2=mant_A[0] 
Xi_1 AND2_X1 $PINS ZN=p_0[2] A1=n_21 A2=n_0 
Xi_0 XOR2_X1 $PINS Z=p_0[1] A=mant_A[1] B=mant_A[0] 
.ENDS

.SUBCKT datapath__0_38 p_0[21] p_0[20] p_0[19] p_0[18] p_0[17] p_0[16] p_0[15] 
+ p_0[14] p_0[13] p_0[12] p_0[11] p_0[10] p_0[9] p_0[8] p_0[7] p_0[6] p_0[5] 
+ p_0[4] p_0[3] p_0[2] p_0[1] p_0[0] p_1[10] p_1[9] p_1[8] p_1[7] p_1[6] p_1[5] 
+ p_1[4] p_1[3] p_1[2] p_1[1] p_1[0] 
Xi_4 HA_X1 $PINS CO=n_3 S=spc__n13 A=p_0[4] B=n_2 
Xi_3 HA_X1 $PINS CO=n_2 S=p_1[3] A=p_0[3] B=n_1 
Xi_2 HA_X1 $PINS CO=n_1 S=drc_ipo_n10 A=p_0[2] B=n_0 
Xi_1 HA_X1 $PINS CO=n_0 S=drc_ipo_n12 A=p_0[1] B=p_0[11] 
Xi_0 INV_X1 $PINS ZN=p_1[0] A=p_0[11] 
Xdrc_ipo_c5 CLKBUF_X1 $PINS Z=p_1[2] A=drc_ipo_n10 
Xdrc_ipo_c6 CLKBUF_X1 $PINS Z=p_1[1] A=drc_ipo_n12 
Xspc__c7 CLKBUF_X1 $PINS Z=p_1[4] A=spc__n13 
.ENDS

.SUBCKT datapath__0_25 p_0 exp_Sum[7] exp_Sum[6] exp_Sum[5] exp_Sum[4] 
+ exp_Sum[3] exp_Sum[2] exp_Sum[1] exp_Sum[0] p_1[21] p_1[20] p_1[19] p_1[18] 
+ p_1[17] p_1[16] p_1[15] p_1[14] p_1[13] p_1[12] p_1[11] p_1[10] p_1[9] p_1[8] 
+ p_1[7] p_1[6] p_1[5] p_1[4] p_1[3] p_1[2] p_1[1] p_1[0] 
Xi_14 INV_X1 $PINS ZN=n_17 A=exp_Sum[4] 
Xi_13 INV_X1 $PINS ZN=n_14 A=exp_Sum[3] 
Xi_12 INV_X1 $PINS ZN=n_13 A=exp_Sum[2] 
Xi_11 INV_X1 $PINS ZN=n_10 A=exp_Sum[1] 
Xi_10 INV_X1 $PINS ZN=n_9 A=exp_Sum[0] 
Xi_9 NOR3_X1 $PINS ZN=p_0 A1=exp_Sum[7] A2=exp_Sum[6] A3=n_3 
Xi_8 NAND2_X1 $PINS ZN=n_6 A1=n_9 A2=p_1[11] 
Xi_7 NAND2_X1 $PINS ZN=n_5 A1=n_10 A2=p_1[1] 
Xi_6 OAI21_X1 $PINS ZN=n_4 A=n_5 B1=n_10 B2=p_1[1] 
Xi_5 NAND2_X1 $PINS ZN=n_8 A1=n_13 A2=p_1[2] 
Xi_4 OAI21_X1 $PINS ZN=n_7 A=n_8 B1=n_13 B2=p_1[2] 
Xi_3 NAND2_X1 $PINS ZN=n_12 A1=n_14 A2=p_1[3] 
Xi_2 OAI21_X1 $PINS ZN=n_11 A=n_12 B1=n_14 B2=p_1[3] 
Xi_1 NAND2_X1 $PINS ZN=n_16 A1=n_17 A2=p_1[4] 
Xi_0 OAI21_X1 $PINS ZN=n_15 A=n_16 B1=n_17 B2=p_1[4] 
Xi_22 FA_X1 $PINS CO=n_3 A=exp_Sum[5] B=n_16 CI=n_2 
Xi_21 FA_X1 $PINS CO=n_2 A=n_12 B=n_15 CI=n_1 
Xi_20 FA_X1 $PINS CO=n_1 A=n_8 B=n_11 CI=n_0 
Xi_19 FA_X1 $PINS CO=n_0 A=n_5 B=n_7 CI=n_18 
Xi_18 HA_X1 $PINS CO=n_18 A=n_6 B=n_4 
.ENDS

.SUBCKT count_leading_zeros valueIn[22] valueIn[21] valueIn[20] valueIn[19] 
+ valueIn[18] valueIn[17] valueIn[16] valueIn[15] valueIn[14] valueIn[13] 
+ valueIn[12] valueIn[11] valueIn[10] valueIn[9] valueIn[8] valueIn[7] 
+ valueIn[6] valueIn[5] valueIn[4] valueIn[3] valueIn[2] valueIn[1] valueIn[0] 
+ result[4] result[3] result[2] result[1] result[0] 
Xi_0_45 NOR4_X1 $PINS ZN=n_0_29 A1=valueIn[14] A2=valueIn[13] A3=valueIn[12] 
+ A4=valueIn[11] 
Xi_0_44 OR2_X1 $PINS ZN=n_0_28 A1=valueIn[6] A2=valueIn[5] 
Xi_0_43 NOR2_X1 $PINS ZN=n_0_26 A1=valueIn[10] A2=valueIn[9] 
Xi_0_42 NOR2_X1 $PINS ZN=n_0_25 A1=valueIn[8] A2=valueIn[7] 
Xi_0_41 NOR4_X1 $PINS ZN=n_0_24 A1=valueIn[18] A2=valueIn[17] A3=valueIn[16] 
+ A4=valueIn[15] 
Xi_0_40 NOR4_X1 $PINS ZN=n_0_23 A1=valueIn[22] A2=valueIn[21] A3=valueIn[20] 
+ A4=valueIn[19] 
Xi_0_39 INV_X1 $PINS ZN=n_0_21 A=n_0_23 
Xi_0_38 NOR3_X1 $PINS ZN=n_0_20 A1=valueIn[3] A2=n_0_28 A3=valueIn[4] 
Xi_0_37 NAND2_X1 $PINS ZN=n_0_19 A1=n_0_26 A2=n_0_25 
Xi_0_36 OAI21_X1 $PINS ZN=n_0_18 A=n_0_29 B1=n_0_20 B2=n_0_19 
Xi_0_35 AOI21_X1 $PINS ZN=result[2] A=n_0_21 B1=n_0_24 B2=n_0_18 
Xi_0_34 INV_X1 $PINS ZN=n_0_40 A=valueIn[21] 
Xi_0_33 INV_X1 $PINS ZN=n_0_39 A=valueIn[20] 
Xi_0_32 INV_X1 $PINS ZN=n_0_38 A=valueIn[17] 
Xi_0_31 INV_X1 $PINS ZN=n_0_37 A=valueIn[16] 
Xi_0_30 INV_X1 $PINS ZN=n_0_36 A=valueIn[13] 
Xi_0_29 INV_X1 $PINS ZN=n_0_35 A=valueIn[12] 
Xi_0_28 INV_X1 $PINS ZN=n_0_34 A=valueIn[9] 
Xi_0_27 INV_X1 $PINS ZN=n_0_33 A=valueIn[8] 
Xi_0_26 INV_X1 $PINS ZN=n_0_32 A=valueIn[5] 
Xi_0_25 INV_X1 $PINS ZN=n_0_31 A=valueIn[4] 
Xi_0_24 INV_X1 $PINS ZN=n_0_30 A=valueIn[1] 
Xi_0_23 NAND2_X1 $PINS ZN=n_0_27 A1=n_0_23 A2=n_0_24 
Xi_0_22 NAND3_X1 $PINS ZN=n_0_22 A1=n_0_29 A2=n_0_26 A3=n_0_25 
Xi_0_21 NOR2_X1 $PINS ZN=result[4] A1=n_0_27 A2=n_0_22 
Xi_0_20 AND3_X1 $PINS ZN=result[3] A1=n_0_22 A2=n_0_24 A3=n_0_23 
Xi_0_19 NOR2_X1 $PINS ZN=n_0_17 A1=valueIn[2] A2=valueIn[1] 
Xi_0_18 NOR3_X1 $PINS ZN=n_0_16 A1=valueIn[4] A2=valueIn[3] A3=n_0_17 
Xi_0_17 OAI21_X1 $PINS ZN=n_0_15 A=n_0_25 B1=n_0_16 B2=n_0_28 
Xi_0_16 AOI211_X1 $PINS ZN=n_0_14 A=valueIn[12] B=valueIn[11] C1=n_0_15 
+ C2=n_0_26 
Xi_0_15 NOR3_X1 $PINS ZN=n_0_13 A1=valueIn[14] A2=valueIn[13] A3=n_0_14 
Xi_0_14 NOR3_X1 $PINS ZN=n_0_12 A1=valueIn[16] A2=valueIn[15] A3=n_0_13 
Xi_0_13 NOR3_X1 $PINS ZN=n_0_11 A1=valueIn[18] A2=valueIn[17] A3=n_0_12 
Xi_0_12 NOR3_X1 $PINS ZN=n_0_10 A1=valueIn[20] A2=valueIn[19] A3=n_0_11 
Xi_0_11 NOR3_X1 $PINS ZN=result[1] A1=valueIn[22] A2=valueIn[21] A3=n_0_10 
Xi_0_10 AOI21_X1 $PINS ZN=n_0_9 A=valueIn[2] B1=n_0_30 B2=valueIn[0] 
Xi_0_9 OAI21_X1 $PINS ZN=n_0_8 A=n_0_31 B1=valueIn[3] B2=n_0_9 
Xi_0_8 AOI21_X1 $PINS ZN=n_0_7 A=valueIn[6] B1=n_0_32 B2=n_0_8 
Xi_0_7 OAI21_X1 $PINS ZN=n_0_6 A=n_0_33 B1=valueIn[7] B2=n_0_7 
Xi_0_6 AOI21_X1 $PINS ZN=n_0_5 A=valueIn[10] B1=n_0_34 B2=n_0_6 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_4 A=n_0_35 B1=valueIn[11] B2=n_0_5 
Xi_0_4 AOI21_X1 $PINS ZN=n_0_3 A=valueIn[14] B1=n_0_36 B2=n_0_4 
Xi_0_3 OAI21_X1 $PINS ZN=n_0_2 A=n_0_37 B1=valueIn[15] B2=n_0_3 
Xi_0_2 AOI21_X1 $PINS ZN=n_0_1 A=valueIn[18] B1=n_0_38 B2=n_0_2 
Xi_0_1 OAI21_X1 $PINS ZN=n_0_0 A=n_0_39 B1=valueIn[19] B2=n_0_1 
Xi_0_0 AOI21_X1 $PINS ZN=result[0] A=valueIn[22] B1=n_0_40 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] sum[2] 
+ sum[1] sum[0] cout 
Xi_0_0 XOR2_X1 $PINS Z=sum[0] A=a[3] B=cin 
.ENDS

.SUBCKT CLA_4bit__0_114 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[0] B=a[0] 
Xi_0_13 AOI22_X1 $PINS ZN=n_0_8 A1=b[0] A2=a[0] B1=cin B2=n_0_9 
Xi_0_12 INV_X1 $PINS ZN=n_0_7 A=n_0_8 
Xi_0_11 XOR2_X1 $PINS Z=n_0_6 A=b[1] B=a[1] 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_5 A1=b[1] A2=a[1] B1=n_0_7 B2=n_0_6 
Xi_0_9 INV_X1 $PINS ZN=n_0_4 A=n_0_5 
Xi_0_8 XOR2_X1 $PINS Z=n_0_3 A=b[2] B=a[2] 
Xi_0_7 AOI22_X1 $PINS ZN=n_0_2 A1=b[2] A2=a[2] B1=n_0_4 B2=n_0_3 
Xi_0_6 NAND2_X1 $PINS ZN=n_0_1 A1=b[3] A2=a[3] 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_0 A=n_0_1 B1=b[3] B2=a[3] 
Xi_0_4 XOR2_X1 $PINS Z=sum[3] A=n_0_2 B=n_0_0 
Xi_0_3 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_3 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_8 B=n_0_6 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=cin B=n_0_9 
Xi_0_0 OAI21_X1 $PINS ZN=cout A=n_0_1 B1=n_0_2 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit__0_106 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[0] B=a[0] 
Xi_0_13 AOI22_X1 $PINS ZN=n_0_8 A1=b[0] A2=a[0] B1=cin B2=n_0_9 
Xi_0_12 INV_X1 $PINS ZN=n_0_7 A=n_0_8 
Xi_0_11 XOR2_X1 $PINS Z=n_0_6 A=b[1] B=a[1] 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_5 A1=b[1] A2=a[1] B1=n_0_7 B2=n_0_6 
Xi_0_9 INV_X1 $PINS ZN=n_0_4 A=n_0_5 
Xi_0_8 XOR2_X1 $PINS Z=n_0_3 A=b[2] B=a[2] 
Xi_0_7 AOI22_X1 $PINS ZN=n_0_2 A1=b[2] A2=a[2] B1=n_0_4 B2=n_0_3 
Xi_0_6 NAND2_X1 $PINS ZN=n_0_1 A1=b[3] A2=a[3] 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_0 A=n_0_1 B1=b[3] B2=a[3] 
Xi_0_4 XOR2_X1 $PINS Z=sum[3] A=n_0_2 B=n_0_0 
Xi_0_3 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_3 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_8 B=n_0_6 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=cin B=n_0_9 
Xi_0_0 OAI21_X1 $PINS ZN=cout A=n_0_1 B1=n_0_2 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit__0_98 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[0] B=a[0] 
Xi_0_13 AOI22_X1 $PINS ZN=n_0_8 A1=b[0] A2=a[0] B1=cin B2=n_0_9 
Xi_0_12 INV_X1 $PINS ZN=n_0_7 A=n_0_8 
Xi_0_11 XOR2_X1 $PINS Z=n_0_6 A=b[1] B=a[1] 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_5 A1=b[1] A2=a[1] B1=n_0_7 B2=n_0_6 
Xi_0_9 INV_X1 $PINS ZN=n_0_4 A=n_0_5 
Xi_0_8 XOR2_X1 $PINS Z=n_0_3 A=b[2] B=a[2] 
Xi_0_7 AOI22_X1 $PINS ZN=n_0_2 A1=b[2] A2=a[2] B1=n_0_4 B2=n_0_3 
Xi_0_6 NAND2_X1 $PINS ZN=n_0_1 A1=b[3] A2=a[3] 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_0 A=n_0_1 B1=b[3] B2=a[3] 
Xi_0_4 XOR2_X1 $PINS Z=sum[3] A=n_0_2 B=n_0_0 
Xi_0_3 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_3 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_8 B=n_0_6 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=cin B=n_0_9 
Xi_0_0 OAI21_X1 $PINS ZN=cout A=n_0_1 B1=n_0_2 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit__0_90 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[0] B=a[0] 
Xi_0_13 AOI22_X1 $PINS ZN=n_0_8 A1=b[0] A2=a[0] B1=cin B2=n_0_9 
Xi_0_12 INV_X1 $PINS ZN=n_0_7 A=n_0_8 
Xi_0_11 XOR2_X1 $PINS Z=n_0_6 A=b[1] B=a[1] 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_5 A1=b[1] A2=a[1] B1=n_0_7 B2=n_0_6 
Xi_0_9 INV_X1 $PINS ZN=n_0_4 A=n_0_5 
Xi_0_8 XOR2_X1 $PINS Z=n_0_3 A=b[2] B=a[2] 
Xi_0_7 AOI22_X1 $PINS ZN=n_0_2 A1=b[2] A2=a[2] B1=n_0_4 B2=n_0_3 
Xi_0_6 NAND2_X1 $PINS ZN=n_0_1 A1=b[3] A2=a[3] 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_0 A=n_0_1 B1=b[3] B2=a[3] 
Xi_0_4 XOR2_X1 $PINS Z=sum[3] A=n_0_2 B=n_0_0 
Xi_0_3 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_3 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_8 B=n_0_6 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=cin B=n_0_9 
Xi_0_0 OAI21_X1 $PINS ZN=cout A=n_0_1 B1=n_0_2 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit__0_82 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[0] B=a[0] 
Xi_0_13 AOI22_X1 $PINS ZN=n_0_8 A1=b[0] A2=a[0] B1=cin B2=n_0_9 
Xi_0_12 INV_X1 $PINS ZN=n_0_7 A=n_0_8 
Xi_0_11 XOR2_X1 $PINS Z=n_0_6 A=b[1] B=a[1] 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_5 A1=b[1] A2=a[1] B1=n_0_7 B2=n_0_6 
Xi_0_9 INV_X1 $PINS ZN=n_0_4 A=n_0_5 
Xi_0_8 XOR2_X1 $PINS Z=n_0_3 A=b[2] B=a[2] 
Xi_0_7 AOI22_X1 $PINS ZN=n_0_2 A1=b[2] A2=a[2] B1=n_0_4 B2=n_0_3 
Xi_0_6 NAND2_X1 $PINS ZN=n_0_1 A1=b[3] A2=a[3] 
Xi_0_5 OAI21_X1 $PINS ZN=n_0_0 A=n_0_1 B1=b[3] B2=a[3] 
Xi_0_4 XOR2_X1 $PINS Z=sum[3] A=n_0_2 B=n_0_0 
Xi_0_3 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_3 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_8 B=n_0_6 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=cin B=n_0_9 
Xi_0_0 OAI21_X1 $PINS ZN=cout A=n_0_1 B1=n_0_2 B2=n_0_0 
.ENDS

.SUBCKT CLA_4bit__0_66 a[3] a[2] a[1] a[0] b[3] b[2] b[1] b[0] cin sum[3] 
+ sum[2] sum[1] sum[0] cout 
Xi_0_16 NOR2_X1 $PINS ZN=n_0_11 A1=b[3] A2=a[3] 
Xi_0_15 NAND2_X1 $PINS ZN=n_0_10 A1=b[3] A2=a[3] 
Xi_0_14 XOR2_X1 $PINS Z=n_0_9 A=b[3] B=a[3] 
Xi_0_13 NOR2_X1 $PINS ZN=n_0_8 A1=b[1] A2=a[1] 
Xi_0_12 NAND2_X1 $PINS ZN=n_0_7 A1=b[1] A2=a[1] 
Xi_0_11 NAND2_X1 $PINS ZN=n_0_6 A1=b[0] A2=a[0] 
Xi_0_10 OAI21_X1 $PINS ZN=n_0_5 A=n_0_7 B1=n_0_8 B2=n_0_6 
Xi_0_9 AOI21_X1 $PINS ZN=n_0_4 A=n_0_5 B1=a[2] B2=b[2] 
Xi_0_8 INV_X1 $PINS ZN=n_0_3 A=n_0_4 
Xi_0_7 OAI21_X1 $PINS ZN=n_0_2 A=n_0_3 B1=a[2] B2=b[2] 
Xi_0_6 XNOR2_X2 $PINS ZN=sum[3] A=n_0_9 B=n_0_2 
Xi_0_5 XNOR2_X1 $PINS ZN=n_0_1 A=b[2] B=a[2] 
Xi_0_4 XNOR2_X1 $PINS ZN=sum[2] A=n_0_5 B=n_0_1 
Xi_0_3 XOR2_X1 $PINS Z=n_0_0 A=b[1] B=a[1] 
Xi_0_2 XNOR2_X1 $PINS ZN=sum[1] A=n_0_6 B=n_0_0 
Xi_0_1 XOR2_X1 $PINS Z=sum[0] A=b[0] B=a[0] 
Xi_0_0 AOI21_X1 $PINS ZN=cout A=n_0_11 B1=n_0_10 B2=n_0_2 
.ENDS

.SUBCKT CLA in1[31] in1[30] in1[29] in1[28] in1[27] in1[26] in1[25] in1[24] 
+ in1[23] in1[22] in1[21] in1[20] in1[19] in1[18] in1[17] in1[16] in1[15] 
+ in1[14] in1[13] in1[12] in1[11] in1[10] in1[9] in1[8] in1[7] in1[6] in1[5] 
+ in1[4] in1[3] in1[2] in1[1] in1[0] in2[31] in2[30] in2[29] in2[28] in2[27] 
+ in2[26] in2[25] in2[24] in2[23] in2[22] in2[21] in2[20] in2[19] in2[18] 
+ in2[17] in2[16] in2[15] in2[14] in2[13] in2[12] in2[11] in2[10] in2[9] in2[8] 
+ in2[7] in2[6] in2[5] in2[4] in2[3] in2[2] in2[1] in2[0] cin sum[31] sum[30] 
+ sum[29] sum[28] sum[27] sum[26] sum[25] sum[24] sum[23] sum[22] sum[21] 
+ sum[20] sum[19] sum[18] sum[17] sum[16] sum[15] sum[14] sum[13] sum[12] 
+ sum[11] sum[10] sum[9] sum[8] sum[7] sum[6] sum[5] sum[4] sum[3] sum[2] 
+ sum[1] sum[0] cout of 
Xgenblk1_24_cla CLA_4bit $PINS sum[3]=uc_3 sum[2]=uc_4 sum[1]=uc_5 
+ sum[0]=sum[24] a[3]=in1[31] a[2]=uc_0 a[1]=uc_1 a[0]=uc_2 cin=n_4 
Xgenblk1_20_cla CLA_4bit__0_114 $PINS cout=n_4 sum[3]=sum[23] sum[2]=sum[22] 
+ sum[1]=sum[21] sum[0]=sum[20] a[3]=in1[23] a[2]=in1[22] a[1]=in1[21] 
+ a[0]=in1[20] b[3]=in2[23] b[2]=in2[22] b[1]=in2[21] b[0]=in2[20] cin=n_3 
Xgenblk1_16_cla CLA_4bit__0_106 $PINS cout=n_3 sum[3]=sum[19] sum[2]=sum[18] 
+ sum[1]=sum[17] sum[0]=sum[16] a[3]=in1[19] a[2]=in1[18] a[1]=in1[17] 
+ a[0]=in1[16] b[3]=in2[19] b[2]=in2[18] b[1]=in2[17] b[0]=in2[16] cin=n_2 
Xgenblk1_12_cla CLA_4bit__0_98 $PINS cout=n_2 sum[3]=sum[15] sum[2]=sum[14] 
+ sum[1]=sum[13] sum[0]=sum[12] a[3]=in1[15] a[2]=in1[14] a[1]=in1[13] 
+ a[0]=in1[12] b[3]=in2[15] b[2]=in2[14] b[1]=in2[13] b[0]=in2[12] cin=n_1 
Xgenblk1_8_cla CLA_4bit__0_90 $PINS cout=n_1 sum[3]=sum[11] sum[2]=sum[10] 
+ sum[1]=sum[9] sum[0]=sum[8] a[3]=in1[11] a[2]=in1[10] a[1]=in1[9] a[0]=in1[8] 
+ b[3]=in2[11] b[2]=in2[10] b[1]=in2[9] b[0]=in2[8] cin=n_0 
Xgenblk1_4_cla CLA_4bit__0_82 $PINS cout=n_0 sum[3]=sum[7] sum[2]=sum[6] 
+ sum[1]=sum[5] sum[0]=sum[4] a[3]=in1[7] a[2]=in1[6] a[1]=in1[5] a[0]=in1[4] 
+ b[3]=in2[7] b[2]=in2[6] b[1]=in2[5] b[0]=in2[4] cin=c 
Xcla1 CLA_4bit__0_66 $PINS cout=c sum[3]=sum[3] sum[2]=sum[2] sum[1]=sum[1] 
+ sum[0]=sum[0] a[3]=in1[3] a[2]=in1[2] a[1]=in1[1] a[0]=in1[0] b[3]=in2[3] 
+ b[2]=in2[2] b[1]=in2[1] b[0]=in2[0] 
.ENDS

.SUBCKT fp_adder A[31] A[30] A[29] A[28] A[27] A[26] A[25] A[24] A[23] A[22] 
+ A[21] A[20] A[19] A[18] A[17] A[16] A[15] A[14] A[13] A[12] A[11] A[10] A[9] 
+ A[8] A[7] A[6] A[5] A[4] A[3] A[2] A[1] A[0] B[31] B[30] B[29] B[28] B[27] 
+ B[26] B[25] B[24] B[23] B[22] B[21] B[20] B[19] B[18] B[17] B[16] B[15] B[14] 
+ B[13] B[12] B[11] B[10] B[9] B[8] B[7] B[6] B[5] B[4] B[3] B[2] B[1] B[0] 
+ Sum[31] Sum[30] Sum[29] Sum[28] Sum[27] Sum[26] Sum[25] Sum[24] Sum[23] 
+ Sum[22] Sum[21] Sum[20] Sum[19] Sum[18] Sum[17] Sum[16] Sum[15] Sum[14] 
+ Sum[13] Sum[12] Sum[11] Sum[10] Sum[9] Sum[8] Sum[7] Sum[6] Sum[5] Sum[4] 
+ Sum[3] Sum[2] Sum[1] Sum[0] overflow underflow 
Xi_0_724 OAI21_X1 $PINS ZN=n_0_617 A=n_0_527 B1=n_0_518 B2=n_0_505 
Xi_0_723 INV_X1 $PINS ZN=n_102 A=n_0_617 
Xi_0_722 NAND2_X1 $PINS ZN=n_0_616 A1=n_0_537 A2=n_0_533 
Xi_0_721 NOR3_X1 $PINS ZN=n_0_615 A1=n_0_535 A2=A[28] A3=n_0_544 
Xi_0_720 AOI21_X1 $PINS ZN=n_0_614 A=n_0_530 B1=n_0_616 B2=n_0_615 
Xi_0_719 OAI21_X1 $PINS ZN=n_0_602 A=n_0_517 B1=n_0_520 B2=n_0_614 
Xi_0_718 AND2_X1 $PINS ZN=n_0_601 A1=n_0_617 A2=n_0_602 
Xi_0_717 AND2_X1 $PINS ZN=n_0_600 A1=n_0_539 A2=n_0_601 
Xi_0_715 NAND2_X1 $PINS ZN=n_0_599 A1=n_0_510 A2=n_0_540 
Xi_0_713 OAI21_X2 $PINS ZN=n_0_598 A=n_0_599 B1=n_0_540 B2=n_0_450 
Xi_0_710 INV_X1 $PINS ZN=n_0_597 A=n_0_598 
Xi_0_709 NOR2_X1 $PINS ZN=n_0_596 A1=n_0_514 A2=n_0_95 
Xi_0_708 NAND2_X1 $PINS ZN=n_0_595 A1=n_0_513 A2=n_0_596 
Xi_0_707 OAI21_X1 $PINS ZN=n_0_594 A=n_0_595 B1=n_0_513 B2=n_0_596 
Xi_0_706 INV_X1 $PINS ZN=n_0_593 A=n_0_594 
Xi_0_705 OAI21_X1 $PINS ZN=n_0_592 A=n_0_524 B1=n_0_526 B2=n_0_525 
Xi_0_704 XOR2_X1 $PINS Z=n_0_591 A=n_0_523 B=n_0_436 
Xi_0_703 INV_X1 $PINS ZN=n_0_590 A=n_0_591 
Xi_0_702 NOR2_X1 $PINS ZN=n_0_589 A1=n_0_592 A2=n_0_591 
Xi_0_701 INV_X1 $PINS ZN=n_0_577 A=n_0_589 
Xi_0_700 NOR2_X2 $PINS ZN=n_0_576 A1=n_0_593 A2=n_0_577 
Xi_0_699 NAND2_X1 $PINS ZN=n_0_575 A1=n_0_593 A2=n_0_589 
Xi_0_698 NAND2_X1 $PINS ZN=n_0_574 A1=n_0_592 A2=n_0_590 
Xi_0_697 INV_X1 $PINS ZN=n_0_573 A=n_0_574 
Xi_0_696 NOR2_X1 $PINS ZN=n_0_572 A1=n_0_594 A2=n_0_574 
Xi_0_695 NOR2_X1 $PINS ZN=n_0_571 A1=n_0_593 A2=n_0_574 
Xi_0_694 NAND2_X1 $PINS ZN=n_0_570 A1=B[12] A2=n_0_576 
Xi_0_693 OAI21_X1 $PINS ZN=n_0_569 A=n_0_570 B1=n_0_314 B2=n_0_575 
Xi_0_686 AOI221_X1 $PINS ZN=n_0_568 A=n_0_569 B1=B[16] B2=n_0_572 C1=B[20] 
+ C2=n_0_571 
Xi_0_684 AOI22_X1 $PINS ZN=n_0_567 A1=B[10] A2=n_0_589 B1=B[18] B2=n_0_573 
Xi_0_683 NOR2_X1 $PINS ZN=n_0_566 A1=n_0_592 A2=n_0_590 
Xi_0_682 AOI222_X1 $PINS ZN=n_0_565 A1=B[22] A2=n_0_566 B1=B[6] B2=n_0_589 
+ C1=B[14] C2=n_0_573 
Xi_0_681 OAI22_X1 $PINS ZN=n_0_562 A1=n_0_594 A2=n_0_565 B1=n_0_593 B2=n_0_567 
Xi_0_680 INV_X1 $PINS ZN=n_0_561 A=n_0_562 
Xi_0_679 OAI22_X1 $PINS ZN=n_0_560 A1=n_0_598 A2=n_0_561 B1=n_0_597 B2=n_0_568 
Xi_0_678 NAND2_X1 $PINS ZN=n_0_559 A1=n_0_540 A2=n_0_601 
Xi_0_677 INV_X1 $PINS ZN=n_0_558 A=n_0_559 
Xi_0_676 AOI22_X1 $PINS ZN=n_0_557 A1=B[21] A2=n_0_566 B1=B[13] B2=n_0_573 
Xi_0_675 OAI21_X1 $PINS ZN=n_0_556 A=n_0_557 B1=n_0_308 B2=n_0_577 
Xi_0_674 AOI222_X1 $PINS ZN=n_0_555 A1=B[9] A2=n_0_576 B1=B[17] B2=n_0_571 
+ C1=n_0_593 C2=n_0_556 
Xi_0_673 NAND2_X1 $PINS ZN=n_0_554 A1=B[15] A2=n_0_590 
Xi_0_672 AOI22_X1 $PINS ZN=n_0_553 A1=n_0_592 A2=n_0_554 B1=n_0_312 B2=n_0_589 
Xi_0_671 AOI222_X1 $PINS ZN=n_0_552 A1=n_0_593 A2=n_0_553 B1=B[11] B2=n_0_576 
+ C1=B[19] C2=n_0_571 
Xi_0_670 OAI22_X1 $PINS ZN=n_0_551 A1=n_0_597 A2=n_0_552 B1=n_0_598 B2=n_0_555 
Xi_0_669 AOI222_X1 $PINS ZN=n_0_550 A1=n_0_600 A2=n_0_560 B1=B[5] B2=n_102 
+ C1=n_0_558 C2=n_0_551 
Xi_0_668 INV_X1 $PINS ZN=n_101 A=n_0_550 
Xi_0_667 INV_X1 $PINS ZN=n_0_549 A=A[28] 
Xi_0_666 INV_X1 $PINS ZN=n_0_548 A=A[25] 
Xi_0_665 INV_X1 $PINS ZN=n_0_547 A=A[23] 
Xi_0_664 INV_X1 $PINS ZN=n_0_546 A=B[30] 
Xi_0_663 INV_X1 $PINS ZN=n_0_545 A=B[29] 
Xi_0_662 INV_X1 $PINS ZN=n_0_544 A=B[28] 
Xi_0_661 INV_X1 $PINS ZN=n_0_543 A=B[27] 
Xi_0_660 INV_X1 $PINS ZN=n_0_542 A=B[26] 
Xi_0_659 NOR2_X1 $PINS ZN=n_0_541 A1=n_0_547 A2=B[23] 
Xi_0_658 AOI21_X1 $PINS ZN=n_0_540 A=n_0_541 B1=n_0_547 B2=B[23] 
Xi_0_657 INV_X1 $PINS ZN=n_0_539 A=n_0_540 
Xi_0_656 NOR2_X1 $PINS ZN=n_0_538 A1=A[30] A2=B[30] 
Xi_0_655 AOI21_X1 $PINS ZN=n_0_537 A=n_0_538 B1=A[30] B2=B[30] 
Xi_0_654 INV_X1 $PINS ZN=n_0_536 A=n_0_537 
Xi_0_653 AOI21_X1 $PINS ZN=n_0_535 A=n_0_537 B1=A[29] B2=n_0_545 
Xi_0_652 NOR2_X1 $PINS ZN=n_0_534 A1=A[29] A2=n_0_545 
Xi_0_651 INV_X1 $PINS ZN=n_0_533 A=n_0_534 
Xi_0_650 NAND2_X1 $PINS ZN=n_0_531 A1=n_0_535 A2=n_0_533 
Xi_0_649 NOR3_X1 $PINS ZN=n_0_530 A1=n_0_549 A2=B[28] A3=n_0_531 
Xi_0_648 NOR2_X1 $PINS ZN=n_0_529 A1=A[30] A2=n_0_546 
Xi_0_647 NOR2_X1 $PINS ZN=n_0_528 A1=n_0_535 A2=n_0_529 
Xi_0_646 NOR2_X1 $PINS ZN=n_0_527 A1=n_0_530 A2=n_0_528 
Xi_0_645 XOR2_X1 $PINS Z=n_0_526 A=A[26] B=n_0_542 
Xi_0_644 OAI21_X1 $PINS ZN=n_0_525 A=n_0_595 B1=A[25] B2=n_0_99 
Xi_0_643 NAND2_X1 $PINS ZN=n_0_524 A1=n_0_526 A2=n_0_525 
Xi_0_642 OAI21_X1 $PINS ZN=n_0_523 A=n_0_524 B1=A[26] B2=n_0_542 
Xi_0_641 NAND2_X1 $PINS ZN=n_0_522 A1=A[27] A2=n_0_543 
Xi_0_640 NOR2_X1 $PINS ZN=n_0_521 A1=A[27] A2=n_0_543 
Xi_0_639 OAI21_X1 $PINS ZN=n_0_520 A=n_0_522 B1=n_0_523 B2=n_0_521 
Xi_0_638 AOI211_X1 $PINS ZN=n_0_519 A=n_0_529 B=n_0_534 C1=n_0_549 C2=B[28] 
Xi_0_637 INV_X1 $PINS ZN=n_0_518 A=n_0_519 
Xi_0_636 NAND3_X1 $PINS ZN=n_0_517 A1=n_0_527 A2=n_0_520 A3=n_0_519 
Xi_0_635 NAND2_X2 $PINS ZN=n_100 A1=n_0_527 A2=n_0_517 
Xi_0_633 NOR2_X1 $PINS ZN=n_0_514 A1=B[24] A2=n_0_96 
Xi_0_632 OAI22_X1 $PINS ZN=n_0_513 A1=A[25] A2=B[25] B1=n_0_548 B2=n_0_99 
Xi_0_631 INV_X1 $PINS ZN=n_0_512 A=n_0_513 
Xi_0_630 AOI21_X1 $PINS ZN=n_0_511 A=n_0_514 B1=B[24] B2=n_0_96 
Xi_0_629 INV_X1 $PINS ZN=n_0_510 A=n_0_511 
Xi_0_628 AOI21_X1 $PINS ZN=n_0_509 A=n_0_514 B1=n_0_541 B2=n_0_511 
Xi_0_627 OAI22_X1 $PINS ZN=n_0_508 A1=n_0_548 A2=B[25] B1=n_0_512 B2=n_0_509 
Xi_0_626 AOI22_X1 $PINS ZN=n_0_507 A1=A[26] A2=n_0_542 B1=n_0_526 B2=n_0_508 
Xi_0_625 AOI21_X1 $PINS ZN=n_0_506 A=n_0_521 B1=n_0_522 B2=n_0_507 
Xi_0_624 INV_X1 $PINS ZN=n_0_505 A=n_0_506 
Xi_0_623 AOI22_X1 $PINS ZN=n_0_503 A1=A[29] A2=n_0_545 B1=n_0_536 B2=n_0_534 
Xi_0_622 OAI33_X1 $PINS ZN=n_0_495 A1=n_0_549 A2=B[28] A3=n_0_503 B1=A[28] 
+ B2=n_0_544 B3=n_0_531 
Xi_0_621 OAI221_X1 $PINS ZN=n_0_493 A=n_0_396 B1=n_0_519 B2=n_0_506 C1=n_0_505 
+ C2=n_0_495 
Xi_0_620 INV_X1 $PINS ZN=n_0_492 A=n_0_493 
Xi_0_619 NOR2_X2 $PINS ZN=n_0_484 A1=n_0_539 A2=n_0_493 
Xi_0_618 INV_X1 $PINS ZN=n_0_471 A=n_0_484 
Xi_0_617 XOR2_X1 $PINS Z=n_0_470 A=n_0_541 B=n_0_511 
Xi_0_616 INV_X1 $PINS ZN=n_0_450 A=drc_ipo_n4 
Xi_0_615 XOR2_X1 $PINS Z=n_0_442 A=n_0_512 B=n_0_509 
Xi_0_614 INV_X1 $PINS ZN=n_0_441 A=n_0_442 
Xi_0_613 XOR2_X1 $PINS Z=n_0_440 A=n_0_526 B=n_0_508 
Xi_0_612 INV_X1 $PINS ZN=n_0_439 A=n_0_440 
Xi_0_611 OAI21_X1 $PINS ZN=n_0_436 A=n_0_522 B1=A[27] B2=n_0_543 
Xi_0_610 XOR2_X1 $PINS Z=n_0_435 A=n_0_507 B=n_0_436 
Xi_0_609 NAND2_X1 $PINS ZN=n_0_434 A1=n_0_439 A2=n_0_435 
Xi_0_608 INV_X1 $PINS ZN=n_0_433 A=n_0_434 
Xi_0_607 NAND2_X1 $PINS ZN=n_0_430 A1=n_0_440 A2=n_0_435 
Xi_0_606 INV_X1 $PINS ZN=n_0_429 A=n_0_430 
Xi_0_605 AOI22_X1 $PINS ZN=n_0_428 A1=A[11] A2=n_0_429 B1=A[19] B2=n_0_433 
Xi_0_604 INV_X1 $PINS ZN=n_0_427 A=n_0_428 
Xi_0_602 NAND2_X1 $PINS ZN=n_0_425 A1=A[15] A2=n_0_435 
Xi_0_601 AOI22_X1 $PINS ZN=n_0_424 A1=n_0_439 A2=n_0_425 B1=n_0_310 B2=n_0_429 
Xi_0_600 OAI22_X1 $PINS ZN=n_0_423 A1=n_0_441 A2=n_0_424 B1=n_0_442 B2=n_0_427 
Xi_0_599 NOR2_X2 $PINS ZN=n_0_422 A1=n_0_441 A2=n_0_430 
Xi_0_598 INV_X1 $PINS ZN=n_0_421 A=n_0_422 
Xi_0_597 OAI22_X1 $PINS ZN=n_0_395 A1=A[21] A2=n_0_442 B1=A[17] B2=n_0_441 
Xi_0_596 NOR2_X1 $PINS ZN=n_0_394 A1=n_0_442 A2=n_0_430 
Xi_0_595 NOR2_X1 $PINS ZN=n_0_393 A1=n_0_434 A2=n_0_395 
Xi_0_594 AOI221_X1 $PINS ZN=n_0_392 A=n_0_393 B1=A[9] B2=n_0_422 C1=A[13] 
+ C2=n_0_394 
Xi_0_593 OAI22_X1 $PINS ZN=n_0_391 A1=drc_ipo_n4 A2=n_0_392 B1=n_0_450 
+ B2=n_0_423 
Xi_0_592 NOR2_X2 $PINS ZN=n_0_390 A1=n_0_540 A2=n_0_493 
Xi_0_591 NOR2_X1 $PINS ZN=n_0_389 A1=n_0_442 A2=n_0_434 
Xi_0_590 NOR2_X1 $PINS ZN=n_0_388 A1=n_0_441 A2=n_0_434 
Xi_0_589 AOI22_X1 $PINS ZN=n_0_387 A1=A[18] A2=n_0_388 B1=A[14] B2=n_0_394 
Xi_0_588 INV_X1 $PINS ZN=n_0_386 A=n_0_387 
Xi_0_587 AOI221_X1 $PINS ZN=n_0_385 A=n_0_386 B1=A[22] B2=n_0_389 C1=A[10] 
+ C2=n_0_422 
Xi_0_586 INV_X1 $PINS ZN=n_0_384 A=n_0_385 
Xi_0_585 NAND2_X1 $PINS ZN=n_0_383 A1=A[12] A2=n_0_394 
Xi_0_584 OAI21_X1 $PINS ZN=n_0_375 A=n_0_383 B1=n_0_313 B2=n_0_421 
Xi_0_583 AOI221_X1 $PINS ZN=n_0_374 A=n_0_375 B1=A[16] B2=n_0_388 C1=A[20] 
+ C2=n_0_389 
Xi_0_582 AOI22_X1 $PINS ZN=n_0_369 A1=drc_ipo_n4 A2=n_0_374 B1=n_0_450 
+ B2=n_0_385 
Xi_0_581 AOI222_X1 $PINS ZN=n_0_366 A1=n_0_484 A2=n_0_391 B1=A[7] B2=n_100 
+ C1=n_0_390 C2=n_0_369 
Xi_0_580 INV_X1 $PINS ZN=n_99 A=n_0_366 
Xi_0_579 AOI221_X1 $PINS ZN=n_0_362 A=n_0_354 B1=B[8] B2=n_0_313 C1=B[9] 
+ C2=n_0_361 
Xi_0_578 INV_X1 $PINS ZN=n_0_361 A=A[9] 
Xi_0_577 AOI22_X1 $PINS ZN=n_0_354 A1=n_0_352 A2=n_0_353 B1=n_0_314 B2=A[8] 
Xi_0_576 NAND2_X1 $PINS ZN=n_0_353 A1=n_0_310 A2=B[7] 
Xi_0_575 OAI221_X1 $PINS ZN=n_0_352 A=n_0_345 B1=n_0_309 B2=B[6] C1=B[7] 
+ C2=n_0_310 
Xi_0_574 OAI221_X1 $PINS ZN=n_0_345 A=n_0_327 B1=A[6] B2=n_0_333 C1=n_0_308 
+ C2=A[5] 
Xi_0_573 INV_X1 $PINS ZN=n_0_333 A=B[6] 
Xi_0_572 OAI221_X1 $PINS ZN=n_0_327 A=n_0_326 B1=n_0_306 B2=B[4] C1=B[5] 
+ C2=n_0_307 
Xi_0_571 OAI221_X1 $PINS ZN=n_0_326 A=n_0_325 B1=A[4] B2=n_0_201 C1=n_0_202 
+ C2=A[3] 
Xi_0_570 OAI221_X1 $PINS ZN=n_0_325 A=n_0_319 B1=B[3] B2=n_0_323 C1=n_0_324 
+ C2=B[2] 
Xi_0_569 INV_X1 $PINS ZN=n_0_324 A=A[2] 
Xi_0_568 INV_X1 $PINS ZN=n_0_323 A=A[3] 
Xi_0_567 OAI221_X1 $PINS ZN=n_0_319 A=n_0_316 B1=n_0_199 B2=A[2] C1=n_0_200 
+ C2=A[1] 
Xi_0_566 OAI22_X1 $PINS ZN=n_0_316 A1=n_0_315 A2=B[0] B1=n_0_198 B2=B[1] 
Xi_0_565 INV_X1 $PINS ZN=n_0_315 A=A[0] 
Xi_0_564 INV_X1 $PINS ZN=n_0_314 A=B[8] 
Xi_0_563 INV_X1 $PINS ZN=n_0_313 A=A[8] 
Xi_0_562 INV_X1 $PINS ZN=n_0_312 A=B[7] 
Xi_0_561 INV_X1 $PINS ZN=n_0_310 A=A[7] 
Xi_0_560 INV_X1 $PINS ZN=n_0_309 A=A[6] 
Xi_0_559 INV_X1 $PINS ZN=n_0_308 A=B[5] 
Xi_0_558 INV_X1 $PINS ZN=n_0_307 A=A[5] 
Xi_0_557 INV_X1 $PINS ZN=n_0_306 A=A[4] 
Xi_0_556 INV_X1 $PINS ZN=n_0_202 A=B[3] 
Xi_0_555 INV_X1 $PINS ZN=n_0_201 A=B[4] 
Xi_0_554 INV_X1 $PINS ZN=n_0_200 A=B[1] 
Xi_0_553 INV_X1 $PINS ZN=n_0_199 A=B[2] 
Xi_0_552 INV_X1 $PINS ZN=n_0_198 A=A[1] 
Xi_0_551 AOI222_X1 $PINS ZN=n_0_197 A1=n_18 A2=n_0_114 B1=n_2 B2=n_0_122 
+ C1=n_10 C2=n_0_120 
Xi_0_550 AOI22_X1 $PINS ZN=n_0_196 A1=n_14 A2=n_0_114 B1=n_6 B2=n_0_120 
Xi_0_549 OAI22_X1 $PINS ZN=n_0_195 A1=n_28 A2=n_0_197 B1=n_0_126 B2=n_0_196 
Xi_0_548 AOI222_X1 $PINS ZN=n_0_194 A1=n_16 A2=n_0_114 B1=n_0 B2=n_0_122 C1=n_8 
+ C2=n_0_120 
Xi_0_547 AOI222_X1 $PINS ZN=n_0_193 A1=n_20 A2=n_0_113 B1=n_12 B2=n_0_119 
+ C1=n_4 C2=n_0_121 
Xi_0_546 OAI21_X1 $PINS ZN=n_0_192 A=n_0_193 B1=n_0_126 B2=n_0_194 
Xi_0_545 INV_X1 $PINS ZN=n_0_132 A=n_0_192 
Xi_0_544 NAND2_X1 $PINS ZN=n_0_131 A1=n_27 A2=n_0_195 
Xi_0_543 OAI21_X1 $PINS ZN=n_0_130 A=n_0_131 B1=n_27 B2=n_0_132 
Xi_0_542 INV_X1 $PINS ZN=n_0_129 A=n_30 
Xi_0_541 INV_X1 $PINS ZN=n_0_128 A=n_29 
Xi_0_540 INV_X1 $PINS ZN=n_0_126 A=n_28 
Xi_0_539 INV_X1 $PINS ZN=n_0_125 A=n_27 
Xi_0_538 NOR2_X1 $PINS ZN=n_0_122 A1=n_0_129 A2=n_29 
Xi_0_537 NOR3_X1 $PINS ZN=n_0_121 A1=n_0_129 A2=n_29 A3=n_28 
Xi_0_536 NOR2_X1 $PINS ZN=n_0_120 A1=n_30 A2=n_0_128 
Xi_0_535 NOR3_X2 $PINS ZN=n_0_119 A1=n_30 A2=n_0_128 A3=n_28 
Xi_0_534 NOR2_X1 $PINS ZN=n_0_114 A1=n_30 A2=n_29 
Xi_0_533 NOR3_X4 $PINS ZN=n_0_113 A1=n_30 A2=n_29 A3=n_28 
Xi_0_532 AOI22_X1 $PINS ZN=n_0_112 A1=n_15 A2=n_0_114 B1=n_7 B2=n_0_120 
Xi_0_531 AOI222_X1 $PINS ZN=n_0_111 A1=n_19 A2=n_0_113 B1=n_11 B2=n_0_119 
+ C1=n_3 C2=n_0_121 
Xi_0_530 OAI21_X1 $PINS ZN=n_0_110 A=n_0_111 B1=n_0_126 B2=n_0_112 
Xi_0_529 AOI22_X1 $PINS ZN=n_0_109 A1=n_13 A2=n_0_114 B1=n_5 B2=n_0_120 
Xi_0_528 AOI222_X1 $PINS ZN=n_0_102 A1=n_9 A2=n_0_120 B1=n_1 B2=n_0_122 C1=n_17 
+ C2=n_0_114 
Xi_0_527 AOI22_X1 $PINS ZN=n_0_101 A1=n_0_126 A2=n_0_102 B1=n_28 B2=n_0_109 
Xi_0_526 OAI22_X1 $PINS ZN=n_0_100 A1=n_27 A2=n_0_110 B1=n_0_125 B2=n_0_101 
Xi_0_525 INV_X1 $PINS ZN=n_0_94 A=B[31] 
Xi_0_524 INV_X1 $PINS ZN=n_0_99 A=B[25] 
Xi_0_523 INV_X1 $PINS ZN=n_0_613 A=B[22] 
Xi_0_522 INV_X1 $PINS ZN=n_0_612 A=B[20] 
Xi_0_521 INV_X1 $PINS ZN=n_0_611 A=B[19] 
Xi_0_520 INV_X1 $PINS ZN=n_0_610 A=B[18] 
Xi_0_716 INV_X1 $PINS ZN=n_0_609 A=B[17] 
Xi_0_519 INV_X1 $PINS ZN=n_0_608 A=B[16] 
Xi_0_714 INV_X1 $PINS ZN=n_0_607 A=B[13] 
Xi_0_518 INV_X1 $PINS ZN=n_0_606 A=B[12] 
Xi_0_712 INV_X1 $PINS ZN=n_0_605 A=B[11] 
Xi_0_711 INV_X1 $PINS ZN=n_0_604 A=B[10] 
Xi_0_517 INV_X1 $PINS ZN=n_0_603 A=B[9] 
Xi_0_516 INV_X1 $PINS ZN=n_0_96 A=A[24] 
Xi_0_515 INV_X1 $PINS ZN=n_0_588 A=A[22] 
Xi_0_514 INV_X1 $PINS ZN=n_0_587 A=A[21] 
Xi_0_513 INV_X1 $PINS ZN=n_0_586 A=A[20] 
Xi_0_692 INV_X1 $PINS ZN=n_0_585 A=A[19] 
Xi_0_691 INV_X1 $PINS ZN=n_0_584 A=A[18] 
Xi_0_690 INV_X1 $PINS ZN=n_0_583 A=A[17] 
Xi_0_689 INV_X1 $PINS ZN=n_0_582 A=A[16] 
Xi_0_688 INV_X1 $PINS ZN=n_0_581 A=A[15] 
Xi_0_687 INV_X1 $PINS ZN=n_0_580 A=A[14] 
Xi_0_512 INV_X1 $PINS ZN=n_0_579 A=A[13] 
Xi_0_685 INV_X1 $PINS ZN=n_0_578 A=A[12] 
Xi_0_511 INV_X1 $PINS ZN=n_0_564 A=n_53 
Xi_0_510 INV_X1 $PINS ZN=n_0_563 A=n_0_6 
Xi_0_509 INV_X1 $PINS ZN=exp_Sum[7] A=n_0_538 
Xi_0_508 AOI21_X1 $PINS ZN=n_0_532 A=B[22] B1=n_0_617 B2=n_0_539 
Xi_0_507 AOI22_X1 $PINS ZN=n_0_95 A1=B[24] A2=n_0_96 B1=B[23] B2=n_0_547 
Xi_0_506 INV_X1 $PINS ZN=n_0_515 A=n_0_575 
Xi_0_505 NAND3_X1 $PINS ZN=n_0_504 A1=n_0_602 A2=n_0_597 A3=n_0_515 
Xi_0_504 AOI21_X1 $PINS ZN=n_98 A=n_0_532 B1=n_0_617 B2=n_0_504 
Xi_0_503 AOI211_X1 $PINS ZN=n_0_502 A=drc_ipo_n4 B=n_0_575 C1=n_0_613 
+ C2=n_0_539 
Xi_0_502 AOI22_X1 $PINS ZN=n_0_501 A1=B[21] A2=n_102 B1=n_0_601 B2=n_0_502 
Xi_0_501 INV_X1 $PINS ZN=n_97 A=n_0_501 
Xi_0_603 NOR3_X1 $PINS ZN=n_0_500 A1=B[21] A2=n_0_598 A3=n_0_540 
Xi_0_500 AOI22_X1 $PINS ZN=n_0_499 A1=B[22] A2=n_0_598 B1=B[20] B2=n_0_597 
Xi_0_499 INV_X1 $PINS ZN=n_0_498 A=n_0_499 
Xi_0_498 AOI211_X1 $PINS ZN=n_0_497 A=n_0_500 B=n_0_575 C1=n_0_540 C2=n_0_499 
Xi_0_497 AOI22_X1 $PINS ZN=n_0_496 A1=B[20] A2=n_102 B1=n_0_601 B2=n_0_497 
Xi_0_496 INV_X1 $PINS ZN=n_96 A=n_0_496 
Xi_0_495 AND3_X1 $PINS ZN=n_0_494 A1=n_0_515 A2=n_0_498 A3=n_0_600 
Xi_0_494 NAND2_X1 $PINS ZN=n_0_491 A1=n_0_611 A2=n_0_593 
Xi_0_493 INV_X1 $PINS ZN=n_0_490 A=n_0_491 
Xi_0_492 AOI21_X1 $PINS ZN=n_0_489 A=n_0_597 B1=B[21] B2=n_0_593 
Xi_0_491 AOI211_X1 $PINS ZN=n_0_488 A=n_0_489 B=n_0_577 C1=n_0_597 C2=n_0_490 
Xi_0_490 AOI221_X1 $PINS ZN=n_0_487 A=n_0_494 B1=n_0_558 B2=n_0_488 C1=B[19] 
+ C2=n_102 
Xi_0_489 INV_X1 $PINS ZN=n_95 A=n_0_487 
Xi_0_488 OAI22_X1 $PINS ZN=n_0_486 A1=n_0_610 A2=n_0_598 B1=n_0_612 B2=n_0_597 
Xi_0_487 NAND2_X1 $PINS ZN=n_0_485 A1=n_0_515 A2=n_0_486 
Xi_0_486 NAND2_X1 $PINS ZN=n_0_483 A1=n_0_597 A2=n_0_576 
Xi_0_485 OAI21_X1 $PINS ZN=n_0_482 A=n_0_485 B1=n_0_613 B2=n_0_483 
Xi_0_484 AOI222_X1 $PINS ZN=n_0_481 A1=n_0_558 A2=n_0_482 B1=B[18] B2=n_102 
+ C1=n_0_600 C2=n_0_488 
Xi_0_483 INV_X1 $PINS ZN=n_94 A=n_0_481 
Xi_0_482 AOI22_X1 $PINS ZN=n_0_480 A1=B[17] A2=n_0_593 B1=B[21] B2=n_0_594 
Xi_0_481 INV_X1 $PINS ZN=n_0_479 A=n_0_480 
Xi_0_480 AOI221_X1 $PINS ZN=n_0_478 A=n_0_577 B1=n_0_597 B2=n_0_480 C1=n_0_598 
+ C2=n_0_490 
Xi_0_479 AOI222_X1 $PINS ZN=n_0_477 A1=n_0_558 A2=n_0_478 B1=B[17] B2=n_102 
+ C1=n_0_600 C2=n_0_482 
Xi_0_478 INV_X1 $PINS ZN=n_93 A=n_0_477 
Xi_0_477 AOI221_X1 $PINS ZN=n_0_476 A=n_0_575 B1=n_0_608 B2=n_0_597 C1=n_0_610 
+ C2=n_0_598 
Xi_0_476 AOI21_X1 $PINS ZN=n_0_475 A=n_0_476 B1=n_0_498 B2=n_0_576 
Xi_0_475 INV_X1 $PINS ZN=n_0_474 A=n_0_475 
Xi_0_474 AOI222_X1 $PINS ZN=n_0_473 A1=n_0_558 A2=n_0_474 B1=B[16] B2=n_102 
+ C1=n_0_600 C2=n_0_478 
Xi_0_473 INV_X1 $PINS ZN=n_92 A=n_0_473 
Xi_0_472 NAND2_X1 $PINS ZN=n_0_472 A1=n_0_598 A2=n_0_479 
Xi_0_471 AOI221_X1 $PINS ZN=n_0_469 A=n_0_572 B1=B[19] B2=n_0_576 C1=B[15] 
+ C2=n_0_515 
Xi_0_470 OAI22_X1 $PINS ZN=n_0_468 A1=n_0_577 A2=n_0_472 B1=n_0_598 B2=n_0_469 
Xi_0_469 AOI222_X1 $PINS ZN=n_0_467 A1=n_0_600 A2=n_0_474 B1=B[15] B2=n_102 
+ C1=n_0_558 C2=n_0_468 
Xi_0_468 INV_X1 $PINS ZN=n_91 A=n_0_467 
Xi_0_467 AOI22_X1 $PINS ZN=n_0_466 A1=B[14] A2=n_0_589 B1=B[22] B2=n_0_573 
Xi_0_466 OR2_X1 $PINS ZN=n_0_465 A1=n_0_594 A2=n_0_466 
Xi_0_465 NOR3_X1 $PINS ZN=n_0_464 A1=n_0_608 A2=n_0_597 A3=n_0_575 
Xi_0_464 AOI21_X1 $PINS ZN=n_0_463 A=n_0_464 B1=n_0_486 B2=n_0_576 
Xi_0_463 OAI21_X1 $PINS ZN=n_0_462 A=n_0_463 B1=n_0_598 B2=n_0_465 
Xi_0_462 AOI222_X1 $PINS ZN=n_0_461 A1=B[14] A2=n_102 B1=n_0_558 B2=n_0_462 
+ C1=n_0_600 C2=n_0_468 
Xi_0_460 INV_X1 $PINS ZN=n_90 A=n_0_461 
Xi_0_459 AOI222_X1 $PINS ZN=n_0_460 A1=B[13] A2=n_0_515 B1=B[21] B2=n_0_572 
+ C1=B[17] C2=n_0_576 
Xi_0_458 AOI22_X1 $PINS ZN=n_0_459 A1=n_0_597 A2=n_0_460 B1=n_0_598 B2=n_0_469 
Xi_0_457 AOI222_X1 $PINS ZN=n_0_458 A1=n_0_600 A2=n_0_462 B1=B[13] B2=n_102 
+ C1=n_0_558 C2=n_0_459 
Xi_0_456 INV_X1 $PINS ZN=n_89 A=n_0_458 
Xi_0_455 AOI222_X1 $PINS ZN=n_0_457 A1=B[16] A2=n_0_576 B1=B[12] B2=n_0_515 
+ C1=B[20] C2=n_0_572 
Xi_0_454 AOI21_X1 $PINS ZN=n_0_456 A=n_0_597 B1=B[18] B2=n_0_576 
Xi_0_453 AOI22_X1 $PINS ZN=n_0_455 A1=n_0_597 A2=n_0_457 B1=n_0_465 B2=n_0_456 
Xi_0_452 AOI22_X1 $PINS ZN=n_0_454 A1=n_0_600 A2=n_0_459 B1=n_0_558 B2=n_0_455 
Xi_0_451 OAI21_X1 $PINS ZN=n_88 A=n_0_454 B1=n_0_606 B2=n_0_617 
Xi_0_450 AOI222_X1 $PINS ZN=n_0_453 A1=B[11] A2=n_0_515 B1=n_0_491 B2=n_0_573 
+ C1=B[15] C2=n_0_576 
Xi_0_449 AOI22_X1 $PINS ZN=n_0_452 A1=n_0_597 A2=n_0_453 B1=n_0_598 B2=n_0_460 
Xi_0_448 AOI222_X1 $PINS ZN=n_0_451 A1=n_0_558 A2=n_0_452 B1=B[11] B2=n_102 
+ C1=n_0_600 C2=n_0_455 
Xi_0_447 INV_X1 $PINS ZN=n_87 A=n_0_451 
Xi_0_446 AOI22_X1 $PINS ZN=n_0_449 A1=n_0_594 A2=n_0_466 B1=n_0_593 B2=n_0_567 
Xi_0_445 INV_X1 $PINS ZN=n_0_448 A=n_0_449 
Xi_0_444 AOI22_X1 $PINS ZN=n_0_447 A1=n_0_598 A2=n_0_457 B1=n_0_597 B2=n_0_448 
Xi_0_443 AOI222_X1 $PINS ZN=n_0_446 A1=B[10] A2=n_102 B1=n_0_600 B2=n_0_452 
+ C1=n_0_558 C2=n_0_447 
Xi_0_442 INV_X1 $PINS ZN=n_86 A=n_0_446 
Xi_0_441 AOI222_X1 $PINS ZN=n_0_445 A1=B[9] A2=n_0_515 B1=n_0_479 B2=n_0_573 
+ C1=B[13] C2=n_0_576 
Xi_0_440 AOI22_X1 $PINS ZN=n_0_444 A1=n_0_597 A2=n_0_445 B1=n_0_598 B2=n_0_453 
Xi_0_439 AOI22_X1 $PINS ZN=n_0_443 A1=n_0_558 A2=n_0_444 B1=n_0_600 B2=n_0_447 
Xi_0_438 OAI21_X1 $PINS ZN=n_85 A=n_0_443 B1=n_0_603 B2=n_0_617 
Xi_0_437 AOI22_X1 $PINS ZN=n_0_438 A1=n_0_597 A2=n_0_568 B1=n_0_598 B2=n_0_448 
Xi_0_436 AOI222_X1 $PINS ZN=n_0_437 A1=n_0_558 A2=n_0_438 B1=B[8] B2=n_102 
+ C1=n_0_600 C2=n_0_444 
Xi_0_435 INV_X1 $PINS ZN=n_84 A=n_0_437 
Xi_0_434 AOI22_X1 $PINS ZN=n_0_432 A1=n_0_597 A2=n_0_552 B1=n_0_598 B2=n_0_445 
Xi_0_433 AOI222_X1 $PINS ZN=n_0_431 A1=n_0_558 A2=n_0_432 B1=B[7] B2=n_102 
+ C1=n_0_600 C2=n_0_438 
Xi_0_432 INV_X1 $PINS ZN=n_83 A=n_0_431 
Xi_0_431 AOI222_X1 $PINS ZN=n_0_426 A1=n_0_600 A2=n_0_432 B1=B[6] B2=n_102 
+ C1=n_0_558 C2=n_0_560 
Xi_0_430 INV_X1 $PINS ZN=n_82 A=n_0_426 
Xi_0_429 AOI22_X1 $PINS ZN=n_0_420 A1=B[12] A2=n_0_573 B1=B[20] B2=n_0_566 
Xi_0_428 OAI21_X1 $PINS ZN=n_0_419 A=n_0_420 B1=n_0_201 B2=n_0_577 
Xi_0_427 AOI222_X1 $PINS ZN=n_0_418 A1=B[16] A2=n_0_571 B1=B[8] B2=n_0_576 
+ C1=n_0_593 C2=n_0_419 
Xi_0_426 AOI22_X1 $PINS ZN=n_0_417 A1=n_0_597 A2=n_0_418 B1=n_0_598 B2=n_0_561 
Xi_0_425 AOI222_X1 $PINS ZN=n_0_416 A1=n_0_558 A2=n_0_417 B1=B[4] B2=n_102 
+ C1=n_0_600 C2=n_0_551 
Xi_0_424 INV_X1 $PINS ZN=n_81 A=n_0_416 
Xi_0_423 NAND2_X1 $PINS ZN=n_0_415 A1=B[11] A2=n_0_572 
Xi_0_422 NOR3_X1 $PINS ZN=n_0_414 A1=n_0_592 A2=n_0_590 A3=n_0_594 
Xi_0_421 OAI21_X1 $PINS ZN=n_0_413 A=n_0_415 B1=n_0_202 B2=n_0_575 
Xi_0_420 AOI221_X1 $PINS ZN=n_0_412 A=n_0_413 B1=n_0_594 B2=n_0_553 C1=B[19] 
+ C2=n_0_414 
Xi_0_419 AOI22_X1 $PINS ZN=n_0_411 A1=n_0_597 A2=n_0_412 B1=n_0_598 B2=n_0_555 
Xi_0_418 AOI22_X1 $PINS ZN=n_0_410 A1=n_0_600 A2=n_0_417 B1=n_0_558 B2=n_0_411 
Xi_0_417 OAI21_X1 $PINS ZN=n_80 A=n_0_410 B1=n_0_202 B2=n_0_617 
Xi_0_416 OAI22_X1 $PINS ZN=n_0_409 A1=n_0_593 A2=n_0_565 B1=n_0_199 B2=n_0_575 
Xi_0_415 AOI221_X1 $PINS ZN=n_0_408 A=n_0_409 B1=B[10] B2=n_0_572 C1=B[18] 
+ C2=n_0_414 
Xi_0_414 AOI22_X1 $PINS ZN=n_0_407 A1=n_0_597 A2=n_0_408 B1=n_0_598 B2=n_0_418 
Xi_0_413 AOI222_X1 $PINS ZN=n_0_406 A1=B[2] A2=n_102 B1=n_0_600 B2=n_0_411 
+ C1=n_0_558 C2=n_0_407 
Xi_0_412 INV_X1 $PINS ZN=n_79 A=n_0_406 
Xi_0_411 AOI22_X1 $PINS ZN=n_0_405 A1=n_0_594 A2=n_0_556 B1=B[9] B2=n_0_572 
Xi_0_410 INV_X1 $PINS ZN=n_0_404 A=n_0_405 
Xi_0_409 AOI221_X1 $PINS ZN=n_0_403 A=n_0_404 B1=B[17] B2=n_0_414 C1=B[1] 
+ C2=n_0_515 
Xi_0_408 AOI22_X1 $PINS ZN=n_0_402 A1=n_0_598 A2=n_0_412 B1=n_0_597 B2=n_0_403 
Xi_0_407 AOI22_X1 $PINS ZN=n_0_401 A1=n_0_558 A2=n_0_402 B1=n_0_600 B2=n_0_407 
Xi_0_406 OAI21_X1 $PINS ZN=n_78 A=n_0_401 B1=n_0_200 B2=n_0_617 
Xi_0_405 AOI21_X1 $PINS ZN=n_0_400 A=n_0_598 B1=B[16] B2=n_0_414 
Xi_0_404 AOI222_X1 $PINS ZN=n_0_399 A1=B[8] A2=n_0_572 B1=B[0] B2=n_0_515 
+ C1=n_0_594 C2=n_0_419 
Xi_0_403 AOI221_X1 $PINS ZN=n_0_398 A=n_0_559 B1=n_0_400 B2=n_0_399 C1=n_0_510 
+ C2=n_0_408 
Xi_0_402 AOI221_X1 $PINS ZN=n_0_397 A=n_0_398 B1=B[0] B2=n_102 C1=n_0_600 
+ C2=n_0_402 
Xi_0_401 INV_X1 $PINS ZN=n_77 A=n_0_397 
Xi_0_400 INV_X1 $PINS ZN=n_0_396 A=n_100 
Xi_0_399 AND2_X1 $PINS ZN=n_0_382 A1=n_0_422 A2=n_0_492 
Xi_0_398 AOI22_X1 $PINS ZN=n_0_381 A1=A[22] A2=n_100 B1=drc_ipo_n4 B2=n_0_382 
Xi_0_461 INV_X1 $PINS ZN=n_76 A=n_0_381 
Xi_0_397 AOI21_X1 $PINS ZN=n_0_380 A=n_0_597 B1=n_0_588 B2=n_0_599 
Xi_0_396 AOI22_X1 $PINS ZN=n_0_379 A1=A[21] A2=n_100 B1=n_0_382 B2=n_0_380 
Xi_0_395 INV_X1 $PINS ZN=n_75 A=n_0_379 
Xi_0_394 AOI21_X1 $PINS ZN=n_0_378 A=n_0_539 B1=A[22] B2=n_0_450 
Xi_0_393 AOI21_X1 $PINS ZN=n_0_377 A=n_0_378 B1=n_0_587 B2=drc_ipo_n4 
Xi_0_392 AOI22_X1 $PINS ZN=n_0_376 A1=A[20] A2=n_100 B1=n_0_382 B2=n_0_377 
Xi_0_391 INV_X1 $PINS ZN=n_74 A=n_0_376 
Xi_0_390 NAND2_X1 $PINS ZN=n_0_373 A1=n_0_450 A2=n_0_422 
Xi_0_389 NOR2_X1 $PINS ZN=n_0_372 A1=A[19] A2=n_0_441 
Xi_0_388 OAI33_X1 $PINS ZN=n_0_371 A1=drc_ipo_n4 A2=n_0_421 A3=n_0_587 
+ B1=n_0_430 B2=n_0_372 B3=n_0_450 
Xi_0_387 OAI22_X1 $PINS ZN=n_0_370 A1=n_0_588 A2=drc_ipo_n4 B1=n_0_586 
+ B2=n_0_450 
Xi_0_386 AND3_X1 $PINS ZN=n_0_368 A1=n_0_422 A2=n_0_370 A3=n_0_390 
Xi_0_385 AOI221_X1 $PINS ZN=n_0_367 A=n_0_368 B1=n_0_484 B2=n_0_371 C1=A[19] 
+ C2=n_100 
Xi_0_384 INV_X1 $PINS ZN=n_73 A=n_0_367 
Xi_0_383 AOI22_X1 $PINS ZN=n_0_365 A1=A[18] A2=n_0_422 B1=A[22] B2=n_0_394 
Xi_0_382 OAI22_X1 $PINS ZN=n_0_364 A1=n_0_586 A2=n_0_373 B1=n_0_450 B2=n_0_365 
Xi_0_381 AOI222_X1 $PINS ZN=n_0_363 A1=A[18] A2=n_100 B1=n_0_371 B2=n_0_390 
+ C1=n_0_484 C2=n_0_364 
Xi_0_380 INV_X1 $PINS ZN=n_72 A=n_0_363 
Xi_0_379 AOI221_X1 $PINS ZN=n_0_360 A=n_0_430 B1=drc_ipo_n4 B2=n_0_395 
+ C1=n_0_450 C2=n_0_372 
Xi_0_378 AOI222_X1 $PINS ZN=n_0_359 A1=n_0_484 A2=n_0_360 B1=A[17] B2=n_100 
+ C1=n_0_390 C2=n_0_364 
Xi_0_377 INV_X1 $PINS ZN=n_71 A=n_0_359 
Xi_0_376 AOI22_X1 $PINS ZN=n_0_358 A1=A[16] A2=n_0_422 B1=A[20] B2=n_0_394 
Xi_0_375 AOI22_X1 $PINS ZN=n_0_357 A1=n_0_450 A2=n_0_365 B1=drc_ipo_n4 
+ B2=n_0_358 
Xi_0_374 AOI222_X1 $PINS ZN=n_0_356 A1=n_0_390 A2=n_0_360 B1=A[16] B2=n_100 
+ C1=n_0_484 C2=n_0_357 
Xi_0_373 INV_X1 $PINS ZN=n_70 A=n_0_356 
Xi_0_372 NAND2_X1 $PINS ZN=n_0_355 A1=A[19] A2=n_0_394 
Xi_0_371 AND2_X1 $PINS ZN=n_0_351 A1=n_0_434 A2=n_0_425 
Xi_0_370 OAI21_X1 $PINS ZN=n_0_350 A=n_0_355 B1=n_0_441 B2=n_0_351 
Xi_0_369 NOR3_X1 $PINS ZN=n_0_349 A1=n_0_430 A2=n_0_395 A3=drc_ipo_n4 
Xi_0_368 AOI21_X1 $PINS ZN=n_0_348 A=n_0_349 B1=drc_ipo_n4 B2=n_0_350 
Xi_0_367 INV_X1 $PINS ZN=n_0_347 A=n_0_348 
Xi_0_366 AOI222_X1 $PINS ZN=n_0_346 A1=n_0_484 A2=n_0_347 B1=A[15] B2=n_100 
+ C1=n_0_390 C2=n_0_357 
Xi_0_365 INV_X1 $PINS ZN=n_69 A=n_0_346 
Xi_0_364 AOI222_X1 $PINS ZN=n_0_344 A1=A[22] A2=n_0_388 B1=A[14] B2=n_0_422 
+ C1=A[18] C2=n_0_394 
Xi_0_363 AOI22_X1 $PINS ZN=n_0_343 A1=n_0_450 A2=n_0_358 B1=drc_ipo_n4 
+ B2=n_0_344 
Xi_0_362 AOI222_X1 $PINS ZN=n_0_342 A1=A[14] A2=n_100 B1=n_0_390 B2=n_0_347 
+ C1=n_0_484 C2=n_0_343 
Xi_0_361 INV_X1 $PINS ZN=n_68 A=n_0_342 
Xi_0_360 AOI22_X1 $PINS ZN=n_0_341 A1=A[21] A2=n_0_388 B1=A[17] B2=n_0_394 
Xi_0_359 OAI21_X1 $PINS ZN=n_0_340 A=n_0_341 B1=n_0_579 B2=n_0_421 
Xi_0_358 AOI22_X1 $PINS ZN=n_0_339 A1=n_0_450 A2=n_0_350 B1=drc_ipo_n4 
+ B2=n_0_340 
Xi_0_357 INV_X1 $PINS ZN=n_0_338 A=n_0_339 
Xi_0_356 AOI222_X1 $PINS ZN=n_0_337 A1=n_0_390 A2=n_0_343 B1=A[13] B2=n_100 
+ C1=n_0_484 C2=n_0_338 
Xi_0_355 INV_X1 $PINS ZN=n_67 A=n_0_337 
Xi_0_354 AOI222_X1 $PINS ZN=n_0_336 A1=A[16] A2=n_0_394 B1=A[12] B2=n_0_422 
+ C1=A[20] C2=n_0_388 
Xi_0_353 AOI22_X1 $PINS ZN=n_0_335 A1=drc_ipo_n4 A2=n_0_336 B1=n_0_450 
+ B2=n_0_344 
Xi_0_352 AOI222_X1 $PINS ZN=n_0_334 A1=n_0_390 A2=n_0_338 B1=A[12] B2=n_100 
+ C1=n_0_484 C2=n_0_335 
Xi_0_351 INV_X1 $PINS ZN=n_66 A=n_0_334 
Xi_0_350 AOI22_X1 $PINS ZN=n_0_332 A1=n_0_442 A2=n_0_428 B1=n_0_441 B2=n_0_351 
Xi_0_349 INV_X1 $PINS ZN=n_0_331 A=n_0_332 
Xi_0_348 NAND2_X1 $PINS ZN=n_0_330 A1=n_0_450 A2=n_0_340 
Xi_0_347 OAI21_X1 $PINS ZN=n_0_329 A=n_0_330 B1=n_0_450 B2=n_0_331 
Xi_0_346 AOI222_X1 $PINS ZN=n_0_328 A1=n_0_484 A2=n_0_329 B1=A[11] B2=n_100 
+ C1=n_0_390 C2=n_0_335 
Xi_0_344 INV_X1 $PINS ZN=n_65 A=n_0_328 
Xi_0_343 NOR2_X1 $PINS ZN=n_0_322 A1=n_0_450 A2=n_0_384 
Xi_0_342 AOI21_X1 $PINS ZN=n_0_321 A=n_0_322 B1=n_0_450 B2=n_0_336 
Xi_0_341 AOI222_X1 $PINS ZN=n_0_320 A1=n_0_390 A2=n_0_329 B1=A[10] B2=n_100 
+ C1=n_0_484 C2=n_0_321 
Xi_0_340 INV_X1 $PINS ZN=n_64 A=n_0_320 
Xi_0_339 AOI22_X1 $PINS ZN=n_0_318 A1=drc_ipo_n4 A2=n_0_392 B1=n_0_450 
+ B2=n_0_331 
Xi_0_338 AOI222_X1 $PINS ZN=n_0_317 A1=n_0_390 A2=n_0_321 B1=A[9] B2=n_100 
+ C1=n_0_484 C2=n_0_318 
Xi_0_337 INV_X1 $PINS ZN=n_63 A=n_0_317 
Xi_0_336 AOI222_X1 $PINS ZN=n_0_311 A1=n_0_390 A2=n_0_318 B1=A[8] B2=n_100 
+ C1=n_0_484 C2=n_0_369 
Xi_0_335 INV_X1 $PINS ZN=n_62 A=n_0_311 
Xi_0_334 NOR2_X1 $PINS ZN=n_0_305 A1=n_0_439 A2=n_0_435 
Xi_0_332 AOI22_X1 $PINS ZN=n_0_304 A1=A[14] A2=n_0_433 B1=A[22] B2=n_0_305 
Xi_0_331 OAI21_X1 $PINS ZN=n_0_303 A=n_0_304 B1=n_0_309 B2=n_0_430 
Xi_0_330 AOI222_X1 $PINS ZN=n_0_302 A1=A[18] A2=n_0_389 B1=A[10] B2=n_0_394 
+ C1=n_0_442 C2=n_0_303 
Xi_0_329 AOI22_X1 $PINS ZN=n_0_301 A1=drc_ipo_n4 A2=n_0_302 B1=n_0_450 
+ B2=n_0_374 
Xi_0_328 AOI222_X1 $PINS ZN=n_0_300 A1=A[6] A2=n_100 B1=n_0_390 B2=n_0_391 
+ C1=n_0_484 C2=n_0_301 
Xi_0_327 INV_X1 $PINS ZN=n_61 A=n_0_300 
Xi_0_326 AOI22_X1 $PINS ZN=n_0_299 A1=A[13] A2=n_0_433 B1=A[21] B2=n_0_305 
Xi_0_325 OAI21_X1 $PINS ZN=n_0_298 A=n_0_299 B1=n_0_307 B2=n_0_430 
Xi_0_324 AOI222_X1 $PINS ZN=n_0_297 A1=A[17] A2=n_0_389 B1=A[9] B2=n_0_394 
+ C1=n_0_442 C2=n_0_298 
Xi_0_323 AOI22_X1 $PINS ZN=n_0_296 A1=drc_ipo_n4 A2=n_0_297 B1=n_0_450 
+ B2=n_0_423 
Xi_0_322 AOI222_X1 $PINS ZN=n_0_295 A1=n_0_390 A2=n_0_301 B1=A[5] B2=n_100 
+ C1=n_0_484 C2=n_0_296 
Xi_0_321 INV_X1 $PINS ZN=n_60 A=n_0_295 
Xi_0_320 AOI22_X1 $PINS ZN=n_0_294 A1=A[12] A2=n_0_433 B1=A[20] B2=n_0_305 
Xi_0_319 OAI21_X1 $PINS ZN=n_0_293 A=n_0_294 B1=n_0_306 B2=n_0_430 
Xi_0_318 AOI222_X1 $PINS ZN=n_0_292 A1=A[16] A2=n_0_389 B1=A[8] B2=n_0_394 
+ C1=n_0_442 C2=n_0_293 
Xi_0_317 AOI22_X1 $PINS ZN=n_0_291 A1=drc_ipo_n4 A2=n_0_292 B1=n_0_450 
+ B2=n_0_302 
Xi_0_316 AOI222_X1 $PINS ZN=n_0_290 A1=n_0_390 A2=n_0_296 B1=A[4] B2=n_100 
+ C1=n_0_484 C2=n_0_291 
Xi_0_315 INV_X1 $PINS ZN=n_59 A=n_0_290 
Xi_0_314 NOR3_X1 $PINS ZN=n_0_289 A1=n_0_439 A2=n_0_435 A3=n_0_441 
Xi_0_313 AOI22_X1 $PINS ZN=n_0_288 A1=n_0_441 A2=n_0_424 B1=A[11] B2=n_0_388 
Xi_0_312 INV_X1 $PINS ZN=n_0_287 A=n_0_288 
Xi_0_311 AOI221_X1 $PINS ZN=n_0_286 A=n_0_287 B1=A[19] B2=n_0_289 C1=A[3] 
+ C2=n_0_422 
Xi_0_310 AOI22_X1 $PINS ZN=n_0_285 A1=drc_ipo_n4 A2=n_0_286 B1=n_0_450 
+ B2=n_0_297 
Xi_0_309 AOI222_X2 $PINS ZN=n_0_284 A1=n_0_390 A2=n_0_291 B1=A[3] B2=n_100 
+ C1=n_0_484 C2=n_0_285 
Xi_0_345 INV_X1 $PINS ZN=n_58 A=n_0_284 
Xi_0_308 AOI22_X1 $PINS ZN=n_0_283 A1=n_0_441 A2=n_0_303 B1=A[10] B2=n_0_388 
Xi_0_307 INV_X1 $PINS ZN=n_0_282 A=n_0_283 
Xi_0_306 AOI221_X1 $PINS ZN=n_0_281 A=n_0_282 B1=A[18] B2=n_0_289 C1=A[2] 
+ C2=n_0_422 
Xi_0_305 AOI22_X1 $PINS ZN=n_0_280 A1=drc_ipo_n4 A2=n_0_281 B1=n_0_450 
+ B2=n_0_292 
Xi_0_304 AOI222_X2 $PINS ZN=n_0_279 A1=n_0_484 A2=n_0_280 B1=A[2] B2=n_100 
+ C1=n_0_390 C2=n_0_285 
Xi_0_303 INV_X1 $PINS ZN=n_57 A=n_0_279 
Xi_0_302 NAND2_X1 $PINS ZN=n_0_278 A1=A[9] A2=n_0_388 
Xi_0_301 OAI21_X1 $PINS ZN=n_0_277 A=n_0_278 B1=n_0_198 B2=n_0_421 
Xi_0_300 AOI221_X1 $PINS ZN=n_0_276 A=n_0_277 B1=A[17] B2=n_0_289 C1=n_0_441 
+ C2=n_0_298 
Xi_0_299 AOI22_X1 $PINS ZN=n_0_275 A1=n_0_450 A2=n_0_286 B1=drc_ipo_n4 
+ B2=n_0_276 
Xi_0_298 AOI222_X2 $PINS ZN=n_0_274 A1=n_0_390 A2=n_0_280 B1=A[1] B2=n_100 
+ C1=n_0_484 C2=n_0_275 
Xi_0_333 INV_X1 $PINS ZN=n_56 A=n_0_274 
Xi_0_297 AOI22_X1 $PINS ZN=n_0_273 A1=n_0_441 A2=n_0_293 B1=A[0] B2=n_0_422 
Xi_0_296 INV_X1 $PINS ZN=n_0_272 A=n_0_273 
Xi_0_295 AOI221_X1 $PINS ZN=n_0_271 A=n_0_272 B1=A[8] B2=n_0_388 C1=A[16] 
+ C2=n_0_289 
Xi_0_294 AOI221_X1 $PINS ZN=n_0_270 A=n_0_471 B1=drc_ipo_n4 B2=n_0_271 
+ C1=n_0_450 C2=n_0_281 
Xi_0_293 AOI221_X1 $PINS ZN=n_0_269 A=n_0_270 B1=A[0] B2=n_100 C1=n_0_390 
+ C2=n_0_275 
Xi_0_292 INV_X1 $PINS ZN=n_55 A=n_0_269 
Xi_0_291 AOI22_X1 $PINS ZN=n_0_268 A1=B[29] A2=n_0_396 B1=A[29] B2=n_100 
Xi_0_290 INV_X1 $PINS ZN=exp_Sum[6] A=n_0_268 
Xi_0_289 AOI22_X1 $PINS ZN=n_0_267 A1=B[28] A2=n_0_396 B1=A[28] B2=n_100 
Xi_0_288 INV_X1 $PINS ZN=exp_Sum[5] A=n_0_267 
Xi_0_287 AOI22_X1 $PINS ZN=n_0_266 A1=B[27] A2=n_0_396 B1=A[27] B2=n_100 
Xi_0_286 INV_X1 $PINS ZN=exp_Sum[4] A=n_0_266 
Xi_0_285 AOI22_X1 $PINS ZN=n_0_265 A1=B[26] A2=n_0_396 B1=A[26] B2=n_100 
Xi_0_284 INV_X1 $PINS ZN=exp_Sum[3] A=n_0_265 
Xi_0_283 AOI22_X1 $PINS ZN=n_0_264 A1=B[25] A2=n_0_396 B1=A[25] B2=n_100 
Xi_0_282 INV_X1 $PINS ZN=exp_Sum[2] A=n_0_264 
Xi_0_281 AOI22_X1 $PINS ZN=n_0_263 A1=B[24] A2=n_0_396 B1=A[24] B2=n_100 
Xi_0_280 INV_X1 $PINS ZN=exp_Sum[1] A=n_0_263 
Xi_0_279 AOI22_X1 $PINS ZN=n_0_262 A1=B[23] A2=n_0_396 B1=A[23] B2=n_100 
Xi_0_277 INV_X1 $PINS ZN=exp_Sum[0] A=n_0_262 
Xi_0_276 NAND2_X1 $PINS ZN=n_0_261 A1=n_78 A2=n_0_274 
Xi_0_275 XOR2_X1 $PINS Z=n_0_260 A=n_88 B=n_66 
Xi_0_274 NOR2_X1 $PINS ZN=n_0_259 A1=n_85 A2=n_0_317 
Xi_0_273 AOI222_X1 $PINS ZN=n_0_258 A1=n_0_501 A2=n_75 B1=n_0_496 B2=n_74 
+ C1=n_97 C2=n_0_379 
Xi_0_272 XOR2_X1 $PINS Z=n_0_257 A=n_98 B=n_0_381 
Xi_0_271 AOI211_X1 $PINS ZN=n_0_256 A=n_0_506 B=n_0_517 C1=n_96 C2=n_0_376 
Xi_0_270 NAND3_X1 $PINS ZN=n_0_255 A1=n_0_257 A2=n_0_256 A3=n_0_258 
Xi_0_269 AOI22_X1 $PINS ZN=n_0_254 A1=n_0_451 A2=n_65 B1=n_87 B2=n_0_328 
Xi_0_268 OAI22_X1 $PINS ZN=n_0_253 A1=n_0_431 A2=n_0_366 B1=n_83 B2=n_99 
Xi_0_267 AOI22_X1 $PINS ZN=n_0_252 A1=n_82 A2=n_0_300 B1=n_0_446 B2=n_64 
Xi_0_266 AOI222_X1 $PINS ZN=n_0_251 A1=n_93 A2=n_0_359 B1=n_92 B2=n_0_356 
+ C1=n_0_426 C2=n_61 
Xi_0_265 OAI221_X1 $PINS ZN=n_0_250 A=n_0_251 B1=n_0_487 B2=n_73 C1=n_95 
+ C2=n_0_367 
Xi_0_264 AOI221_X1 $PINS ZN=n_0_249 A=n_0_250 B1=n_86 B2=n_0_320 C1=n_0_437 
+ C2=n_62 
Xi_0_263 OAI211_X1 $PINS ZN=n_0_248 A=n_0_252 B=n_0_249 C1=n_0_437 C2=n_62 
Xi_0_262 AOI221_X1 $PINS ZN=n_0_247 A=n_0_248 B1=n_0_550 B2=n_60 C1=n_101 
+ C2=n_0_295 
Xi_0_261 OAI221_X1 $PINS ZN=n_0_246 A=n_0_247 B1=n_0_397 B2=n_55 C1=n_77 
+ C2=n_0_269 
Xi_0_260 OAI221_X1 $PINS ZN=n_0_245 A=n_0_254 B1=n_79 B2=n_0_279 C1=n_78 
+ C2=n_0_274 
Xi_0_259 OAI21_X1 $PINS ZN=n_0_244 A=n_0_261 B1=n_81 B2=n_0_290 
Xi_0_258 AOI22_X1 $PINS ZN=n_0_243 A1=n_94 A2=n_0_363 B1=n_0_481 B2=n_72 
Xi_0_257 AOI22_X1 $PINS ZN=n_0_242 A1=n_91 A2=n_0_346 B1=n_90 B2=n_0_342 
Xi_0_256 AOI221_X1 $PINS ZN=n_0_241 A=n_0_255 B1=n_0_477 B2=n_71 C1=n_0_473 
+ C2=n_70 
Xi_0_255 AOI22_X1 $PINS ZN=n_0_240 A1=n_0_467 A2=n_69 B1=n_0_461 B2=n_68 
Xi_0_254 NAND4_X1 $PINS ZN=n_0_239 A1=n_0_243 A2=n_0_242 A3=n_0_241 A4=n_0_240 
Xi_0_253 NOR4_X1 $PINS ZN=n_0_238 A1=n_0_260 A2=n_0_245 A3=n_0_244 A4=n_0_239 
Xi_0_252 OAI222_X1 $PINS ZN=n_0_237 A1=n_80 A2=n_0_284 B1=n_0_406 B2=n_57 
+ C1=n_0_416 C2=n_59 
Xi_0_251 AOI221_X1 $PINS ZN=n_0_236 A=n_0_237 B1=n_0_458 B2=n_67 C1=n_89 
+ C2=n_0_337 
Xi_0_250 AOI221_X1 $PINS ZN=n_0_235 A=n_0_259 B1=n_85 B2=n_0_317 C1=n_80 
+ C2=n_0_284 
Xi_0_249 NAND4_X1 $PINS ZN=n_0_234 A1=n_0_253 A2=n_0_235 A3=n_0_236 A4=n_0_238 
Xi_0_248 XNOR2_X1 $PINS ZN=n_0_233 A=n_0_94 B=A[31] 
Xi_0_247 INV_X1 $PINS ZN=n_0_232 A=n_0_233 
Xi_0_246 OAI21_X4 $PINS ZN=n_0_231 A=n_0_233 B1=n_0_246 B2=n_0_234 
Xi_0_245 INV_X1 $PINS ZN=n_0_230 A=n_0_231 
Xi_0_244 AOI21_X1 $PINS ZN=n_0_229 A=n_0_231 B1=num_leading_zeros[4] 
+ B2=num_leading_zeros[3] 
Xi_0_243 INV_X1 $PINS ZN=n_0_228 A=n_0_229 
Xi_0_278 AND2_X1 $PINS ZN=underflow A1=n_25 A2=n_0_229 
Xi_0_242 NAND3_X1 $PINS ZN=n_0_227 A1=exp_Sum[3] A2=exp_Sum[2] A3=exp_Sum[1] 
Xi_0_241 NOR4_X1 $PINS ZN=n_0_226 A1=exp_Sum[0] A2=n_0_227 A3=n_0_267 
+ A4=n_0_266 
Xi_0_240 NAND4_X1 $PINS ZN=n_0_225 A1=n_24 A2=exp_Sum[7] A3=exp_Sum[6] 
+ A4=n_0_226 
Xi_0_239 NOR2_X1 $PINS ZN=overflow A1=n_0_233 A2=n_0_225 
Xi_0_238 AND2_X1 $PINS ZN=mant_A[31] A1=n_54 A2=n_0_230 
Xi_0_237 AOI22_X1 $PINS ZN=mant_A[23] A1=n_0_564 A2=n_0_230 B1=n_0_396 
+ B2=n_0_232 
Xi_0_236 NOR2_X1 $PINS ZN=n_0_224 A1=n_52 A2=n_0_231 
Xi_0_235 AOI21_X1 $PINS ZN=mant_A[22] A=n_0_224 B1=n_0_381 B2=n_0_231 
Xi_0_234 NOR2_X1 $PINS ZN=n_0_223 A1=n_51 A2=n_0_231 
Xi_0_233 AOI21_X1 $PINS ZN=mant_A[21] A=n_0_223 B1=n_0_379 B2=n_0_231 
Xi_0_232 NOR2_X1 $PINS ZN=n_0_222 A1=n_50 A2=n_0_231 
Xi_0_231 AOI21_X1 $PINS ZN=mant_A[20] A=n_0_222 B1=n_0_376 B2=n_0_231 
Xi_0_230 NOR2_X1 $PINS ZN=n_0_221 A1=n_49 A2=n_0_231 
Xi_0_229 AOI21_X1 $PINS ZN=mant_A[19] A=n_0_221 B1=n_0_367 B2=n_0_231 
Xi_0_228 NOR2_X1 $PINS ZN=n_0_220 A1=n_48 A2=n_0_231 
Xi_0_227 AOI21_X1 $PINS ZN=mant_A[18] A=n_0_220 B1=n_0_363 B2=n_0_231 
Xi_0_226 NOR2_X1 $PINS ZN=n_0_219 A1=n_47 A2=n_0_231 
Xi_0_225 AOI21_X1 $PINS ZN=mant_A[17] A=n_0_219 B1=n_0_359 B2=n_0_231 
Xi_0_224 NOR2_X1 $PINS ZN=n_0_218 A1=n_46 A2=n_0_231 
Xi_0_223 AOI21_X1 $PINS ZN=mant_A[16] A=n_0_218 B1=n_0_356 B2=n_0_231 
Xi_0_222 NOR2_X1 $PINS ZN=n_0_217 A1=n_45 A2=n_0_231 
Xi_0_221 AOI21_X1 $PINS ZN=mant_A[15] A=n_0_217 B1=n_0_346 B2=n_0_231 
Xi_0_220 NOR2_X1 $PINS ZN=n_0_216 A1=n_44 A2=n_0_231 
Xi_0_219 AOI21_X1 $PINS ZN=mant_A[14] A=n_0_216 B1=n_0_342 B2=n_0_231 
Xi_0_218 NOR2_X1 $PINS ZN=n_0_215 A1=n_43 A2=n_0_231 
Xi_0_217 AOI21_X1 $PINS ZN=mant_A[13] A=n_0_215 B1=n_0_337 B2=n_0_231 
Xi_0_195 NOR2_X1 $PINS ZN=n_0_214 A1=n_42 A2=n_0_231 
Xi_0_194 AOI21_X1 $PINS ZN=mant_A[12] A=n_0_214 B1=n_0_334 B2=n_0_231 
Xi_0_193 NOR2_X1 $PINS ZN=n_0_213 A1=n_41 A2=n_0_231 
Xi_0_192 AOI21_X1 $PINS ZN=mant_A[11] A=n_0_213 B1=n_0_328 B2=n_0_231 
Xi_0_191 NOR2_X1 $PINS ZN=n_0_212 A1=n_40 A2=n_0_231 
Xi_0_190 AOI21_X1 $PINS ZN=mant_A[10] A=n_0_212 B1=n_0_320 B2=n_0_231 
Xi_0_189 NOR2_X1 $PINS ZN=n_0_211 A1=n_39 A2=n_0_231 
Xi_0_188 AOI21_X1 $PINS ZN=mant_A[9] A=n_0_211 B1=n_0_317 B2=n_0_231 
Xi_0_187 NOR2_X1 $PINS ZN=n_0_210 A1=n_38 A2=n_0_231 
Xi_0_186 AOI21_X1 $PINS ZN=mant_A[8] A=n_0_210 B1=n_0_311 B2=n_0_231 
Xi_0_185 NOR2_X1 $PINS ZN=n_0_209 A1=n_37 A2=n_0_231 
Xi_0_184 AOI21_X1 $PINS ZN=mant_A[7] A=n_0_209 B1=n_0_366 B2=n_0_231 
Xi_0_183 NOR2_X1 $PINS ZN=n_0_208 A1=n_36 A2=n_0_231 
Xi_0_182 AOI21_X1 $PINS ZN=mant_A[6] A=n_0_208 B1=n_0_300 B2=n_0_231 
Xi_0_181 NOR2_X1 $PINS ZN=n_0_207 A1=n_35 A2=n_0_231 
Xi_0_180 AOI21_X1 $PINS ZN=mant_A[5] A=n_0_207 B1=n_0_295 B2=n_0_231 
Xi_0_179 NOR2_X1 $PINS ZN=n_0_206 A1=n_34 A2=n_0_231 
Xi_0_178 AOI21_X1 $PINS ZN=mant_A[4] A=n_0_206 B1=n_0_290 B2=n_0_231 
Xi_0_177 NOR2_X1 $PINS ZN=n_0_205 A1=n_33 A2=n_0_231 
Xi_0_176 AOI21_X1 $PINS ZN=mant_A[3] A=n_0_205 B1=n_0_284 B2=n_0_231 
Xi_0_175 NOR2_X1 $PINS ZN=n_0_204 A1=n_32 A2=n_0_231 
Xi_0_174 AOI21_X1 $PINS ZN=mant_A[2] A=n_0_204 B1=n_0_279 B2=n_0_231 
Xi_0_173 NOR2_X1 $PINS ZN=n_0_203 A1=n_31 A2=n_0_231 
Xi_0_172 AOI21_X1 $PINS ZN=mant_A[1] A=n_0_203 B1=n_0_274 B2=n_0_231 
Xi_0_216 AOI221_X1 $PINS ZN=n_0_191 A=n_0_362 B1=n_0_603 B2=A[9] C1=n_0_604 
+ C2=A[10] 
Xi_0_215 INV_X1 $PINS ZN=n_0_190 A=n_0_191 
Xi_0_214 OAI221_X1 $PINS ZN=n_0_189 A=n_0_190 B1=n_0_604 B2=A[10] C1=n_0_605 
+ C2=A[11] 
Xi_0_213 AOI22_X1 $PINS ZN=n_0_188 A1=n_0_606 A2=A[12] B1=n_0_605 B2=A[11] 
Xi_0_212 AOI22_X1 $PINS ZN=n_0_187 A1=n_0_189 A2=n_0_188 B1=B[12] B2=n_0_578 
Xi_0_211 AOI21_X1 $PINS ZN=n_0_186 A=n_0_187 B1=n_0_607 B2=A[13] 
Xi_0_210 AOI221_X1 $PINS ZN=n_0_185 A=n_0_186 B1=B[13] B2=n_0_579 C1=B[14] 
+ C2=n_0_580 
Xi_0_209 INV_X1 $PINS ZN=n_0_184 A=n_0_185 
Xi_0_208 OAI221_X1 $PINS ZN=n_0_183 A=n_0_184 B1=B[14] B2=n_0_580 C1=B[15] 
+ C2=n_0_581 
Xi_0_207 AOI22_X1 $PINS ZN=n_0_182 A1=B[16] A2=n_0_582 B1=B[15] B2=n_0_581 
Xi_0_206 AOI22_X1 $PINS ZN=n_0_181 A1=n_0_183 A2=n_0_182 B1=n_0_608 B2=A[16] 
Xi_0_205 AOI21_X1 $PINS ZN=n_0_180 A=n_0_181 B1=B[17] B2=n_0_583 
Xi_0_204 AOI221_X1 $PINS ZN=n_0_179 A=n_0_180 B1=n_0_609 B2=A[17] C1=n_0_610 
+ C2=A[18] 
Xi_0_203 AOI221_X1 $PINS ZN=n_0_178 A=n_0_179 B1=B[19] B2=n_0_585 C1=B[18] 
+ C2=n_0_584 
Xi_0_202 AOI221_X1 $PINS ZN=n_0_177 A=n_0_178 B1=n_0_611 B2=A[19] C1=n_0_612 
+ C2=A[20] 
Xi_0_201 AOI221_X1 $PINS ZN=n_0_176 A=n_0_177 B1=B[21] B2=n_0_587 C1=B[20] 
+ C2=n_0_586 
Xi_0_200 OAI22_X1 $PINS ZN=n_0_175 A1=B[21] A2=n_0_587 B1=B[22] B2=n_0_588 
Xi_0_199 OAI22_X1 $PINS ZN=n_0_174 A1=n_0_613 A2=A[22] B1=n_0_176 B2=n_0_175 
Xi_0_198 AOI21_X1 $PINS ZN=n_0_173 A=n_0_396 B1=n_102 B2=n_0_174 
Xi_0_197 NAND2_X1 $PINS ZN=n_0_172 A1=A[31] A2=n_0_173 
Xi_0_196 OAI21_X1 $PINS ZN=Sum[31] A=n_0_172 B1=n_0_94 B2=n_0_173 
Xi_0_171 NOR2_X1 $PINS ZN=n_0_171 A1=n_25 A2=n_0_228 
Xi_0_170 AOI22_X1 $PINS ZN=n_0_170 A1=n_0_129 A2=exp_Sum[4] B1=n_30 B2=n_0_266 
Xi_0_169 AOI22_X1 $PINS ZN=n_0_169 A1=n_29 A2=n_0_265 B1=n_0_128 B2=exp_Sum[3] 
Xi_0_168 AOI22_X1 $PINS ZN=n_0_168 A1=n_28 A2=n_0_264 B1=n_0_126 B2=exp_Sum[2] 
Xi_0_167 INV_X1 $PINS ZN=n_0_167 A=n_0_168 
Xi_0_166 NAND2_X1 $PINS ZN=n_0_166 A1=n_26 A2=n_0_262 
Xi_0_165 INV_X1 $PINS ZN=n_0_165 A=n_0_166 
Xi_0_164 AOI22_X1 $PINS ZN=n_0_164 A1=n_27 A2=n_0_263 B1=n_0_125 B2=exp_Sum[1] 
Xi_0_163 AOI22_X1 $PINS ZN=n_0_163 A1=n_27 A2=n_0_263 B1=n_0_165 B2=n_0_164 
Xi_0_162 OAI22_X1 $PINS ZN=n_0_162 A1=n_0_126 A2=exp_Sum[2] B1=n_0_167 
+ B2=n_0_163 
Xi_0_161 AOI22_X1 $PINS ZN=n_0_161 A1=n_29 A2=n_0_265 B1=n_0_169 B2=n_0_162 
Xi_0_160 AOI22_X1 $PINS ZN=n_0_160 A1=n_0_129 A2=exp_Sum[4] B1=n_0_170 
+ B2=n_0_161 
Xi_0_159 NAND2_X1 $PINS ZN=n_0_159 A1=n_0_267 A2=n_0_160 
Xi_0_158 NOR2_X1 $PINS ZN=n_0_158 A1=exp_Sum[6] A2=n_0_159 
Xi_0_157 INV_X1 $PINS ZN=n_0_157 A=n_0_158 
Xi_0_156 NAND2_X1 $PINS ZN=n_0_156 A1=n_0_171 A2=n_0_158 
Xi_0_155 AOI21_X1 $PINS ZN=n_0_155 A=exp_Sum[7] B1=n_0_6 B2=n_0_232 
Xi_0_154 NAND3_X1 $PINS ZN=n_0_154 A1=num_leading_zeros[4] 
+ A2=num_leading_zeros[3] A3=n_0_230 
Xi_0_153 INV_X1 $PINS ZN=n_0_153 A=n_0_154 
Xi_0_152 AOI221_X1 $PINS ZN=n_0_152 A=n_0_153 B1=n_0_171 B2=n_0_157 C1=n_0_563 
+ C2=n_0_232 
Xi_0_151 AOI22_X1 $PINS ZN=Sum[30] A1=n_0_156 A2=n_0_155 B1=exp_Sum[7] 
+ B2=n_0_152 
Xi_0_150 AOI21_X1 $PINS ZN=n_0_151 A=n_0_153 B1=n_0_171 B2=n_0_159 
Xi_0_149 NAND2_X1 $PINS ZN=n_0_150 A1=n_0_13 A2=n_0_232 
Xi_0_148 OAI211_X1 $PINS ZN=Sum[29] A=n_0_156 B=n_0_150 C1=n_0_268 C2=n_0_151 
Xi_0_147 OAI21_X1 $PINS ZN=n_0_149 A=n_0_159 B1=n_0_267 B2=n_0_160 
Xi_0_146 AOI22_X1 $PINS ZN=n_0_148 A1=n_0_12 A2=n_0_232 B1=n_0_171 B2=n_0_149 
Xi_0_145 OAI21_X1 $PINS ZN=Sum[28] A=n_0_148 B1=n_0_267 B2=n_0_154 
Xi_0_144 XOR2_X1 $PINS Z=n_0_147 A=n_0_170 B=n_0_161 
Xi_0_143 AOI222_X1 $PINS ZN=n_0_146 A1=n_0_11 A2=n_0_232 B1=exp_Sum[4] 
+ B2=n_0_153 C1=n_0_171 C2=n_0_147 
Xi_0_142 INV_X1 $PINS ZN=Sum[27] A=n_0_146 
Xi_0_141 XNOR2_X1 $PINS ZN=n_0_145 A=n_0_169 B=n_0_162 
Xi_0_140 AOI222_X1 $PINS ZN=n_0_144 A1=n_0_10 A2=n_0_232 B1=exp_Sum[3] 
+ B2=n_0_153 C1=n_0_171 C2=n_0_145 
Xi_0_139 INV_X1 $PINS ZN=Sum[26] A=n_0_144 
Xi_0_138 XOR2_X1 $PINS Z=n_0_143 A=n_0_168 B=n_0_163 
Xi_0_137 AOI222_X1 $PINS ZN=n_0_142 A1=n_0_9 A2=n_0_232 B1=exp_Sum[2] 
+ B2=n_0_153 C1=n_0_171 C2=n_0_143 
Xi_0_136 INV_X1 $PINS ZN=Sum[25] A=n_0_142 
Xi_0_135 XOR2_X1 $PINS Z=n_0_141 A=n_0_166 B=n_0_164 
Xi_0_134 AOI222_X1 $PINS ZN=n_0_140 A1=n_0_8 A2=n_0_232 B1=exp_Sum[1] 
+ B2=n_0_153 C1=n_0_171 C2=n_0_141 
Xi_0_133 INV_X1 $PINS ZN=Sum[24] A=n_0_140 
Xi_0_132 OAI21_X1 $PINS ZN=n_0_139 A=n_0_166 B1=n_26 B2=n_0_262 
Xi_0_131 AOI222_X1 $PINS ZN=n_0_138 A1=n_0_7 A2=n_0_232 B1=exp_Sum[0] 
+ B2=n_0_153 C1=n_0_171 C2=n_0_139 
Xi_0_130 INV_X1 $PINS ZN=Sum[23] A=n_0_138 
Xi_0_129 OAI21_X2 $PINS ZN=n_0_137 A=n_0_154 B1=n_24 B2=n_0_233 
Xi_0_128 AND3_X1 $PINS ZN=n_0_136 A1=n_24 A2=n_0_232 A3=n_0_225 
Xi_0_127 AOI22_X1 $PINS ZN=n_0_135 A1=n_22 A2=n_0_137 B1=n_23 B2=n_0_136 
Xi_0_126 NAND2_X1 $PINS ZN=n_0_134 A1=n_26 A2=n_0_229 
Xi_0_125 INV_X1 $PINS ZN=n_0_133 A=n_0_134 
Xi_0_124 NAND2_X1 $PINS ZN=n_0_127 A1=n_13 A2=n_0_119 
Xi_0_123 AOI22_X1 $PINS ZN=n_0_124 A1=n_21 A2=n_0_113 B1=n_5 B2=n_0_121 
Xi_0_122 OAI211_X1 $PINS ZN=n_0_123 A=n_0_127 B=n_0_124 C1=n_0_126 C2=n_0_102 
Xi_0_121 OAI22_X1 $PINS ZN=n_0_118 A1=n_0_125 A2=n_0_110 B1=n_27 B2=n_0_123 
Xi_0_120 INV_X1 $PINS ZN=n_0_117 A=n_0_118 
Xi_0_119 NOR2_X2 $PINS ZN=n_0_116 A1=n_26 A2=n_0_228 
Xi_0_118 INV_X1 $PINS ZN=n_0_115 A=n_0_116 
Xi_0_117 AOI22_X1 $PINS ZN=n_0_108 A1=n_14 A2=n_0_119 B1=n_6 B2=n_0_121 
Xi_0_116 OAI21_X1 $PINS ZN=n_0_107 A=n_0_108 B1=n_0_126 B2=n_0_197 
Xi_0_115 AOI21_X1 $PINS ZN=n_0_106 A=n_0_107 B1=n_22 B2=n_0_113 
Xi_0_114 AOI221_X1 $PINS ZN=n_0_105 A=n_0_115 B1=n_0_125 B2=n_0_106 C1=n_27 
+ C2=n_0_132 
Xi_0_113 AOI21_X1 $PINS ZN=n_0_104 A=n_0_105 B1=n_0_133 B2=n_0_117 
Xi_0_112 NAND2_X1 $PINS ZN=Sum[22] A1=n_0_135 A2=n_0_104 
Xi_0_111 AOI22_X1 $PINS ZN=n_0_103 A1=n_22 A2=n_0_136 B1=n_0_117 B2=n_0_116 
Xi_0_110 AOI22_X1 $PINS ZN=n_0_98 A1=n_0_133 A2=n_0_130 B1=n_21 B2=n_0_137 
Xi_0_109 NAND2_X1 $PINS ZN=Sum[21] A1=n_0_103 A2=n_0_98 
Xi_0_108 NAND2_X1 $PINS ZN=n_0_97 A1=n_21 A2=n_0_136 
Xi_0_107 AOI22_X1 $PINS ZN=n_0_93 A1=n_20 A2=n_0_137 B1=n_0_116 B2=n_0_130 
Xi_0_106 OAI211_X1 $PINS ZN=Sum[20] A=n_0_97 B=n_0_93 C1=n_0_134 C2=n_0_100 
Xi_0_105 AOI22_X1 $PINS ZN=n_0_92 A1=n_4 A2=n_0_120 B1=n_12 B2=n_0_114 
Xi_0_104 OAI22_X1 $PINS ZN=n_0_91 A1=n_28 A2=n_0_194 B1=n_0_126 B2=n_0_92 
Xi_0_103 AOI22_X1 $PINS ZN=n_0_90 A1=n_0_125 A2=n_0_195 B1=n_27 B2=n_0_91 
Xi_0_102 AOI22_X1 $PINS ZN=n_0_89 A1=n_20 A2=n_0_136 B1=n_19 B2=n_0_137 
Xi_0_101 OAI221_X1 $PINS ZN=Sum[19] A=n_0_89 B1=n_0_134 B2=n_0_90 C1=n_0_115 
+ C2=n_0_100 
Xi_0_100 AOI22_X1 $PINS ZN=n_0_88 A1=n_19 A2=n_0_136 B1=n_18 B2=n_0_137 
Xi_0_99 NOR3_X2 $PINS ZN=n_0_87 A1=n_30 A2=n_29 A3=n_0_126 
Xi_0_98 NOR3_X1 $PINS ZN=n_0_86 A1=n_30 A2=n_0_128 A3=n_0_126 
Xi_0_97 AOI22_X1 $PINS ZN=n_0_85 A1=n_11 A2=n_0_87 B1=n_3 B2=n_0_86 
Xi_0_96 OAI21_X1 $PINS ZN=n_0_84 A=n_0_85 B1=n_28 B2=n_0_112 
Xi_0_95 AOI22_X1 $PINS ZN=n_0_83 A1=n_27 A2=n_0_84 B1=n_0_125 B2=n_0_101 
Xi_0_94 OAI221_X1 $PINS ZN=Sum[18] A=n_0_88 B1=n_0_115 B2=n_0_90 C1=n_0_134 
+ C2=n_0_83 
Xi_0_93 AOI22_X1 $PINS ZN=n_0_82 A1=n_17 A2=n_0_137 B1=n_18 B2=n_0_136 
Xi_0_92 AOI22_X1 $PINS ZN=n_0_81 A1=n_10 A2=n_0_87 B1=n_2 B2=n_0_86 
Xi_0_91 OAI21_X1 $PINS ZN=n_0_80 A=n_0_81 B1=n_28 B2=n_0_196 
Xi_0_90 AOI22_X1 $PINS ZN=n_0_79 A1=n_0_125 A2=n_0_91 B1=n_27 B2=n_0_80 
Xi_0_89 OAI221_X1 $PINS ZN=Sum[17] A=n_0_82 B1=n_0_134 B2=n_0_79 C1=n_0_115 
+ C2=n_0_83 
Xi_0_88 AOI22_X1 $PINS ZN=n_0_78 A1=n_1 A2=n_0_86 B1=n_9 B2=n_0_87 
Xi_0_87 OAI21_X1 $PINS ZN=n_0_77 A=n_0_78 B1=n_28 B2=n_0_109 
Xi_0_86 AOI22_X1 $PINS ZN=n_0_76 A1=n_0_125 A2=n_0_84 B1=n_27 B2=n_0_77 
Xi_0_85 INV_X1 $PINS ZN=n_0_75 A=n_0_76 
Xi_0_84 AOI22_X1 $PINS ZN=n_0_74 A1=n_0_133 A2=n_0_75 B1=n_17 B2=n_0_136 
Xi_0_83 NAND2_X1 $PINS ZN=n_0_73 A1=n_16 A2=n_0_137 
Xi_0_82 OAI211_X1 $PINS ZN=Sum[16] A=n_0_74 B=n_0_73 C1=n_0_115 C2=n_0_79 
Xi_0_81 AOI22_X1 $PINS ZN=n_0_72 A1=n_0 A2=n_0_86 B1=n_8 B2=n_0_87 
Xi_0_80 OAI21_X1 $PINS ZN=n_0_71 A=n_0_72 B1=n_28 B2=n_0_92 
Xi_0_79 AOI22_X1 $PINS ZN=n_0_70 A1=n_0_125 A2=n_0_80 B1=n_27 B2=n_0_71 
Xi_0_78 AOI22_X1 $PINS ZN=n_0_69 A1=n_16 A2=n_0_136 B1=n_15 B2=n_0_137 
Xi_0_77 OAI221_X1 $PINS ZN=Sum[15] A=n_0_69 B1=n_0_134 B2=n_0_70 C1=n_0_115 
+ C2=n_0_76 
Xi_0_76 AOI222_X1 $PINS ZN=n_0_68 A1=n_11 A2=n_0_113 B1=n_3 B2=n_0_119 C1=n_7 
+ C2=n_0_87 
Xi_0_75 NAND2_X1 $PINS ZN=n_0_67 A1=n_0_125 A2=n_0_77 
Xi_0_74 OAI21_X1 $PINS ZN=n_0_66 A=n_0_67 B1=n_0_125 B2=n_0_68 
Xi_0_73 AOI22_X1 $PINS ZN=n_0_65 A1=n_15 A2=n_0_136 B1=n_0_133 B2=n_0_66 
Xi_0_72 NAND2_X1 $PINS ZN=n_0_64 A1=n_14 A2=n_0_137 
Xi_0_71 OAI211_X1 $PINS ZN=Sum[14] A=n_0_64 B=n_0_65 C1=n_0_115 C2=n_0_70 
Xi_0_70 AOI22_X1 $PINS ZN=n_0_63 A1=n_0_116 A2=n_0_66 B1=n_14 B2=n_0_136 
Xi_0_69 AOI222_X1 $PINS ZN=n_0_62 A1=n_10 A2=n_0_113 B1=n_2 B2=n_0_119 C1=n_6 
+ C2=n_0_87 
Xi_0_68 NAND2_X1 $PINS ZN=n_0_61 A1=n_0_125 A2=n_0_71 
Xi_0_67 OAI21_X1 $PINS ZN=n_0_60 A=n_0_61 B1=n_0_125 B2=n_0_62 
Xi_0_66 AOI22_X1 $PINS ZN=n_0_59 A1=n_13 A2=n_0_137 B1=n_0_133 B2=n_0_60 
Xi_0_65 NAND2_X1 $PINS ZN=Sum[13] A1=n_0_63 A2=n_0_59 
Xi_0_64 AOI222_X1 $PINS ZN=n_0_58 A1=n_9 A2=n_0_113 B1=n_1 B2=n_0_119 C1=n_5 
+ C2=n_0_87 
Xi_0_63 OAI22_X1 $PINS ZN=n_0_57 A1=n_27 A2=n_0_68 B1=n_0_125 B2=n_0_58 
Xi_0_62 AOI22_X1 $PINS ZN=n_0_56 A1=n_0_133 A2=n_0_57 B1=n_13 B2=n_0_136 
Xi_0_61 AOI22_X1 $PINS ZN=n_0_55 A1=n_12 A2=n_0_137 B1=n_0_116 B2=n_0_60 
Xi_0_60 NAND2_X1 $PINS ZN=Sum[12] A1=n_0_56 A2=n_0_55 
Xi_0_59 AOI22_X1 $PINS ZN=n_0_54 A1=n_11 A2=n_0_137 B1=n_12 B2=n_0_136 
Xi_0_58 AOI222_X1 $PINS ZN=n_0_53 A1=n_8 A2=n_0_113 B1=n_0 B2=n_0_119 C1=n_4 
+ C2=n_0_87 
Xi_0_57 OAI22_X1 $PINS ZN=n_0_52 A1=n_27 A2=n_0_62 B1=n_0_125 B2=n_0_53 
Xi_0_56 AOI22_X1 $PINS ZN=n_0_51 A1=n_0_133 A2=n_0_52 B1=n_0_116 B2=n_0_57 
Xi_0_55 NAND2_X1 $PINS ZN=Sum[11] A1=n_0_54 A2=n_0_51 
Xi_0_54 AOI22_X1 $PINS ZN=n_0_50 A1=n_0_116 A2=n_0_52 B1=n_11 B2=n_0_136 
Xi_0_53 AOI22_X1 $PINS ZN=n_0_49 A1=n_7 A2=n_0_113 B1=n_3 B2=n_0_87 
Xi_0_52 OAI22_X1 $PINS ZN=n_0_48 A1=n_0_125 A2=n_0_49 B1=n_27 B2=n_0_58 
Xi_0_51 AOI22_X1 $PINS ZN=n_0_47 A1=n_10 A2=n_0_137 B1=n_0_133 B2=n_0_48 
Xi_0_50 NAND2_X1 $PINS ZN=Sum[10] A1=n_0_50 A2=n_0_47 
Xi_0_49 AOI22_X1 $PINS ZN=n_0_46 A1=n_6 A2=n_0_113 B1=n_2 B2=n_0_87 
Xi_0_48 OAI22_X1 $PINS ZN=n_0_45 A1=n_27 A2=n_0_53 B1=n_0_125 B2=n_0_46 
Xi_0_47 AOI22_X1 $PINS ZN=n_0_44 A1=n_0_133 A2=n_0_45 B1=n_10 B2=n_0_136 
Xi_0_46 AOI22_X1 $PINS ZN=n_0_43 A1=n_9 A2=n_0_137 B1=n_0_116 B2=n_0_48 
Xi_0_45 NAND2_X1 $PINS ZN=Sum[9] A1=n_0_44 A2=n_0_43 
Xi_0_44 AOI22_X1 $PINS ZN=n_0_42 A1=n_9 A2=n_0_136 B1=n_8 B2=n_0_137 
Xi_0_43 AOI22_X1 $PINS ZN=n_0_41 A1=n_5 A2=n_0_113 B1=n_1 B2=n_0_87 
Xi_0_42 OAI22_X1 $PINS ZN=n_0_40 A1=n_27 A2=n_0_49 B1=n_0_125 B2=n_0_41 
Xi_0_41 AOI22_X1 $PINS ZN=n_0_39 A1=n_0_116 A2=n_0_45 B1=n_0_133 B2=n_0_40 
Xi_0_40 NAND2_X1 $PINS ZN=Sum[8] A1=n_0_42 A2=n_0_39 
Xi_0_39 AOI22_X1 $PINS ZN=n_0_38 A1=n_8 A2=n_0_136 B1=n_0_116 B2=n_0_40 
Xi_0_38 AOI22_X1 $PINS ZN=n_0_37 A1=n_4 A2=n_0_113 B1=n_0 B2=n_0_87 
Xi_0_37 OAI22_X1 $PINS ZN=n_0_36 A1=n_27 A2=n_0_46 B1=n_0_125 B2=n_0_37 
Xi_0_36 AOI22_X1 $PINS ZN=n_0_35 A1=n_0_133 A2=n_0_36 B1=n_7 B2=n_0_137 
Xi_0_35 NAND2_X1 $PINS ZN=Sum[7] A1=n_0_38 A2=n_0_35 
Xi_0_34 AND2_X1 $PINS ZN=n_0_34 A1=n_27 A2=n_0_113 
Xi_0_33 NAND2_X1 $PINS ZN=n_0_33 A1=n_3 A2=n_0_34 
Xi_0_32 OAI21_X1 $PINS ZN=n_0_32 A=n_0_33 B1=n_27 B2=n_0_41 
Xi_0_31 AOI22_X1 $PINS ZN=n_0_31 A1=n_0_133 A2=n_0_32 B1=n_7 B2=n_0_136 
Xi_0_30 AOI22_X1 $PINS ZN=n_0_30 A1=n_6 A2=n_0_137 B1=n_0_116 B2=n_0_36 
Xi_0_29 NAND2_X1 $PINS ZN=Sum[6] A1=n_0_31 A2=n_0_30 
Xi_0_28 AOI22_X1 $PINS ZN=n_0_29 A1=n_6 A2=n_0_136 B1=n_0_116 B2=n_0_32 
Xi_0_27 NAND2_X1 $PINS ZN=n_0_28 A1=n_2 A2=n_0_34 
Xi_0_26 OAI21_X1 $PINS ZN=n_0_27 A=n_0_28 B1=n_27 B2=n_0_37 
Xi_0_25 AOI22_X1 $PINS ZN=n_0_26 A1=n_0_133 A2=n_0_27 B1=n_5 B2=n_0_137 
Xi_0_24 NAND2_X1 $PINS ZN=Sum[5] A1=n_0_29 A2=n_0_26 
Xi_0_23 AND2_X1 $PINS ZN=n_0_25 A1=n_0_125 A2=n_0_113 
Xi_0_22 AOI22_X1 $PINS ZN=n_0_24 A1=n_1 A2=n_0_34 B1=n_3 B2=n_0_25 
Xi_0_21 AOI222_X1 $PINS ZN=n_0_23 A1=n_5 A2=n_0_136 B1=n_4 B2=n_0_137 
+ C1=n_0_116 C2=n_0_27 
Xi_0_20 OAI21_X1 $PINS ZN=Sum[4] A=n_0_23 B1=n_0_134 B2=n_0_24 
Xi_0_19 AOI22_X1 $PINS ZN=n_0_22 A1=n_3 A2=n_0_137 B1=n_4 B2=n_0_136 
Xi_0_18 AOI22_X1 $PINS ZN=n_0_21 A1=n_0 A2=n_0_34 B1=n_2 B2=n_0_25 
Xi_0_17 OAI221_X1 $PINS ZN=Sum[3] A=n_0_22 B1=n_0_134 B2=n_0_21 C1=n_0_115 
+ C2=n_0_24 
Xi_0_16 NAND2_X1 $PINS ZN=n_0_20 A1=n_1 A2=n_0_25 
Xi_0_15 AOI22_X1 $PINS ZN=n_0_19 A1=n_3 A2=n_0_136 B1=n_2 B2=n_0_137 
Xi_0_14 OAI221_X1 $PINS ZN=Sum[2] A=n_0_19 B1=n_0_134 B2=n_0_20 C1=n_0_115 
+ C2=n_0_21 
Xi_0_13 AOI21_X1 $PINS ZN=n_0_18 A=n_0_137 B1=n_0_116 B2=n_0_25 
Xi_0_12 INV_X1 $PINS ZN=n_0_17 A=n_0_18 
Xi_0_11 NAND2_X1 $PINS ZN=n_0_16 A1=n_0 A2=n_0_25 
Xi_0_10 AOI22_X1 $PINS ZN=n_0_15 A1=n_1 A2=n_0_17 B1=n_2 B2=n_0_136 
Xi_0_9 OAI21_X1 $PINS ZN=Sum[1] A=n_0_15 B1=n_0_134 B2=n_0_16 
Xi_0_8 AOI22_X1 $PINS ZN=n_0_14 A1=n_0 A2=n_0_17 B1=n_1 B2=n_0_136 
Xi_0_7 INV_X1 $PINS ZN=Sum[0] A=n_0_14 
Xi_0_6 HA_X1 $PINS CO=n_0_6 S=n_0_13 A=exp_Sum[6] B=n_0_5 
Xi_0_5 HA_X1 $PINS CO=n_0_5 S=n_0_12 A=exp_Sum[5] B=n_0_4 
Xi_0_4 HA_X1 $PINS CO=n_0_4 S=n_0_11 A=exp_Sum[4] B=n_0_3 
Xi_0_3 HA_X1 $PINS CO=n_0_3 S=n_0_10 A=exp_Sum[3] B=n_0_2 
Xi_0_2 HA_X1 $PINS CO=n_0_2 S=n_0_9 A=exp_Sum[2] B=n_0_1 
Xi_0_1 HA_X1 $PINS CO=n_0_1 S=n_0_8 A=exp_Sum[1] B=n_0_0 
Xi_0_0 HA_X1 $PINS CO=n_0_0 S=n_0_7 A=n_24 B=exp_Sum[0] 
Xi_22 datapath__0_43 $PINS p_0[31]=n_54 p_0[30]=uc_28 p_0[29]=uc_29 
+ p_0[28]=uc_30 p_0[27]=uc_31 p_0[26]=uc_32 p_0[25]=uc_33 p_0[24]=uc_34 
+ p_0[23]=n_53 p_0[22]=n_52 p_0[21]=n_51 p_0[20]=n_50 p_0[19]=n_49 p_0[18]=n_48 
+ p_0[17]=n_47 p_0[16]=n_46 p_0[15]=n_45 p_0[14]=n_44 p_0[13]=n_43 p_0[12]=n_42 
+ p_0[11]=n_41 p_0[10]=n_40 p_0[9]=n_39 p_0[8]=n_38 p_0[7]=n_37 p_0[6]=n_36 
+ p_0[5]=n_35 p_0[4]=n_34 p_0[3]=n_33 p_0[2]=n_32 p_0[1]=n_31 p_0[0]=uc_35 
+ mant_A[23]=n_100 mant_A[22]=n_76 mant_A[21]=n_75 mant_A[20]=n_74 
+ mant_A[19]=n_73 mant_A[18]=n_72 mant_A[17]=n_71 mant_A[16]=n_70 mant_A[15]=n_69 
+ mant_A[14]=n_68 mant_A[13]=n_67 mant_A[12]=n_66 mant_A[11]=n_65 mant_A[10]=n_64 
+ mant_A[9]=n_63 mant_A[8]=n_62 mant_A[7]=n_99 mant_A[6]=n_61 mant_A[5]=n_60 
+ mant_A[4]=n_59 mant_A[3]=n_58 mant_A[2]=n_57 mant_A[1]=n_56 mant_A[0]=n_55 
Xi_17 datapath__0_38 $PINS p_1[10]=uc_22 p_1[9]=uc_23 p_1[8]=uc_24 p_1[7]=uc_25 
+ p_1[6]=uc_26 p_1[5]=uc_27 p_1[4]=n_30 p_1[3]=n_29 p_1[2]=n_28 p_1[1]=n_27 
+ p_1[0]=n_26 p_0[21]=VSS p_0[20]=VSS p_0[19]=VSS p_0[18]=VSS p_0[17]=VSS 
+ p_0[16]=VSS p_0[15]=VSS p_0[14]=VSS p_0[13]=VSS p_0[12]=VSS 
+ p_0[11]=num_leading_zeros[0] p_0[10]=VSS p_0[9]=VSS p_0[8]=VSS p_0[7]=VSS 
+ p_0[6]=VSS p_0[5]=VSS p_0[4]=num_leading_zeros[4] p_0[3]=num_leading_zeros[3] 
+ p_0[2]=num_leading_zeros[2] p_0[1]=num_leading_zeros[1] p_0[0]=VDD 
Xi_5 datapath__0_25 $PINS p_0=n_25 exp_Sum[7]=exp_Sum[7] exp_Sum[6]=exp_Sum[6] 
+ exp_Sum[5]=exp_Sum[5] exp_Sum[4]=exp_Sum[4] exp_Sum[3]=exp_Sum[3] 
+ exp_Sum[2]=exp_Sum[2] exp_Sum[1]=exp_Sum[1] exp_Sum[0]=exp_Sum[0] p_1[21]=VSS 
+ p_1[20]=VSS p_1[19]=VSS p_1[18]=VSS p_1[17]=VSS p_1[16]=VSS p_1[15]=VSS 
+ p_1[14]=VSS p_1[13]=VSS p_1[12]=VSS p_1[11]=num_leading_zeros[0] p_1[10]=VSS 
+ p_1[9]=VSS p_1[8]=VSS p_1[7]=VSS p_1[6]=VSS p_1[5]=VSS 
+ p_1[4]=num_leading_zeros[4] p_1[3]=num_leading_zeros[3] 
+ p_1[2]=num_leading_zeros[2] p_1[1]=num_leading_zeros[1] p_1[0]=VDD 
Xcount_leading_zeros_instance count_leading_zeros $PINS 
+ result[4]=num_leading_zeros[4] result[3]=num_leading_zeros[3] 
+ result[2]=num_leading_zeros[2] result[1]=num_leading_zeros[1] 
+ result[0]=num_leading_zeros[0] valueIn[22]=n_22 valueIn[21]=n_21 
+ valueIn[20]=n_20 valueIn[19]=n_19 valueIn[18]=n_18 valueIn[17]=n_17 
+ valueIn[16]=n_16 valueIn[15]=n_15 valueIn[14]=n_14 valueIn[13]=n_13 
+ valueIn[12]=n_12 valueIn[11]=n_11 valueIn[10]=n_10 valueIn[9]=n_9 
+ valueIn[8]=n_8 valueIn[7]=n_7 valueIn[6]=n_6 valueIn[5]=n_5 valueIn[4]=n_4 
+ valueIn[3]=n_3 valueIn[2]=n_2 valueIn[1]=n_1 valueIn[0]=n_0 
XCLA_dut CLA $PINS sum[31]=uc_15 sum[30]=uc_16 sum[29]=uc_17 sum[28]=uc_18 
+ sum[27]=uc_19 sum[26]=uc_20 sum[25]=uc_21 sum[24]=n_24 sum[23]=n_23 
+ sum[22]=n_22 sum[21]=n_21 sum[20]=n_20 sum[19]=n_19 sum[18]=n_18 sum[17]=n_17 
+ sum[16]=n_16 sum[15]=n_15 sum[14]=n_14 sum[13]=n_13 sum[12]=n_12 sum[11]=n_11 
+ sum[10]=n_10 sum[9]=n_9 sum[8]=n_8 sum[7]=n_7 sum[6]=n_6 sum[5]=n_5 sum[4]=n_4 
+ sum[3]=n_3 sum[2]=n_2 sum[1]=n_1 sum[0]=n_0 in1[31]=mant_A[31] in1[30]=uc_0 
+ in1[29]=uc_1 in1[28]=uc_2 in1[27]=uc_3 in1[26]=uc_4 in1[25]=uc_5 in1[24]=uc_6 
+ in1[23]=mant_A[23] in1[22]=mant_A[22] in1[21]=mant_A[21] in1[20]=mant_A[20] 
+ in1[19]=mant_A[19] in1[18]=mant_A[18] in1[17]=mant_A[17] in1[16]=mant_A[16] 
+ in1[15]=mant_A[15] in1[14]=mant_A[14] in1[13]=mant_A[13] in1[12]=mant_A[12] 
+ in1[11]=mant_A[11] in1[10]=mant_A[10] in1[9]=mant_A[9] in1[8]=mant_A[8] 
+ in1[7]=mant_A[7] in1[6]=mant_A[6] in1[5]=mant_A[5] in1[4]=mant_A[4] 
+ in1[3]=mant_A[3] in1[2]=mant_A[2] in1[1]=mant_A[1] in1[0]=n_55 in2[31]=uc_7 
+ in2[30]=uc_8 in2[29]=uc_9 in2[28]=uc_10 in2[27]=uc_11 in2[26]=uc_12 
+ in2[25]=uc_13 in2[24]=uc_14 in2[23]=n_102 in2[22]=n_98 in2[21]=n_97 
+ in2[20]=n_96 in2[19]=n_95 in2[18]=n_94 in2[17]=n_93 in2[16]=n_92 in2[15]=n_91 
+ in2[14]=n_90 in2[13]=n_89 in2[12]=n_88 in2[11]=n_87 in2[10]=n_86 in2[9]=n_85 
+ in2[8]=n_84 in2[7]=n_83 in2[6]=n_82 in2[5]=n_101 in2[4]=n_81 in2[3]=n_80 
+ in2[2]=n_79 in2[1]=n_78 in2[0]=n_77 
Xdrc_ipo_c4 CLKBUF_X1 $PINS Z=drc_ipo_n4 A=n_0_470 
.ENDS

.SUBCKT buffer__0_58 clk_CTS_1_PP_0 clk rst en D[31] D[30] D[29] D[28] D[27] 
+ D[26] D[25] D[24] D[23] D[22] D[21] D[20] D[19] D[18] D[17] D[16] D[15] D[14] 
+ D[13] D[12] D[11] D[10] D[9] D[8] D[7] D[6] D[5] D[4] D[3] D[2] D[1] D[0] 
+ Q[31] Q[30] Q[29] Q[28] Q[27] Q[26] Q[25] Q[24] Q[23] Q[22] Q[21] Q[20] Q[19] 
+ Q[18] Q[17] Q[16] Q[15] Q[14] Q[13] Q[12] Q[11] Q[10] Q[9] Q[8] Q[7] Q[6] 
+ Q[5] Q[4] Q[3] Q[2] Q[1] Q[0] 
Xi_0_33 AND2_X1 $PINS ZN=n_33 A1=n_0_0 A2=D[31] 
Xi_0_32 AND2_X1 $PINS ZN=n_32 A1=n_0_0 A2=D[30] 
Xi_0_31 AND2_X1 $PINS ZN=n_31 A1=n_0_0 A2=D[29] 
Xi_0_30 AND2_X1 $PINS ZN=n_30 A1=n_0_0 A2=D[28] 
Xi_0_29 AND2_X1 $PINS ZN=n_29 A1=n_0_0 A2=D[27] 
Xi_0_28 AND2_X1 $PINS ZN=n_28 A1=n_0_0 A2=D[26] 
Xi_0_27 AND2_X1 $PINS ZN=n_27 A1=n_0_0 A2=D[25] 
Xi_0_26 AND2_X1 $PINS ZN=n_26 A1=n_0_0 A2=D[24] 
Xi_0_25 AND2_X1 $PINS ZN=n_25 A1=n_0_0 A2=D[23] 
Xi_0_24 AND2_X1 $PINS ZN=n_24 A1=n_0_0 A2=D[22] 
Xi_0_23 AND2_X1 $PINS ZN=n_23 A1=n_0_0 A2=D[21] 
Xi_0_22 AND2_X1 $PINS ZN=n_22 A1=n_0_0 A2=D[20] 
Xi_0_21 AND2_X1 $PINS ZN=n_21 A1=n_0_0 A2=D[19] 
Xi_0_20 AND2_X1 $PINS ZN=n_20 A1=n_0_0 A2=D[18] 
Xi_0_19 AND2_X1 $PINS ZN=n_19 A1=n_0_0 A2=D[17] 
Xi_0_18 AND2_X1 $PINS ZN=n_18 A1=n_0_0 A2=D[16] 
Xi_0_17 AND2_X1 $PINS ZN=n_17 A1=n_0_0 A2=D[15] 
Xi_0_16 AND2_X1 $PINS ZN=n_16 A1=n_0_0 A2=D[14] 
Xi_0_15 AND2_X1 $PINS ZN=n_15 A1=n_0_0 A2=D[13] 
Xi_0_14 AND2_X1 $PINS ZN=n_14 A1=n_0_0 A2=D[12] 
Xi_0_13 AND2_X1 $PINS ZN=n_13 A1=n_0_0 A2=D[11] 
Xi_0_12 AND2_X1 $PINS ZN=n_12 A1=n_0_0 A2=D[10] 
Xi_0_11 AND2_X1 $PINS ZN=n_11 A1=n_0_0 A2=D[9] 
Xi_0_10 AND2_X1 $PINS ZN=n_10 A1=n_0_0 A2=D[8] 
Xi_0_9 AND2_X1 $PINS ZN=n_9 A1=n_0_0 A2=D[7] 
Xi_0_8 AND2_X1 $PINS ZN=n_8 A1=n_0_0 A2=D[6] 
Xi_0_7 AND2_X1 $PINS ZN=n_7 A1=n_0_0 A2=D[5] 
Xi_0_6 AND2_X1 $PINS ZN=n_6 A1=n_0_0 A2=D[4] 
Xi_0_5 AND2_X1 $PINS ZN=n_5 A1=n_0_0 A2=D[3] 
Xi_0_4 AND2_X1 $PINS ZN=n_4 A1=n_0_0 A2=D[2] 
Xi_0_3 AND2_X1 $PINS ZN=n_3 A1=n_0_0 A2=D[1] 
Xi_0_2 AND2_X1 $PINS ZN=n_2 A1=n_0_0 A2=D[0] 
Xi_0_1 INV_X1 $PINS ZN=n_0_0 A=rst 
Xi_0_0 OR2_X1 $PINS ZN=n_1 A1=en A2=rst 
XQ_reg[0] DFF_X1 $PINS Q=Q[0] CK=CTS_n_tid1_48 D=n_2 
XQ_reg[1] DFF_X1 $PINS Q=Q[1] CK=CTS_n_tid1_48 D=n_3 
XQ_reg[2] DFF_X1 $PINS Q=Q[2] CK=CTS_n_tid1_48 D=n_4 
XQ_reg[3] DFF_X1 $PINS Q=Q[3] CK=CTS_n_tid1_48 D=n_5 
XQ_reg[4] DFF_X1 $PINS Q=Q[4] CK=CTS_n_tid1_48 D=n_6 
XQ_reg[5] DFF_X1 $PINS Q=Q[5] CK=CTS_n_tid1_48 D=n_7 
XQ_reg[6] DFF_X1 $PINS Q=Q[6] CK=CTS_n_tid1_48 D=n_8 
XQ_reg[7] DFF_X1 $PINS Q=Q[7] CK=CTS_n_tid1_48 D=n_9 
XQ_reg[8] DFF_X1 $PINS Q=Q[8] CK=CTS_n_tid1_48 D=n_10 
XQ_reg[9] DFF_X1 $PINS Q=Q[9] CK=CTS_n_tid1_48 D=n_11 
XQ_reg[10] DFF_X1 $PINS Q=Q[10] CK=CTS_n_tid1_48 D=n_12 
XQ_reg[11] DFF_X1 $PINS Q=Q[11] CK=CTS_n_tid1_48 D=n_13 
XQ_reg[12] DFF_X1 $PINS Q=Q[12] CK=CTS_n_tid1_48 D=n_14 
XQ_reg[13] DFF_X1 $PINS Q=Q[13] CK=CTS_n_tid1_48 D=n_15 
XQ_reg[14] DFF_X1 $PINS Q=Q[14] CK=CTS_n_tid1_48 D=n_16 
XQ_reg[15] DFF_X1 $PINS Q=Q[15] CK=CTS_n_tid1_48 D=n_17 
XQ_reg[16] DFF_X1 $PINS Q=Q[16] CK=CTS_n_tid1_48 D=n_18 
XQ_reg[17] DFF_X1 $PINS Q=Q[17] CK=CTS_n_tid1_48 D=n_19 
XQ_reg[18] DFF_X1 $PINS Q=Q[18] CK=CTS_n_tid1_48 D=n_20 
XQ_reg[19] DFF_X1 $PINS Q=Q[19] CK=CTS_n_tid1_48 D=n_21 
XQ_reg[20] DFF_X1 $PINS Q=Q[20] CK=CTS_n_tid1_48 D=n_22 
XQ_reg[21] DFF_X1 $PINS Q=Q[21] CK=CTS_n_tid1_48 D=n_23 
XQ_reg[22] DFF_X1 $PINS Q=Q[22] CK=CTS_n_tid1_48 D=n_24 
XQ_reg[23] DFF_X1 $PINS Q=Q[23] CK=CTS_n_tid1_48 D=n_25 
XQ_reg[24] DFF_X1 $PINS Q=Q[24] CK=CTS_n_tid1_48 D=n_26 
XQ_reg[25] DFF_X1 $PINS Q=Q[25] CK=CTS_n_tid1_48 D=n_27 
XQ_reg[26] DFF_X1 $PINS Q=Q[26] CK=CTS_n_tid1_48 D=n_28 
XQ_reg[27] DFF_X1 $PINS Q=Q[27] CK=CTS_n_tid1_48 D=n_29 
XQ_reg[28] DFF_X1 $PINS Q=Q[28] CK=CTS_n_tid1_48 D=n_30 
XQ_reg[29] DFF_X1 $PINS Q=Q[29] CK=CTS_n_tid1_48 D=n_31 
XQ_reg[30] DFF_X1 $PINS Q=Q[30] CK=CTS_n_tid1_48 D=n_32 
XQ_reg[31] DFF_X1 $PINS Q=Q[31] CK=CTS_n_tid1_48 D=n_33 
Xclk_gate_Q_reg CLKGATETST_X8 $PINS GCK=CTS_n_tid1_48 CK=clk_CTS_1_PP_0 E=n_1 
+ SE=VSS 
.ENDS

.SUBCKT buffer__0_55 clk_CTS_1_PP_0 clk rst en D[31] D[30] D[29] D[28] D[27] 
+ D[26] D[25] D[24] D[23] D[22] D[21] D[20] D[19] D[18] D[17] D[16] D[15] D[14] 
+ D[13] D[12] D[11] D[10] D[9] D[8] D[7] D[6] D[5] D[4] D[3] D[2] D[1] D[0] 
+ Q[31] Q[30] Q[29] Q[28] Q[27] Q[26] Q[25] Q[24] Q[23] Q[22] Q[21] Q[20] Q[19] 
+ Q[18] Q[17] Q[16] Q[15] Q[14] Q[13] Q[12] Q[11] Q[10] Q[9] Q[8] Q[7] Q[6] 
+ Q[5] Q[4] Q[3] Q[2] Q[1] Q[0] 
Xi_0_33 AND2_X1 $PINS ZN=n_33 A1=n_0_0 A2=D[31] 
Xi_0_32 AND2_X1 $PINS ZN=n_32 A1=n_0_0 A2=D[30] 
Xi_0_31 AND2_X1 $PINS ZN=n_31 A1=n_0_0 A2=D[29] 
Xi_0_30 AND2_X1 $PINS ZN=n_30 A1=n_0_0 A2=D[28] 
Xi_0_29 AND2_X1 $PINS ZN=n_29 A1=n_0_0 A2=D[27] 
Xi_0_28 AND2_X1 $PINS ZN=n_28 A1=n_0_0 A2=D[26] 
Xi_0_27 AND2_X1 $PINS ZN=n_27 A1=n_0_0 A2=D[25] 
Xi_0_26 AND2_X1 $PINS ZN=n_26 A1=n_0_0 A2=D[24] 
Xi_0_25 AND2_X1 $PINS ZN=n_25 A1=n_0_0 A2=D[23] 
Xi_0_24 AND2_X1 $PINS ZN=n_24 A1=n_0_0 A2=D[22] 
Xi_0_23 AND2_X1 $PINS ZN=n_23 A1=n_0_0 A2=D[21] 
Xi_0_22 AND2_X1 $PINS ZN=n_22 A1=n_0_0 A2=D[20] 
Xi_0_21 AND2_X1 $PINS ZN=n_21 A1=n_0_0 A2=D[19] 
Xi_0_20 AND2_X1 $PINS ZN=n_20 A1=n_0_0 A2=D[18] 
Xi_0_19 AND2_X1 $PINS ZN=n_19 A1=n_0_0 A2=D[17] 
Xi_0_18 AND2_X1 $PINS ZN=n_18 A1=n_0_0 A2=D[16] 
Xi_0_17 AND2_X1 $PINS ZN=n_17 A1=n_0_0 A2=D[15] 
Xi_0_16 AND2_X1 $PINS ZN=n_16 A1=n_0_0 A2=D[14] 
Xi_0_15 AND2_X1 $PINS ZN=n_15 A1=n_0_0 A2=D[13] 
Xi_0_14 AND2_X1 $PINS ZN=n_14 A1=n_0_0 A2=D[12] 
Xi_0_13 AND2_X1 $PINS ZN=n_13 A1=n_0_0 A2=D[11] 
Xi_0_12 AND2_X1 $PINS ZN=n_12 A1=n_0_0 A2=D[10] 
Xi_0_11 AND2_X1 $PINS ZN=n_11 A1=n_0_0 A2=D[9] 
Xi_0_10 AND2_X1 $PINS ZN=n_10 A1=n_0_0 A2=D[8] 
Xi_0_9 AND2_X1 $PINS ZN=n_9 A1=n_0_0 A2=D[7] 
Xi_0_8 AND2_X1 $PINS ZN=n_8 A1=n_0_0 A2=D[6] 
Xi_0_7 AND2_X1 $PINS ZN=n_7 A1=n_0_0 A2=D[5] 
Xi_0_6 AND2_X1 $PINS ZN=n_6 A1=n_0_0 A2=D[4] 
Xi_0_5 AND2_X1 $PINS ZN=n_5 A1=n_0_0 A2=D[3] 
Xi_0_4 AND2_X1 $PINS ZN=n_4 A1=n_0_0 A2=D[2] 
Xi_0_3 AND2_X1 $PINS ZN=n_3 A1=n_0_0 A2=D[1] 
Xi_0_2 AND2_X1 $PINS ZN=n_2 A1=n_0_0 A2=D[0] 
Xi_0_1 INV_X1 $PINS ZN=n_0_0 A=rst 
Xi_0_0 OR2_X1 $PINS ZN=n_1 A1=en A2=rst 
XQ_reg[0] DFF_X1 $PINS Q=Q[0] CK=n_0 D=n_2 
XQ_reg[1] DFF_X1 $PINS Q=Q[1] CK=n_0 D=n_3 
XQ_reg[2] DFF_X1 $PINS Q=Q[2] CK=n_0 D=n_4 
XQ_reg[3] DFF_X1 $PINS Q=Q[3] CK=n_0 D=n_5 
XQ_reg[4] DFF_X1 $PINS Q=Q[4] CK=n_0 D=n_6 
XQ_reg[5] DFF_X1 $PINS Q=Q[5] CK=n_0 D=n_7 
XQ_reg[6] DFF_X1 $PINS Q=Q[6] CK=n_0 D=n_8 
XQ_reg[7] DFF_X1 $PINS Q=Q[7] CK=n_0 D=n_9 
XQ_reg[8] DFF_X1 $PINS Q=Q[8] CK=n_0 D=n_10 
XQ_reg[9] DFF_X1 $PINS Q=Q[9] CK=n_0 D=n_11 
XQ_reg[10] DFF_X1 $PINS Q=Q[10] CK=n_0 D=n_12 
XQ_reg[11] DFF_X1 $PINS Q=Q[11] CK=n_0 D=n_13 
XQ_reg[12] DFF_X1 $PINS Q=Q[12] CK=n_0 D=n_14 
XQ_reg[13] DFF_X1 $PINS Q=Q[13] CK=n_0 D=n_15 
XQ_reg[14] DFF_X1 $PINS Q=Q[14] CK=n_0 D=n_16 
XQ_reg[15] DFF_X1 $PINS Q=Q[15] CK=n_0 D=n_17 
XQ_reg[16] DFF_X1 $PINS Q=Q[16] CK=n_0 D=n_18 
XQ_reg[17] DFF_X1 $PINS Q=Q[17] CK=n_0 D=n_19 
XQ_reg[18] DFF_X1 $PINS Q=Q[18] CK=n_0 D=n_20 
XQ_reg[19] DFF_X1 $PINS Q=Q[19] CK=n_0 D=n_21 
XQ_reg[20] DFF_X1 $PINS Q=Q[20] CK=n_0 D=n_22 
XQ_reg[21] DFF_X1 $PINS Q=Q[21] CK=n_0 D=n_23 
XQ_reg[22] DFF_X1 $PINS Q=Q[22] CK=n_0 D=n_24 
XQ_reg[23] DFF_X1 $PINS Q=Q[23] CK=n_0 D=n_25 
XQ_reg[24] DFF_X1 $PINS Q=Q[24] CK=n_0 D=n_26 
XQ_reg[25] DFF_X1 $PINS Q=Q[25] CK=n_0 D=n_27 
XQ_reg[26] DFF_X1 $PINS Q=Q[26] CK=n_0 D=n_28 
XQ_reg[27] DFF_X1 $PINS Q=Q[27] CK=n_0 D=n_29 
XQ_reg[28] DFF_X1 $PINS Q=Q[28] CK=n_0 D=n_30 
XQ_reg[29] DFF_X1 $PINS Q=Q[29] CK=n_0 D=n_31 
XQ_reg[30] DFF_X1 $PINS Q=Q[30] CK=n_0 D=n_32 
XQ_reg[31] DFF_X1 $PINS Q=Q[31] CK=n_0 D=n_33 
Xclk_gate_Q_reg CLKGATETST_X1 $PINS GCK=n_0 CK=clk_CTS_1_PP_0 E=n_1 SE=VSS 
.ENDS

.SUBCKT fp_adder_buff clk rst en a[31] a[30] a[29] a[28] a[27] a[26] a[25] 
+ a[24] a[23] a[22] a[21] a[20] a[19] a[18] a[17] a[16] a[15] a[14] a[13] a[12] 
+ a[11] a[10] a[9] a[8] a[7] a[6] a[5] a[4] a[3] a[2] a[1] a[0] b[31] b[30] 
+ b[29] b[28] b[27] b[26] b[25] b[24] b[23] b[22] b[21] b[20] b[19] b[18] b[17] 
+ b[16] b[15] b[14] b[13] b[12] b[11] b[10] b[9] b[8] b[7] b[6] b[5] b[4] b[3] 
+ b[2] b[1] b[0] sum[31] sum[30] sum[29] sum[28] sum[27] sum[26] sum[25] 
+ sum[24] sum[23] sum[22] sum[21] sum[20] sum[19] sum[18] sum[17] sum[16] 
+ sum[15] sum[14] sum[13] sum[12] sum[11] sum[10] sum[9] sum[8] sum[7] sum[6] 
+ sum[5] sum[4] sum[3] sum[2] sum[1] sum[0] overflow underflow 
XoutRegU buffer__parameterized0 $PINS Q[0]=underflow D[0]=underflow_out en=en 
+ rst=rst clk_CTS_1_PP_0=CTS_n_tid1_3 
XoutRegO buffer__parameterized0__0_52 $PINS Q[0]=overflow 
+ clk_CTS_1_PP_0=CTS_n_tid1_3 D[0]=overflow_out en=en rst=rst clk_CTS_1_PP_8=clk 
XoutRegS buffer $PINS Q[31]=sum[31] Q[30]=sum[30] Q[29]=sum[29] Q[28]=sum[28] 
+ Q[27]=sum[27] Q[26]=sum[26] Q[25]=sum[25] Q[24]=sum[24] Q[23]=sum[23] 
+ Q[22]=sum[22] Q[21]=sum[21] Q[20]=sum[20] Q[19]=sum[19] Q[18]=sum[18] 
+ Q[17]=sum[17] Q[16]=sum[16] Q[15]=sum[15] Q[14]=sum[14] Q[13]=sum[13] 
+ Q[12]=sum[12] Q[11]=sum[11] Q[10]=sum[10] Q[9]=sum[9] Q[8]=sum[8] Q[7]=sum[7] 
+ Q[6]=sum[6] Q[5]=sum[5] Q[4]=sum[4] Q[3]=sum[3] Q[2]=sum[2] Q[1]=sum[1] 
+ Q[0]=sum[0] D[31]=sum_out[31] D[30]=sum_out[30] D[29]=sum_out[29] 
+ D[28]=sum_out[28] D[27]=sum_out[27] D[26]=sum_out[26] D[25]=sum_out[25] 
+ D[24]=sum_out[24] D[23]=sum_out[23] D[22]=sum_out[22] D[21]=sum_out[21] 
+ D[20]=sum_out[20] D[19]=sum_out[19] D[18]=sum_out[18] D[17]=sum_out[17] 
+ D[16]=sum_out[16] D[15]=sum_out[15] D[14]=sum_out[14] D[13]=sum_out[13] 
+ D[12]=sum_out[12] D[11]=sum_out[11] D[10]=sum_out[10] D[9]=sum_out[9] 
+ D[8]=sum_out[8] D[7]=sum_out[7] D[6]=sum_out[6] D[5]=sum_out[5] D[4]=sum_out[4] 
+ D[3]=sum_out[3] D[2]=sum_out[2] D[1]=sum_out[1] D[0]=sum_out[0] en=en rst=rst 
+ clk_CTS_1_PP_3=clk 
XA32 fp_adder $PINS Sum[31]=sum_out[31] Sum[30]=sum_out[30] Sum[29]=sum_out[29] 
+ Sum[28]=sum_out[28] Sum[27]=sum_out[27] Sum[26]=sum_out[26] Sum[25]=sum_out[25] 
+ Sum[24]=sum_out[24] Sum[23]=sum_out[23] Sum[22]=sum_out[22] Sum[21]=sum_out[21] 
+ Sum[20]=sum_out[20] Sum[19]=sum_out[19] Sum[18]=sum_out[18] Sum[17]=sum_out[17] 
+ Sum[16]=sum_out[16] Sum[15]=sum_out[15] Sum[14]=sum_out[14] Sum[13]=sum_out[13] 
+ Sum[12]=sum_out[12] Sum[11]=sum_out[11] Sum[10]=sum_out[10] Sum[9]=sum_out[9] 
+ Sum[8]=sum_out[8] Sum[7]=sum_out[7] Sum[6]=sum_out[6] Sum[5]=sum_out[5] 
+ Sum[4]=sum_out[4] Sum[3]=sum_out[3] Sum[2]=sum_out[2] Sum[1]=sum_out[1] 
+ Sum[0]=sum_out[0] overflow=overflow_out underflow=underflow_out A[31]=a_out[31] 
+ A[30]=a_out[30] A[29]=a_out[29] A[28]=a_out[28] A[27]=a_out[27] A[26]=a_out[26] 
+ A[25]=a_out[25] A[24]=a_out[24] A[23]=a_out[23] A[22]=a_out[22] A[21]=a_out[21] 
+ A[20]=a_out[20] A[19]=a_out[19] A[18]=a_out[18] A[17]=a_out[17] A[16]=a_out[16] 
+ A[15]=a_out[15] A[14]=a_out[14] A[13]=a_out[13] A[12]=a_out[12] A[11]=a_out[11] 
+ A[10]=a_out[10] A[9]=a_out[9] A[8]=a_out[8] A[7]=a_out[7] A[6]=a_out[6] 
+ A[5]=a_out[5] A[4]=a_out[4] A[3]=a_out[3] A[2]=a_out[2] A[1]=a_out[1] 
+ A[0]=a_out[0] B[31]=b_out[31] B[30]=b_out[30] B[29]=b_out[29] B[28]=b_out[28] 
+ B[27]=b_out[27] B[26]=b_out[26] B[25]=b_out[25] B[24]=b_out[24] B[23]=b_out[23] 
+ B[22]=b_out[22] B[21]=b_out[21] B[20]=b_out[20] B[19]=b_out[19] B[18]=b_out[18] 
+ B[17]=b_out[17] B[16]=b_out[16] B[15]=b_out[15] B[14]=b_out[14] B[13]=b_out[13] 
+ B[12]=b_out[12] B[11]=b_out[11] B[10]=b_out[10] B[9]=b_out[9] B[8]=b_out[8] 
+ B[7]=b_out[7] B[6]=b_out[6] B[5]=b_out[5] B[4]=b_out[4] B[3]=b_out[3] 
+ B[2]=b_out[2] B[1]=b_out[1] B[0]=b_out[0] 
XinRegB buffer__0_58 $PINS Q[31]=b_out[31] Q[30]=b_out[30] Q[29]=b_out[29] 
+ Q[28]=b_out[28] Q[27]=b_out[27] Q[26]=b_out[26] Q[25]=b_out[25] Q[24]=b_out[24] 
+ Q[23]=b_out[23] Q[22]=b_out[22] Q[21]=b_out[21] Q[20]=b_out[20] Q[19]=b_out[19] 
+ Q[18]=b_out[18] Q[17]=b_out[17] Q[16]=b_out[16] Q[15]=b_out[15] Q[14]=b_out[14] 
+ Q[13]=b_out[13] Q[12]=b_out[12] Q[11]=b_out[11] Q[10]=b_out[10] Q[9]=b_out[9] 
+ Q[8]=b_out[8] Q[7]=b_out[7] Q[6]=b_out[6] Q[5]=b_out[5] Q[4]=b_out[4] 
+ Q[3]=b_out[3] Q[2]=b_out[2] Q[1]=b_out[1] Q[0]=b_out[0] D[31]=b[31] D[30]=b[30] 
+ D[29]=b[29] D[28]=b[28] D[27]=b[27] D[26]=b[26] D[25]=b[25] D[24]=b[24] 
+ D[23]=b[23] D[22]=b[22] D[21]=b[21] D[20]=b[20] D[19]=b[19] D[18]=b[18] 
+ D[17]=b[17] D[16]=b[16] D[15]=b[15] D[14]=b[14] D[13]=b[13] D[12]=b[12] 
+ D[11]=b[11] D[10]=b[10] D[9]=b[9] D[8]=b[8] D[7]=b[7] D[6]=b[6] D[5]=b[5] 
+ D[4]=b[4] D[3]=b[3] D[2]=b[2] D[1]=b[1] D[0]=b[0] en=en rst=rst 
+ clk_CTS_1_PP_0=CTS_n_tid1_3 
XinRegA buffer__0_55 $PINS Q[31]=a_out[31] Q[30]=a_out[30] Q[29]=a_out[29] 
+ Q[28]=a_out[28] Q[27]=a_out[27] Q[26]=a_out[26] Q[25]=a_out[25] Q[24]=a_out[24] 
+ Q[23]=a_out[23] Q[22]=a_out[22] Q[21]=a_out[21] Q[20]=a_out[20] Q[19]=a_out[19] 
+ Q[18]=a_out[18] Q[17]=a_out[17] Q[16]=a_out[16] Q[15]=a_out[15] Q[14]=a_out[14] 
+ Q[13]=a_out[13] Q[12]=a_out[12] Q[11]=a_out[11] Q[10]=a_out[10] Q[9]=a_out[9] 
+ Q[8]=a_out[8] Q[7]=a_out[7] Q[6]=a_out[6] Q[5]=a_out[5] Q[4]=a_out[4] 
+ Q[3]=a_out[3] Q[2]=a_out[2] Q[1]=a_out[1] Q[0]=a_out[0] D[31]=a[31] D[30]=a[30] 
+ D[29]=a[29] D[28]=a[28] D[27]=a[27] D[26]=a[26] D[25]=a[25] D[24]=a[24] 
+ D[23]=a[23] D[22]=a[22] D[21]=a[21] D[20]=a[20] D[19]=a[19] D[18]=a[18] 
+ D[17]=a[17] D[16]=a[16] D[15]=a[15] D[14]=a[14] D[13]=a[13] D[12]=a[12] 
+ D[11]=a[11] D[10]=a[10] D[9]=a[9] D[8]=a[8] D[7]=a[7] D[6]=a[6] D[5]=a[5] 
+ D[4]=a[4] D[3]=a[3] D[2]=a[2] D[1]=a[1] D[0]=a[0] en=en rst=rst 
+ clk_CTS_1_PP_0=CTS_n_tid1_3 
.ENDS
.GLOBAL VDD 
.GLOBAL VSS 
